# -*- coding: utf-8 -*-
from ._refs import COMMON_REFS

topic = {
    "num": 3,
    "title": "Maktabgacha ta'lim tashkilotlarida kichik yoshdagi bolalarning nutqini o'stirish metodlari va vositalari",
    "reja": [
        "Kichik yoshdagi bolalar nutqi xususiyatlari va rivojlanish bosqichlari.",
        "Kichik guruh bolalari nutqini o'stirishning asosiy metodlari.",
        "Asosiy ta'lim vositalari: o'yinchoq, surat, kitob va boshqalar.",
        "Mashg'ulotlarni tashkil etish va kundalik tartib elementlari.",
        "Oilada va MTTda kichik yosh bolasi bilan hamkorlikda ishlash.",
    ],
    "sections": [
        (
            "Kichik yoshdagi bolalar nutqi xususiyatlari va rivojlanish bosqichlari",
            [
                "Kichik yosh guruhi (3-4 yosh) — bolaning faol nutq qobiliyatlari intensiv shakllanadigan, lekin ayni paytda ko'plab xususiyatlar va kamchiliklar bilan ajralib turadigan davrdir. Bu yoshda bola atrof-olamni faol o'rganadi, har bir narsaga qiziqib qaraydi va son-sanoqsiz savollar so'raydi. Tarbiyachi bu qiziqishni saqlash va undan unumli foydalanishni bilishi shart, chunki aynan qiziqish — nutqni rivojlantirishning eng kuchli motoridir.",
                "Bu yoshdagi bolaning lug'at boyligi 800 dan 1500 so'zgacha bo'ladi. U ko'pchilik kundalik narsalarni nomlay oladi, asosiy harakatlarni va sifatlarni biladi, oddiy gaplar tuza oladi. Lekin bola ko'pincha so'zlarning ma'nosini chuqur tushunmaydi, ularni xato qo'llaydi, ko'pma'noli so'zlarning bir ma'nosini biladi xolos. Tarbiyachining vazifasi — har bir so'zni bola uchun aniq, hayotiy va tushunarli qilib taqdim etishdir.",
                "Tovushlarni talaffuz qilishda kichik yosh bolasida ko'plab kamchiliklar uchraydi. \"R\" tovushini ko'pchilik bolalar 4-5 yoshgacha to'g'ri talaffuz qila olmaydi. Shuningdek, [sh], [j], [ch], [s], [z] tovushlari ham qiyinchilik tug'diradi. Bu — yoshga xos hodisa, va ko'p hollarda maxsus ish olib borishni talab qilmaydi. Lekin tarbiyachi bolalar nutqini diqqat bilan kuzatib, agar zarurat bo'lsa, logoped maslahatini olishi shart.",
                "Grammatik jihatdan kichik yosh bolasi sodda gaplardan murakkab gaplarga o'tib boradi. \"Otam ishga ketdi\", \"Onam meni bog'chaga olib keldi\" kabi 4-5 so'zli sodda gaplar normal hisoblanadi. Lekin bola ko'pincha qo'shimchalarni xato ishlatadi: \"otaga\" o'rniga \"otani\", \"sotgan\" o'rniga \"sotdik\" deyishi mumkin. Bunday xatolar yoshga xos va asta-sekin kamayib boradi.",
                "Dialogik nutq jihatidan kichik yosh bolasi tarbiyachining savollariga javob bera oladi, oddiy talab va istaklarini bayon eta oladi, kattalar bilan suhbatga kirisha oladi. Lekin uning suhbati ko'pincha qisqa, sodda va to'g'ridan-to'g'ridir. Bola fikrini chuqur va to'liq bayon eta olmaydi, savollarga aniq va to'liq javob bera olmaydi. Bu — kichik guruh bolasi uchun kutilgan holat va asta-sekin yengilashtiriladi.",
                "Monologik nutq esa hali shakllanmagan. Bola surat asosida 1-2 jumla aytishi, predmetni 2-3 belgisi bilan tasvirlay olishi mumkin, lekin uzun, izchil hikoya tuza olmaydi. Tarbiyachi bu yoshda monologik nutqni jiddiy talab qilmaydi, balki uning shakllanishi uchun zamin tayyorlaydi: ertaklar tinglatadi, sodda hikoyalar aytib beradi, savollar orqali bolaning hikoyasini boshqaradi.",
                "Kichik yosh bolasining nutq sezgirligi (xotirasi va taqlid qilish qobiliyati) juda yuqori. Bu yoshdagi bola eshitgan har bir so'zni, ohangni, ifodani osongina o'zlashtiradi. Ammo bu xususiyat ham ijobiy, ham salbiy bo'lishi mumkin: bola yaxshi nutqdan ham, qo'pol nutqdan ham namuna oladi. Shu sababli tarbiyachi va ota-onalarning nutqi bola uchun namuna sifatida xizmat qilishi shart. Bola atrof-muhitdan o'rganadi — buni asla unutmaslik kerak.",
            ],
        ),
        (
            "Kichik guruh bolalari nutqini o'stirishning asosiy metodlari",
            [
                "Kichik guruhda nutqni o'stirishning asosiy metodlari quyidagilardir: kuzatish va idrok etish metodi; suhbat metodi; o'qish va aytib berish metodi; didaktik o'yin metodi; mashqlar metodi; ko'rgazmali metodlar; amaliy metodlar. Har bir metodni qo'llash bola yoshini, individual xususiyatlarini, mavzu mazmunini hisobga olib amalga oshiriladi. Metodlar bir-birini to'ldiradi va birgalikda ishlaydi.",
                "Kuzatish va idrok etish metodi — bola turli xil predmet va hodisalarni o'z ko'zi bilan ko'rib, qo'li bilan ushlab, hidlab, ta'mini sezib o'rganishidan iborat. Bog'cha hududidagi gullarni, daraxtlarni, qushlarni kuzatish, oshxonadagi non, sabzavotlar bilan tanishish, hayvonot bog'iga ekskursiya — bularning hammasi kuzatish metodining namunalaridir. Bola ko'rgan, ushlagan narsasi haqida nutq qila boshlaydi va shu yo'l bilan lug'ati boyiyadi.",
                "Suhbat metodi — tarbiyachining bola bilan o'tkazadigan savol-javobi. Suhbat erkin (bolaning xohish va istaklariga muvofiq) yoki rejalashtirilgan (muayyan mavzu bo'yicha) bo'lishi mumkin. Kichik guruhda suhbat ko'pincha individual yoki kichik guruh bilan o'tkaziladi, chunki bolalar uzoq diqqatini bir mavzuda ushlab tura olmaydi. Suhbat oddiy savollardan boshlanadi va asta-sekin murakkab savollar qo'yiladi.",
                "Badiiy adabiyot bilan tanishtirish metodi alohida ahamiyatga ega. Tarbiyachi bolalarga sodda ertaklar (\"Bo'g'irsoq\", \"Sholg'om\", \"Tovuq va Saroq jo'jacha\"), bolalar she'rlari, qo'shiqlar, topishmoqlar bilan tanishtiradi. Asarni o'qib bergandan keyin albatta savol-javob, suhbat o'tkaziladi: \"Asarda kim qatnashdi?\", \"Nima bo'ldi?\", \"Bola qanday ish qildi?\" kabi savollar bola fikrini ishga soladi va lug'atini boyitadi.",
                "Didaktik o'yin metodi — kichik guruh bolalari nutqini o'stirishning eng samarali vositalaridan biridir. Bolalar o'yin orqali bilim oladi, ular uchun o'yin — eng mahsuldor faoliyatdir. \"Sehrli qopcha\" o'yini (bolalar paypaslab predmetlarni topadilar va nomlaydilar), \"Kim nima qiladi?\" (suratlar bo'yicha hayvonlar va ularning harakatlarini aniqlash), \"Ushbu narsa qayerda?\" (mekan munosabatlari) kabi o'yinlar lug'at va grammatik vazifalarni hal etadi.",
                "Ko'rgazmali metodlar — turli xil suratlar, kartochkalar, qo'g'irchoqlar, modellar va boshqa ko'rgazma vositalari yordamida o'tkaziladigan ish usullari. Kichik yoshdagi bola fikrlashi ko'rgazmali-amaliy va ko'rgazmali-obrazli xarakterda bo'lganligi uchun, ko'rgazma vositalari mashg'ulotlarning ajralmas qismi hisoblanadi. Ko'rgazma — bolaning diqqatini jamlashga, fikrni faollashtirishga va qiziqishini saqlashga yordam beradi.",
                "Amaliy metodlar — bolaning faol qatnashishini talab qiluvchi metodlar. Mashqlar (ovoz, talaffuz, lug'at, gap qurish mashqlari), modellashtirish (predmet sxemalari), faoliyat tashkil etish (rasm chizish, plastilindan yasash, qog'ozdan kesish bilan birga gapirish) — bularning hammasi bolaning nutqini faol holatda rivojlantiradi. \"Eshitganini eslab qoladi, qilganini bilib oladi\" degan tamoyil bu yerda to'la o'rinli.",
            ],
        ),
        (
            "Asosiy ta'lim vositalari: o'yinchoq, surat, kitob va boshqalar",
            [
                "O'yinchoq — kichik yoshdagi bola hayotidagi eng yaqin va eng sevimli predmetdir. Pedagogik nuqtai nazardan o'yinchoq nafaqat o'yin uchun vosita, balki nutqni rivojlantirish uchun kuchli omilidir. To'g'ri tanlangan, sifatli va xilma-xil o'yinchoqlar bola lug'atini boyitadi, uning tasavvurini rivojlantiradi, hissiy va aqliy taraqqiyotiga zamin yaratadi. O'yinchoqlar siyosiy va etik talablarga ham javob berishi shart.",
                "Bog'cha guruhlarida turli toifadagi o'yinchoqlar bo'lishi kerak: 1) syujetli o'yinchoqlar (qo'g'irchoqlar, hayvonchalar, transport vositalari, mebellar); 2) didaktik o'yinchoqlar (matryoshka, piramida, mozaika, kublar, lotto); 3) qurilish o'yinchoqlari (turli xil konstruktorlar); 4) musiqiy o'yinchoqlar (baraban, dutorcha, qo'shiq qutilar); 5) sport o'yinchoqlari (to'plar, halqalar, simirilar). Har bir o'yinchoq turi o'z funksional yukini bajaradi.",
                "Suratlar va surat-jadvallar — kichik yosh bolalari nutqini o'stirishda o'rni beqiyos. Bola hali yozma matnni tushunmaydi, lekin suratga qarab uning mazmunini idrok eta oladi. Tarbiyachi bolalarga predmet suratlarini (alohida narsalar tasvirlangan), syujet suratlarini (kichik voqea tasvirlangan) va seriya suratlarini (voqealar tartibida tasvirlangan) ko'rsatadi va ular bo'yicha gap-nutq tashkil etadi.",
                "Surat bilan ishlash bosqichlari quyidagicha: 1) surat ko'rib chiqiladi va undagi narsalar nomlanadi; 2) sifat va xususiyatlari aniqlanadi; 3) narsalar va personajlar o'rtasidagi munosabatlar aniqlanadi; 4) syujet bo'yicha sodda hikoya tuziladi; 5) bola savollarga javob beradi yoki sodda hikoya qiladi. Kichik guruhda 4-5 bosqichlar to'liq amalga oshmaydi, ular keyingi guruhlarda chuqurlashadi.",
                "Bolalar adabiyoti kitoblari — alohida e'tiborga loyiq vosita. Yorqin va sifatli illyustratsiyalari bo'lgan, tushunarli va qiziqarli matni bo'lgan kitoblar bola hayotining ajralmas qismiga aylanishi kerak. Tarbiyachi har kuni bolalarga kitobdan o'qib beradi, illustratsiyalarni ko'rsatadi, mazmunini muhokama qiladi. Kitob bola uchun ulkan bilim manbai, tasavvur ozig'i va estetik did manbasi bo'lib qoladi.",
                "Tabiiy materiallar va real predmetlar — gul, barg, mevalar, sabzavotlar, tabiiy materiallar (qum, suv, tosh, qobiq) — bolaning nutqini boyitishning eng samarali vositalaridir. Bola real predmetni ko'rib, ushlab, hidini his qilib, uning haqida nutq qila boshlaydi. \"Olma — qattiq, dumaloq, qizil, shirin, mazali\" — bunday tasvirlash bola lug'atini va his-tuyg'usini birga rivojlantiradi.",
                "Hozirgi davrda multimedia vositalari — multfilmlar, ta'limiy videolar, interaktiv dasturlar — ham nutq o'stirishda foydalaniladi. Lekin bu vositalar bilan ehtiyotkorlik bilan munosabatda bo'lish kerak. Ekran oldida o'tkaziladigan vaqt cheklangan bo'lishi (kichik guruhda kuniga 15-20 daqiqadan oshmasligi), tarbiyachi bilan birgalikda ko'rilishi va keyin albatta muhokama o'tkazilishi shart. Multimedia an'anaviy vositalarni almashtirmaydi, balki ularni to'ldiradi.",
            ],
        ),
        (
            "Mashg'ulotlarni tashkil etish va kundalik tartib elementlari",
            [
                "Kichik guruhda nutqni o'stirish mashg'ulotlari muntazam, izchil va ilmiy tashkil etilishi shart. Davlat dasturi talablariga ko'ra, kichik guruhda haftada 2 marta nutq o'stirishga oid mashg'ulot o'tkaziladi, ularning davomiyligi 15 daqiqani tashkil etadi. Bu vaqt — bola diqqatining bir mavzuga jamlanadigan maksimal vaqtidir. Mashg'ulot uzoq bo'lsa, bola charchaydi va material o'zlashtirilmaydi.",
                "Mashg'ulot tuzilishi quyidagicha bo'lishi mumkin: 1) tashkiliy qism (1 daqiqa) — bolalarni ish kayfiyatiga sozlash; 2) asosiy qism (10-12 daqiqa) — yangi material yoki o'zlashtirgan mavzuning takrorlanishi; 3) yakuniy qism (2-3 daqiqa) — natijalarni umumlashtirish, baholash. Har bir bosqich aniq mazmunga ega va bir-biriga chambarchas bog'liq bo'ladi.",
                "Mashg'ulotni qiziqarli va samarali qilish uchun tarbiyachi turli xil usullarni qo'llaydi: o'yin elementlari, kutilmagan vaziyatlar, qo'g'irchoq personajlari (Petrushka, Buratino), musiqa fonidan foydalanish, harakat va nutqni birlashtirish. Bolalar uchun monoton, bir xil mashg'ulotlar zerikarli va samarasizdir. Ular uchun har bir kun yangi tajriba, yangi qiziqish bo'lishi kerak.",
                "Kundalik tartibdagi rejim daqiqalari ham nutq o'stirish uchun qulay imkoniyatlardir. Ertalabki qabul qilish vaqtida tarbiyachi har bir bola bilan samimiy salomlashadi va qisqa suhbat o'tkazadi: \"Bugun qanday kayfiyat bilan keldingiz?\", \"Yo'lda nimalarni ko'rdingiz?\". Ovqat vaqtida — taom haqida, mahsulot va ularning xususiyatlari haqida suhbat. Sayr vaqtida — havo, fasl, atrof-muhit haqida.",
                "Sayr — kichik guruh bolalari nutqini o'stirishda eng samarali rejim elementlaridan biri. Bog'cha hovlisida, mahalla yo'lakchasida, parkda o'tkaziladigan sayrlar bola uchun yangi taassurot va so'z manbai bo'ladi. Tarbiyachi sayrni rejalashtirib o'tkazadi: oldindan kuzatish maqsadi va savollarni belgilab oladi. \"Bugun barglarni kuzatamiz: ular qanday rangda?\", \"Shamol qanday tovushlar chiqaradi?\" kabi savollar bola diqqatini yo'naltiradi.",
                "Mehnat faoliyatida ham nutqni o'stirish uchun katta imkoniyatlar mavjud. Stol-stulni joyiga qo'yish, o'yinchoqlarni terib qo'yish, gulga suv quyish, sodda topshiriqlarni bajarish — bularning hammasi bola lug'atini va grammatik shakllarni boyitadi. \"Men gulga suv quyaman\", \"Men dasturxonni yig'ishtirdim\" kabi gaplar bolaning faoliyati natijasida tabiiy ravishda paydo bo'ladi.",
                "Bayram va o'yin-kulgi tadbirlari — bola hayotining yorqin lavhalari va nutq sezgirligini kuchaytiruvchi vaziyatlardir. Yangi yil, Navro'z, Mustaqillik kuni, ona-yer kuni kabi bayramlar uchun maxsus matritsalar tayyorlanadi: she'rlar yodlanadi, qo'shiqlar o'rganiladi, kichik sahna ko'rinishlari namoyish etiladi. Bayram bola xotirasida uzoq saqlanadi va u yodlagan she'r-qo'shig'i — uning lug'atining mustahkam qismiga aylanadi.",
            ],
        ),
        (
            "Oilada va MTTda kichik yosh bolasi bilan hamkorlikda ishlash",
            [
                "Oila — bola tarbiyasining birinchi va eng muhim instituti hisoblanadi. Bola nutqining shakllanishi avval oilada, ona qo'lida boshlanadi. Bog'cha oila bilan birgalikda ishlamasa, hech qanday natija to'liq bo'lmaydi. Tarbiyachi va ota-onalar o'rtasida ishonchli, samarali hamkorlik o'rnatish — pedagogning eng muhim vazifalaridan biridir. Bu hamkorlik ko'p qirrali tashkil etilishi mumkin.",
                "Ota-onalar uchun maslahat va o'qitish ishlari muntazam o'tkazilishi kerak. Ota-onalar yig'ilishlarida, individual suhbatlarda, taklif qilingan ekspertlarning ma'ruzalarida bolaning nutqini uyda qanday o'stirish bo'yicha tavsiyalar beriladi. Tarbiyachi ota-onalarga: bolaga ko'p o'qib bering, u bilan suhbat qiling, u so'rayotgan savollarga sabr bilan javob bering, uni eshitishga vaqt toping, telekanal va planshetdan kamroq foydalaning kabi maslahatlar beradi.",
                "Bog'cha bilan oilani bog'lovchi turli shakllar mavjud: ota-onalar uchun ko'rgazmali stendlar (\"Bola nutqini qanday rivojlantirish kerak?\", \"Maslahat kuni\"), ota-onalar uchun seminar-trening, oilani tashrif buyurish, bog'cha nashriyoti, internet sahifa va ijtimoiy tarmoq guruhlari. Hozirgi davrda elektron muloqot vositalari katta ahamiyat kasb etmoqda — Telegram va WhatsApp guruhlarda tarbiyachi ota-onalar bilan kundalik aloqada bo'lishi mumkin.",
                "Ota-onalarga uy sharoitida olib boriladigan ishlar bo'yicha aniq tavsiyalar berish kerak. Masalan: ovqat tayyorlash jarayonida bolaga mahsulotlarni nomlash, ularning xususiyatlarini aytish; do'kondan qaytishda yo'l-yo'lakay ko'rilgan narsalarni muhokama qilish; uxlash oldidan albatta ertak yoki she'r o'qib berish; bola so'ragan savollarga jiddiy va to'liq javob berish. Bunday oddiy, lekin doimiy ishlar katta natija beradi.",
                "Tarbiyachi har bir bolaning oilaviy sharoitidan, ota-onalarining bilim darajasidan, pedagogik madaniyatidan xabardor bo'lishi shart. Ba'zi oilalar farzandi nutqiga yetarli e'tibor bermaydi, ba'zilari aksincha, juda talabchan va asabiy munosabatda bo'ladi. Har ikkala holat ham bola uchun zararli. Tarbiyachi har bir oilaga individual yondashib, mos maslahatlar berishi va bolaning manfaati doirasida ish olib borishi kerak.",
                "Maxsus pedagogik talab va e'tibor talab qiladigan bolalar — nutqida sezilarli kamchiligi bo'lganlar, ikki tilli muhitda o'sayotganlar, oilaviy muammolari bo'lganlar, sog'ligi cheklangan bolalar. Bunday holatlarda tarbiyachi logoped, psixolog, defektolog mutaxassislari bilan hamkorlikda ish olib boradi. Vaqtida aniqlangan va to'g'ri yo'naltirilgan ish bola taqdirini sezilarli darajada yaxshilashi mumkin. Vaqt o'tkazib yuborilsa, kamchiliklarni bartaraf etish ancha qiyin bo'ladi.",
                "Hamkorlikning eng muhim sharti — bog'cha va oila o'rtasida ishonch va o'zaro hurmatdir. Tarbiyachi har qanday bolani — uning xulqi yoki nutqi qanday bo'lishidan qat'i nazar — sevishi, uning oilasini hurmat qilishi va ularga yordam berishga intilishi kerak. \"Hamma bolalar — bizning bolalarimiz\" tamoyili pedagogik faoliyatning oltin qoidasi bo'lishi shart. Faqat shu yo'l bilan bola erkin, sog'lom va yetuk shaxs sifatida shakllanadi.",
            ],
        ),
    ],
    "refs": COMMON_REFS,
}
