# -*- coding: utf-8 -*-
from ._refs import COMMON_REFS

topic = {
    "num": 9,
    "title": "Maktabgacha yoshdagi bolalar bilan lug'at ishini olib borishning nazariy asoslari",
    "reja": [
        "Lug'at va lug'at ishi tushunchasi, uning ahamiyati.",
        "Bola lug'atining shakllanishi va rivojlanish qonuniyatlari.",
        "Lug'at ishining vazifalari va yo'nalishlari.",
        "Lug'at ishining tilshunoslik va psixologik asoslari.",
        "Lug'at ishini olib borishning tamoyillari va metodlari.",
    ],
    "sections": [
        (
            "Lug'at va lug'at ishi tushunchasi, uning ahamiyati",
            [
                "Lug'at (leksika) — tilning so'z boyligi, undagi barcha so'zlar majmuidir. Inson lug'ati ikki turga bo'linadi: faol lug'at (inson o'zi nutqida qo'llaydigan so'zlar) va passiv lug'at (inson tushunadigan, lekin o'zi qo'llamaydigan so'zlar). Passiv lug'at odatda faol lug'atdan ancha katta bo'ladi. Lug'at ishining maqsadi — passiv lug'atni boyitish va uni faol lug'atga aylantirishdir.",
                "Lug'at ishi — bog'cha bolasining so'z boyligini muntazam ravishda boyitish, mustahkamlash, faollashtirish va aniqlashtirishga qaratilgan pedagogik faoliyatdir. Bu — nutqni o'stirish metodikasining muhim va markaziy yo'nalishlaridan biridir. Lug'at — nutqning \"qurilish materiali\" hisoblanadi: lug'atsiz na gap qurish, na fikr bayon qilish mumkin. Shu sababli lug'at ishi barcha boshqa ishlarning poydevoridir.",
                "Lug'at ishining ahamiyati bir necha jihatdan namoyon bo'ladi. Birinchidan, lug'at — nutqning asosi: boy lug'atga ega bola o'z fikrini aniq, to'liq va ifodali bayon qila oladi. Ikkinchidan, lug'at — tafakkur quroli: har bir so'z muayyan tushunchani ifodalaydi, demak lug'atni boyitish tushunchalar tizimini boyitadi. Uchinchidan, lug'at — bilim manbai: bola yangi so'zlar orqali yangi bilimlar oladi.",
                "Lug'at va tafakkur o'rtasidagi aloqa juda chuqurdir. So'z — tushunchaning moddiy qobig'i, tushuncha esa — fikrlash birligi. Bola yangi so'zni o'zlashtirar ekan, u bilan birga yangi tushunchani, yangi bilimni ham egallaydi. \"Daraxt\" so'zini bilgan bola daraxt tushunchasiga ega bo'ladi; \"barg\", \"shox\", \"ildiz\", \"tana\" so'zlarini bilgan bola daraxt tuzilishi haqida tasavvurga ega bo'ladi. Lug'at va bilim birga rivojlanadi.",
                "Lug'atning sifat va miqdor ko'rsatkichlari farqlanadi. Miqdor ko'rsatkichi — bola biladigan so'zlar soni. Bu son yosh bilan ortadi: 1 yoshda 10-15 so'z, 3 yoshda 1000-1200 so'z, 5 yoshda 2500-3000 so'z, 7 yoshda 3500-4000 so'z. Sifat ko'rsatkichi esa — so'zlarni aniq, to'g'ri, o'rinli va xilma-xil qo'llay olish. Ikkala ko'rsatkich ham muhim va ular birga rivojlantiriladi.",
                "Lug'at boyligi bolaning umumiy taraqqiyot darajasini ko'rsatadi. Boy lug'atga ega bola odatda yaxshi rivojlangan, qiziquvchan, bilimli va ijtimoiy faol bo'ladi. Aksincha, lug'ati kambag'al bola fikrini ifoda eta olmaydi, muloqotda qiynaladi, o'qishda orqada qoladi. Shu sababli lug'at ishi — bola umumiy taraqqiyotini ta'minlovchi muhim omildir va tarbiyachi unga jiddiy e'tibor qaratishi shart.",
                "Lug'at ishi maktab ta'limi uchun ham muhim poydevor hisoblanadi. Maktabda bola matn o'qiydi, masalalar yechadi, og'zaki va yozma javob beradi — bularning hammasi boy lug'atni talab qiladi. Lug'ati kambag'al bola maktabda jiddiy qiyinchiliklarga duch keladi. Demak, bog'chada olib boriladigan lug'at ishi — bolaning butun keyingi o'quv hayoti uchun investitsiyadir. Bunga befarq qarab bo'lmaydi.",
            ],
        ),
        (
            "Bola lug'atining shakllanishi va rivojlanish qonuniyatlari",
            [
                "Bola lug'atining shakllanishi tug'ilgan kundan boshlanadi va u muayyan qonuniyatlar asosida amalga oshadi. Birinchi yilda bola so'zlarni tushuna boshlaydi (passiv lug'at), birinchi yil oxiriga kelib esa birinchi so'zlarni ayta boshlaydi (faol lug'at). Bu — \"so'zgача\" davr deb ataladi va bu davrda bolaning gugulashlari, taqlidlari nutq uchun zamin tayyorlaydi.",
                "Bir yoshdan keyin lug'at jadal rivojlanadi. 1 yoshda bola 10-15 so'z biladi, 1,5 yoshda 30-40 so'z, 2 yoshda 300 so'z, 3 yoshda 1000-1200 so'zga yetadi. Bu davr \"lug'at portlashi\" deb ataladi — bola juda tez sur'atda yangi so'zlarni o'zlashtiradi. Har kuni bola bir necha yangi so'zni o'rganadi. Bu — nutq taraqqiyotining eng intensiv davridir.",
                "Lug'atning yosh dinamikasi quyidagicha: 3 yosh — 1000-1200 so'z; 4 yosh — 1500-2000 so'z; 5 yosh — 2500-3000 so'z; 6 yosh — 3000-3500 so'z; 7 yosh — 3500-4000 so'z. Bu raqamlar o'rtacha ko'rsatkichlar bo'lib, har bir bolada individual farqlar bo'lishi mumkin. Lug'at boyligi bola tarbiyalanayotgan til muhiti boyligiga bevosita bog'liqdir.",
                "Lug'at shakllanishining muhim qonuniyati — so'z ma'nosining asta-sekin chuqurlashishi. Boshida bola so'zni juda tor yoki juda keng ma'noda tushunadi. Masalan, \"mushuk\" so'zini barcha tukli hayvonlarga nisbatan qo'llashi (kengaytirilgan ma'no) yoki faqat o'z mushugiga nisbatan qo'llashi (toraytirilgan ma'no) mumkin. Asta-sekin so'z ma'nosi aniqlashadi va to'g'ri chegaralarga ega bo'ladi.",
                "Lug'at tarkibi ham yosh bilan o'zgaradi. Boshida bolaning lug'atida otlar (narsalar nomi) va fe'llar (harakatlar) ustun bo'ladi. Keyin sifatlar (xususiyatlar), ravishlar, sonlar, olmoshlar va boshqa so'z turkumlari qo'shiladi. Mavhum tushunchalarni ifodalovchi so'zlar (sevgi, do'stlik, halollik) eng kech o'zlashtiriladi, chunki ular bolaning ko'rgazmali-obrazli fikrlashiga to'g'ridan-to'g'ri mos kelmaydi.",
                "Lug'atning rivojlanishi bola faoliyati bilan chambarchas bog'liq. Bola o'yin o'ynar ekan, o'yinga oid so'zlarni; ovqatlanar ekan, oziq-ovqatga oid so'zlarni; tabiatni kuzatar ekan, tabiatga oid so'zlarni o'zlashtiradi. Demak, bolaning faoliyati qancha boy va xilma-xil bo'lsa, uning lug'ati ham shuncha boy bo'ladi. Tarbiyachi bola faoliyatini boyitib, shu orqali lug'atni ham boyitadi.",
                "Lug'at shakllanishida taqlid muhim mexanizm hisoblanadi. Bola atrofdagi kattalar nutqini eshitib, so'zlarni o'zlashtiradi va ularni o'z nutqida qo'llaydi. Shu sababli atrofdagilar nutqining sifati — eng muhim omil. Boy, to'g'ri, ifodali nutqli oilada va bog'chada o'sgan bola boy lug'atga ega bo'ladi. Kambag'al, qo'pol nutqli muhitda esa bola lug'ati ham kambag'al bo'ladi. Bu — pedagogning eslab qolishi shart bo'lgan haqiqatdir.",
            ],
        ),
        (
            "Lug'at ishining vazifalari va yo'nalishlari",
            [
                "Lug'at ishining to'rt asosiy vazifasi bor: 1) lug'atni boyitish — yangi so'zlar bilan tanishtirish; 2) lug'atni mustahkamlash va aniqlashtirish — ma'lum so'zlarning ma'nosini chuqurlashtirish; 3) lug'atni faollashtirish — passiv lug'atni faol lug'atga aylantirish; 4) nutqdan g'ayriadabiy so'zlarni chiqarish — sheva, qo'pol va noto'g'ri so'zlarni adabiy variantlar bilan almashtirish. Bu vazifalar bir-biri bilan chambarchas bog'liq.",
                "Lug'atni boyitish — eng asosiy vazifa. Bola har kuni yangi so'zlar bilan tanishtiriladi. Yangi so'zlar bola hayotining barcha sohalariga oid bo'lishi kerak: narsalar, harakatlar, xususiyatlar, munosabatlar. Boyitish bola yoshiga va imkoniyatiga mos ravishda, izchil va rejali olib boriladi. Har bir yangi so'z bola uchun tushunarli, hayotiy va kerakli bo'lishi shart.",
                "Lug'atni mustahkamlash va aniqlashtirish — bola allaqachon biladigan so'zlarning ma'nosini chuqurlashtirish, aniqlashtirish va kengaytirish. Bola ko'pincha so'zni taxminan, noaniq biladi. Tarbiyachining vazifasi — so'z ma'nosini aniq qilish, uning chegaralarini belgilash, sinonim va antonimlarini ko'rsatish, ko'p ma'noli so'zlarning turli ma'nolarini ochib berish. Bu — lug'atning sifat tomonini boyitadi.",
                "Lug'atni faollashtirish — passiv lug'atni faol lug'atga aylantirish. Bola ko'p so'zlarni tushunadi, lekin ularni o'z nutqida qo'llamaydi. Tarbiyachining vazifasi — shunday vaziyatlar yaratish-ki, bola passiv lug'atidagi so'zlarni faol qo'llay boshlasin. Buning uchun savol-javob, suhbat, didaktik o'yinlar, hikoya tuzish kabi usullardan foydalaniladi. Faollashtirilgan so'z — bolaning haqiqiy boyligi.",
                "Nutqdan noadabiy so'zlarni chiqarish — bola nutqidagi sheva so'zlari, qo'pol iboralar, noto'g'ri so'zlarni adabiy til variantlari bilan almashtirish. Bola oilada yoki ko'chada noto'g'ri so'zlarni o'rganishi mumkin. Tarbiyachi muloyimlik bilan, bolani uyaltirmasdan, to'g'ri adabiy variantni taqdim etadi va uni mustahkamlaydi. Bu — nutq madaniyatini tarbiyalashning muhim qismidir.",
                "Lug'at ishining yo'nalishlari mavzular bo'yicha tashkil etiladi: 1) tabiat (fasllar, o'simliklar, hayvonlar, qushlar, ob-havo); 2) ijtimoiy hayot (oila, bog'cha, kasblar, transport, do'kon); 3) predmet olami (o'yinchoqlar, idishlar, mebellar, kiyimlar, oziq-ovqat); 4) madaniyat (bayramlar, an'analar, milliy qadriyatlar); 5) inson (tana qismlari, his-tuyg'ular, xulq-atvor). Har bir mavzu boy lug'at materiali beradi.",
                "Lug'at ishini olib borishda har bir yosh guruhining xususiyatlari hisobga olinadi. Kichik guruhda — asosan narsalar nomi va sodda harakatlar; o'rta guruhda — xususiyatlar, sinonim va antonimlar; katta guruhda — umumlashtiruvchi tushunchalar, ko'p ma'noli so'zlar, maqollar. Lug'at ishi izchil ravishda murakkablashib va chuqurlashib boradi. Bu izchillik — pedagogik muvaffaqiyatning kalitidir.",
            ],
        ),
        (
            "Lug'at ishining tilshunoslik va psixologik asoslari",
            [
                "Lug'at ishi chuqur tilshunoslik (lingvistik) asoslarga tayanadi. Leksikologiya fani — tilning lug'at tarkibini o'rganuvchi soha — lug'at ishi uchun nazariy asos beradi. Tarbiyachi so'z, uning ma'nosi, ma'no turlari, so'zlar o'rtasidagi munosabatlar haqida bilimga ega bo'lishi kerak. Bu bilimlarsiz lug'at ishini ilmiy va samarali olib borib bo'lmaydi.",
                "So'z ma'nosi (semantika) — lug'at ishining markaziy tushunchasi. So'z ikki tomonga ega: tovush qobig'i (qanday talaffuz qilinadi) va ma'no (nimani bildiradi). So'zning lug'aviy ma'nosi (muayyan narsa yoki tushunchani bildirish) va grammatik ma'nosi (so'z turkumi, shakl) farqlanadi. Tarbiyachi bolaga so'zning aynan lug'aviy ma'nosini, ya'ni u nimani bildirishini o'rgatadi.",
                "Sinonimiya, antonimiya, omonimiya, ko'p ma'nolilik — so'zlar o'rtasidagi muhim munosabatlar. Sinonimlar — ma'nosi yaqin so'zlar (\"katta\", \"ulkan\"); antonimlar — qarama-qarshi ma'noli so'zlar (\"katta\", \"kichik\"); omonimlar — bir xil aytiladigan, lekin har xil ma'noli so'zlar (\"yer\" — sayyora va \"yer\" — joy); ko'p ma'noli so'zlar — bir so'z bir necha ma'noga ega (\"oltin\" — metall va qimmatli). Bularning hammasi lug'at ishida hisobga olinadi.",
                "Frazeologiya — turg'un so'z birikmalarini (maqol, matal, idioma) o'rganuvchi soha. \"Ko'ngli ochiq\", \"qo'li gul\", \"ipidan ignasigacha\" kabi turg'un iboralar bola nutqini jonli, tasvirli va boy qiladi. Tarbiyachi mos maqol va iboralarni bolalar bilan o'rganadi va ularning ma'nosini tushuntiradi. Bu — lug'atni nafaqat boyitadi, balki bolaning milliy madaniyatini ham shakllantiradi.",
                "Lug'at ishining psixologik asoslari — bola so'zni qanday o'zlashtirishi haqidagi bilimlardir. Psixolog L.S.Vigotskiyning so'z ma'nosining rivojlanishi haqidagi nazariyasi muhim ahamiyatga ega. Vigotskiyning ta'kidlashicha, so'z ma'nosi bola yoshi bilan rivojlanadi va o'zgaradi: boshida so'z bola uchun emotsional-amaliy ma'noga ega, keyin esa u tushuncha darajasiga ko'tariladi. Bu jarayonni tarbiyachi bilishi va hisobga olishi shart.",
                "So'zni o'zlashtirish jarayoni bir necha bosqichdan iborat: 1) so'zni eshitish va idrok etish; 2) so'zning tovush qobig'ini eslab qolish; 3) so'z ma'nosini tushunish; 4) so'zni passiv lug'atga kiritish; 5) so'zni faol nutqda qo'llash. Har bir bosqich vaqt va takrorlashni talab qiladi. Yangi so'z bir marta eshitilgani bilan o'zlashtirilmaydi — u 5-6 marta turli vaziyatlarda takrorlanishi kerak.",
                "Diqqat, xotira va tafakkur — lug'atni o'zlashtirishda ishtirok etuvchi psixik jarayonlar. Bola yangi so'zga diqqatini qaratishi, uni xotirasida saqlashi va ma'nosini tushunishi (tafakkur) kerak. Shu sababli lug'at ishi shu psixik jarayonlarni hisobga olib tashkil etiladi: bola diqqati jamlangan bo'lishi, material qiziqarli va ko'rgazmali bo'lishi, so'z muayyan tushuncha bilan bog'lanishi kerak. Psixologiyani bilmasdan turib, lug'at ishini samarali olib bo'lmaydi.",
            ],
        ),
        (
            "Lug'at ishini olib borishning tamoyillari va metodlari",
            [
                "Lug'at ishi muayyan tamoyillar asosida olib boriladi. Birinchi tamoyil — lug'at ishini hissiy idrok bilan bog'lash. Bola yangi so'zni faqat eshitib emas, balki narsani ko'rib, ushlab, paypaslab, hidini sezib o'zlashtirishi kerak. Bu — \"so'z va narsa birligi\" tamoyili. Mavhum, ko'rinmaydigan narsa haqidagi so'z bola uchun bo'sh tovush bo'lib qoladi.",
                "Ikkinchi tamoyil — lug'at ishini bola faoliyati bilan bog'lash. So'z bolaning real faoliyatida — o'yin, mehnat, kuzatish, muloqotda qo'llanilishi kerak. Faoliyatda qo'llanilgan so'z mustahkam o'zlashtiriladi. Uchinchi tamoyil — izchillik: lug'at ishi oddiydan murakkabga, tanishdan notanishga, yaqindan uzoqqa olib boriladi. To'rtinchi tamoyil — takrorlash: yangi so'z bir necha marta turli vaziyatlarda takrorlanishi shart.",
                "Lug'at ishining metodlari ikki guruhga bo'linadi: bevosita tanishtirish metodlari va bilvosita tanishtirish metodlari. Bevosita metodlar — bola narsa bilan to'g'ridan-to'g'ri tanishadi: predmetlarni kuzatish, ekskursiyalar, real predmetlar bilan ishlash, tajribalar. Bu metodlar eng samarali, chunki bola so'zni real narsa bilan bog'laydi.",
                "Bilvosita tanishtirish metodlari — bola narsa bilan vositalar orqali tanishadi: suratlar bilan ishlash, badiiy adabiyot o'qish, tarbiyachining hikoyasi, suhbat. Bu metodlar bola bevosita ko'ra olmaydigan narsalar (uzoq mamlakatlar, o'tmish, yovvoyi hayvonlar) bilan tanishtirishda muhimdir. Bilvosita metodlar bevosita metodlarni to'ldiradi.",
                "Didaktik o'yinlar — lug'at ishining eng samarali va eng sevimli metodlaridan biri. \"Sehrli qopcha\", \"Magazin\", \"Aksini ayt\", \"Nima ortiqcha?\", \"Kim ko'p so'z aytadi?\", \"Tasvirlash bo'yicha top\", \"Lotto\" kabi o'yinlar bola lug'atini boyitadi, mustahkamlaydi va faollashtiradi. O'yinda bola zerikmaydi, charchaydigan emas, balki qiziqish va zavq bilan o'rganadi. Bu — eng tabiiy o'rganish yo'lidir.",
                "Lug'at mashqlari — maxsus tashkil qilingan, lug'atni rivojlantirishga yo'naltirilgan topshiriqlar. Mashqlar turlari: so'zni tanlash (\"Qaysi so'z mos?\"), so'zni tasniflash (\"Mevalarni ajrat\"), sinonim va antonim topish, umumlashtiruvchi so'z topish (\"Olma, nok, uzum — bular nima?\"), ortiqcha so'zni topish. Bu mashqlar bola lug'atini sistemali ravishda rivojlantiradi va mustahkamlaydi.",
                "Lug'at ishining samaradorligi bir qator shartlarga bog'liq: tarbiyachining nutqi boy va to'g'ri bo'lishi; ko'rgazmali vositalarning yetarli va sifatli bo'lishi; ishning izchil va rejali olib borilishi; har bir bola imkoniyatining hisobga olinishi; oila bilan hamkorlik. Tarbiyachi ota-onalarga bola lug'atini uyda qanday boyitish bo'yicha tavsiyalar beradi: ko'p suhbatlashish, kitob o'qish, savollarga javob berish, atrofdagi narsalarni nomlash. Bog'cha va oila birgalikda ishlaganda bola lug'ati boy va mukammal rivojlanadi.",
            ],
        ),
    ],
    "refs": COMMON_REFS,
}
