# -*- coding: utf-8 -*-
from ._refs import COMMON_REFS

topic = {
    "num": 12,
    "title": "Maktabgacha ta'lim tashkilotlarida o'yinlar va ularning mazmuni",
    "reja": [
        "O'yin tushunchasi va uning bola hayotidagi o'rni.",
        "O'yinlarning tasnifi va asosiy turlari.",
        "Ijodiy o'yinlar: syujetli-rolli, qurilish va dramalashtirish o'yinlari.",
        "Qoidali o'yinlar: didaktik va harakatli o'yinlar.",
        "O'yinlarni tashkil etish va boshqarishda tarbiyachining roli.",
    ],
    "sections": [
        (
            "O'yin tushunchasi va uning bola hayotidagi o'rni",
            [
                "O'yin — bola hayotining eng asosiy va eng muhim faoliyat turidir. Psixologiya va pedagogika fanlarida o'yin bog'cha yoshidagi bolaning \"yetakchi faoliyati\" deb e'tirof etiladi. Bu shuni anglatadiki, aynan o'yin orqali bola taraqqiyotidagi eng muhim o'zgarishlar amalga oshadi: u olamni biladi, ko'nikmalarni egallaydi, shaxs sifatida shakllanadi. O'yinsiz bola taraqqiyotini tasavvur qilib bo'lmaydi.",
                "O'yin — bolaning hayotni o'zlashtirish usulidir. O'yinda bola kattalar hayotini taqlid qiladi, ijtimoiy munosabatlarni o'rganadi, turli rollarni sinab ko'radi. \"Ona-bola\" o'yinida u oilaviy munosabatlarni, \"Shifokor\" o'yinida tibbiyot sohasini, \"Magazin\" o'yinida savdo munosabatlarini o'rganadi. O'yin orqali bola katta dunyoga kichik qadamlar bilan kiradi va unga tayyorlanadi.",
                "Mashhur psixolog L.S.Vigotskiy o'yinni \"taraqqiyot manbai\" deb atagan. Uning fikricha, o'yinda bola o'zining real imkoniyatlaridan yuqori darajada harakat qiladi — \"o'yinda bola o'zidan bir bosh baland turadi\". O'yinda bola yangi ko'nikmalarni sinab ko'radi, ular hali uning kundalik hayotida mustahkamlanmagan bo'lsa ham. Shu sababli o'yin — \"yaqin taraqqiyot zonasi\"ni yaratuvchi vositadir.",
                "Psixolog D.B.Elkonin o'yin nazariyasini chuqur ishlab chiqdi. Uning fikricha, o'yinning markazida ijtimoiy munosabatlar va inson faoliyati turadi. Bola o'yinda buyumlar bilan emas, balki ular orqasidagi inson munosabatlari bilan ishlaydi. Bu — o'yinning ijtimoiy mohiyatini ko'rsatadi. Elkonin o'yinni \"bolaning ijtimoiy hayotga tayyorgarlik maktabi\" deb baholagan.",
                "O'yin bolaning barcha taraqqiyot tomonlarini ta'minlaydi. Aqliy taraqqiyot — o'yinda bola fikrlaydi, tasavvur qiladi, qaror qabul qiladi. Jismoniy taraqqiyot — harakatli o'yinlarda tana rivojlanadi. Hissiy taraqqiyot — o'yinda bola his-tuyg'ularni boshdan kechiradi va boshqaradi. Ijtimoiy taraqqiyot — o'yinda bola muloqot qiladi va hamkorlik qiladi. Axloqiy taraqqiyot — o'yinda bola qoidalar va normalarni o'rganadi.",
                "O'yin bolaning nutqini rivojlantirishda alohida o'rin tutadi. O'yinda bola doimo gapiradi: rollarni ovoz chiqarib o'ynaydi, hamkorlari bilan kelishadi, voqealarni izohlaydi. Syujetli-rolli o'yinlar dialogik nutqni, qurilish o'yinlari izohlovchi nutqni, didaktik o'yinlar lug'at va grammatikani rivojlantiradi. O'yin — nutqning eng tabiiy va eng samarali maktabidir.",
                "Bog'cha hayotida o'yin markaziy o'rin tutadi. Davlat o'quv dasturi o'yinni ta'lim-tarbiyaning asosiy shakli sifatida belgilaydi. Bog'chada o'yin uchun maxsus vaqt, joy va sharoit ajratiladi. Tarbiyachi o'yinni tashkil etadi, boshqaradi va rivojlantiradi. Hozirgi zamon pedagogikasi \"o'yin orqali ta'lim\" tamoyilini eng samarali yondashuv sifatida tan oladi. Shu sababli tarbiyachi o'yin nazariyasi va metodikasini chuqur bilishi shart.",
            ],
        ),
        (
            "O'yinlarning tasnifi va asosiy turlari",
            [
                "Bog'cha pedagogikasida o'yinlar turli mezonlar bo'yicha tasniflanadi. Eng keng tarqalgan tasnif o'yinlarni ikki katta guruhga ajratadi: 1) ijodiy o'yinlar (bolalar o'zlari yaratadigan o'yinlar); 2) qoidali o'yinlar (tayyor qoidalari bo'lgan o'yinlar). Bu ikki guruh o'z ichida yana bir necha turlarga bo'linadi. Har bir tur o'z xususiyatlari va pedagogik imkoniyatlariga ega.",
                "Ijodiy o'yinlar — bolalar o'zlari o'ylab topadigan, syujetni va rollarni o'zlari belgilaydigan o'yinlar. Bu guruhga kiradi: syujetli-rolli o'yinlar (bola turli ijtimoiy rollarni o'ynaydi); qurilish-konstruktorlik o'yinlari (bola turli materiallardan narsalar quradi); dramalashtirish o'yinlari (bola ertak yoki hikoyani sahnalashtiradi). Ijodiy o'yinlarda bola erkin va mustaqil, u o'z tasavvuri bilan o'ynaydi.",
                "Qoidali o'yinlar — kattalar tomonidan yaratilgan, tayyor qoidalari va mazmuni bo'lgan o'yinlar. Bu guruhga kiradi: didaktik o'yinlar (ta'limiy maqsadga yo'naltirilgan); harakatli o'yinlar (jismoniy faoliyatga yo'naltirilgan). Qoidali o'yinlarda bola tayyor qoidalarga rioya qiladi va muayyan maqsadga erishadi. Bu o'yinlar bolada intizom, qoidaga rioya qilish, maqsadga intilish fazilatlarini shakllantiradi.",
                "Syujetli-rolli o'yin — ijodiy o'yinlarning eng asosiy va eng muhim turi. Bunda bola biror ijtimoiy rolni (ona, shifokor, sotuvchi, haydovchi) o'ynaydi va shu rolga mos harakat qiladi. Bu o'yin bola hayotining markazida turadi va uning ijtimoiylashuvini ta'minlaydi. Syujetli-rolli o'yin bola taraqqiyotining eng kuchli dvigatellaridan biri hisoblanadi.",
                "Qurilish-konstruktorlik o'yinlari — bola turli materiallardan (kublar, lego, qum, qor) narsalar quradigan o'yinlar. Bu o'yinlar bolaning fazoviy tasavvurini, konstruktorlik qobiliyatini, mayda motorikani rivojlantiradi. Bola uy, ko'prik, mashina, qal'a quradi va shu jarayonda fikrlaydi, rejalashtiradi, muammolarni hal qiladi. Qurilish o'yinlari texnik va ijodiy fikrlashni rivojlantiradi.",
                "Dramalashtirish (teatrlashtirilgan) o'yinlar — bola ertak, hikoya yoki she'rni sahnalashtiradigan o'yinlar. Bola personaj rolini o'ynaydi, uning so'zlarini aytadi, harakatlarini takrorlaydi. Bu o'yinlar bola nutqini, ifodaliligini, badiiy didini, o'ziga ishonchini rivojlantiradi. Qo'g'irchoq teatri, soya teatri, stol teatri — dramalashtirish o'yinlarining turli shakllaridir.",
                "O'yinlarning yana boshqa tasniflari ham mavjud. Ishtirokchilar soni bo'yicha: yakka, juft, guruhli, jamoaviy o'yinlar. Harakatlilik darajasi bo'yicha: harakatli, o'rtacha harakatli, sokin o'yinlar. O'tkaziladigan joy bo'yicha: xona o'yinlari, hovli o'yinlari. Milliy mansublik bo'yicha: o'zbek xalq o'yinlari, jahon xalqlari o'yinlari. Bu tasniflar tarbiyachiga o'yinlarni to'g'ri tanlash va tashkil etishda yordam beradi.",
            ],
        ),
        (
            "Ijodiy o'yinlar: syujetli-rolli, qurilish va dramalashtirish o'yinlari",
            [
                "Syujetli-rolli o'yin — bog'cha yoshidagi bolaning eng sevimli va eng muhim o'yin turidir. Bunda bola biror syujet (voqea) doirasida turli rollarni o'ynaydi. Masalan, \"Oila\" o'yinida bolalar ona, ota, bola rollarini; \"Kasalxona\" o'yinida shifokor, hamshira, bemor rollarini; \"Magazin\" o'yinida sotuvchi va xaridor rollarini o'ynaydilar. Bu o'yin bola hayotining markazida turadi.",
                "Syujetli-rolli o'yinning tarkibiy qismlari: 1) syujet (o'yin voqeasi — oila hayoti, kasalxona, magazin); 2) mazmun (o'yinda aks ettiriladigan munosabatlar); 3) rol (bola o'ynaydigan personaj); 4) o'yin harakatlari (rolga mos amallar); 5) o'yin qoidalari (rol bilan bog'liq xulq normalari). Bu qismlar yagona o'yin tizimini tashkil etadi.",
                "Syujetli-rolli o'yin bola taraqqiyotiga g'oyat katta ta'sir ko'rsatadi. U bolaning ijtimoiylashuvini ta'minlaydi: bola turli ijtimoiy rollarni sinab ko'radi va ijtimoiy munosabatlarni o'rganadi. U nutqni rivojlantiradi: bola rollarni ovoz chiqarib o'ynaydi va hamkorlari bilan muloqot qiladi. U tasavvurni rivojlantiradi: bola tayoqni \"ot\", kubni \"telefon\" deb tasavvur qiladi.",
                "Syujetli-rolli o'yin yosh bilan rivojlanadi. Kichik yoshda o'yin sodda, qisqa va asosan predmet harakatlariga tayanadi (bola qo'g'irchoqni ovqatlantiradi, uxlatadi). O'rta yoshda syujet murakkablashadi, rollar paydo bo'ladi. Katta yoshda o'yin uzoq, murakkab, ko'p rolli bo'ladi, bolalar syujetni oldindan rejalashtiradilar va rollarni taqsimlaydilar. Bu rivojlanishni tarbiyachi kuzatadi va qo'llab-quvvatlaydi.",
                "Qurilish-konstruktorlik o'yinlari bolaning yaratuvchilik faoliyatidir. Bola turli materiallardan — yog'och kublar, plastik konstruktor, lego, qum, qor — narsalar quradi: uy, ko'prik, minora, mashina, qal'a. Bu o'yinlar bolaning fazoviy tasavvurini, mantiqiy fikrlashini, mayda motorikasini va sabrini rivojlantiradi. Qurilish jarayonida bola rejalashtirishni, muammolarni hal qilishni o'rganadi.",
                "Qurilish o'yinlari nutqni ham rivojlantiradi. Bola o'z qurilishini izohlaydi, hamkorlari bilan kelishadi, natijani tasvirlaydi: \"Men baland uy qurmoqchiman\", \"Bu yerga ko'prik qo'yamiz\", \"Mening qal'am eng mustahkam\". Tarbiyachi qurilish o'yinida bola nutqini boyitadi: yangi so'zlar (devor, tom, ustun, poydevor), fazoviy munosabatlar (ustida, ostida, yonida, orasida) bilan tanishtiradi.",
                "Dramalashtirish o'yinlari — bola badiiy asarni sahnalashtiradigan ijodiy faoliyatdir. Bolalar tanish ertak yoki hikoyani (\"Sholg'om\", \"Uch ayiq\", \"Qizil shapka\") sahna ko'rinishida ko'rsatadilar. Har bir bola personaj rolini ijro etadi: uning so'zlarini aytadi, harakatlarini takrorlaydi, his-tuyg'ularini ifodalaydi. Bu o'yinlar bola nutqini, ifodaliligini, badiiy didini va o'ziga ishonchini rivojlantiradi. Dramalashtirish o'yinlari bolalar uchun ham qiziqarli, ham foydali bo'lib, ular bog'cha hayotining yorqin lavhalaridan biriga aylanadi.",
            ],
        ),
        (
            "Qoidali o'yinlar: didaktik va harakatli o'yinlar",
            [
                "Qoidali o'yinlar — kattalar tomonidan yaratilgan, tayyor qoidalari, mazmuni va maqsadi bo'lgan o'yinlardir. Ijodiy o'yinlardan farqli o'laroq, bunda bola syujetni o'zi o'ylab topmaydi, balki tayyor qoidalarga rioya qiladi. Qoidali o'yinlar ikki asosiy turga bo'linadi: didaktik o'yinlar (ta'limiy maqsadga yo'naltirilgan) va harakatli o'yinlar (jismoniy faoliyatga yo'naltirilgan).",
                "Didaktik o'yin — muayyan ta'limiy maqsadga yo'naltirilgan, qoidalar asosida tashkil qilingan o'yindir. Uning maqsadi — bolaga bilim berish, ko'nikma shakllantirish, psixik jarayonlarni rivojlantirish. Didaktik o'yinlar lug'atni boyitadi, tafakkurni rivojlantiradi, sezgilarni o'tkirlashtiradi, matematik tushunchalarni shakllantiradi. Ular bog'cha ta'limining eng samarali vositalaridan biridir.",
                "Didaktik o'yinlar mazmuni bo'yicha turlicha bo'ladi: 1) nutqni rivojlantiruvchi o'yinlar (lug'at, grammatika, tovush); 2) matematik o'yinlar (son, shakl, o'lcham); 3) tabiat bilan tanishtiruvchi o'yinlar (o'simlik, hayvon, fasllar); 4) sensor o'yinlar (rang, shakl, o'lchamni idrok etish); 5) mantiqiy o'yinlar (tahlil, taqqoslash, umumlashtirish). Har bir tur o'z ta'limiy vazifasini bajaradi.",
                "Didaktik o'yinlar shakli bo'yicha ham turlicha: predmetli o'yinlar (real predmetlar bilan), ko'rgazmali o'yinlar (surat va kartochkalar bilan), so'zli o'yinlar (faqat so'zga tayanadigan). Bola yoshi oshgan sari predmetli o'yinlardan so'zli o'yinlarga o'tib boriladi. Didaktik o'yinning tuzilishi: didaktik vazifa, o'yin vazifasi, o'yin harakatlari, qoidalar va natija.",
                "Harakatli o'yinlar — bola jismoniy faoliyatiga, harakatiga yo'naltirilgan qoidali o'yinlar. Ularning maqsadi — bolaning jismoniy taraqqiyotini ta'minlash: harakat malakalarini (yugurish, sakrash, uloqtirish) rivojlantirish, jismoniy sifatlarni (kuch, tezlik, chaqqonlik, chidamlilik) shakllantirish, sog'liqni mustahkamlash. Harakatli o'yinlar bog'cha hayotining ajralmas qismidir.",
                "Harakatli o'yinlar turlari: 1) syujetli harakatli o'yinlar (\"Mushuk va sichqonlar\", \"Quyonlar va bo'ri\" — voqea asosida); 2) syujetsiz harakatli o'yinlar (\"Bayroqcha tomon yugur\", \"Kim tez?\" — musobaqa elementi bilan); 3) sport elementli o'yinlar (to'p, halqa bilan). Harakatli o'yinlar nafaqat jismoniy, balki nutqni ham rivojlantiradi: ko'pchilik o'yinlar she'r, qo'shiq, sanama bilan hamroh bo'ladi.",
                "Qoidali o'yinlar bolada muhim fazilatlarni shakllantiradi. Qoidaga rioya qilish — bola o'z istaklarini jilovlashga, tartibga bo'ysunishga o'rganadi. Maqsadga intilish — bola o'yin maqsadiga erishishga harakat qiladi. Adolat va halollik — bola qoidalarni buzmaslikni, halol o'ynashni o'rganadi. Jamoaviylik — bola jamoa manfaatini o'ylashga o'rganadi. Bu fazilatlar kelajakda maktab va hayot uchun zarurdir. Shu sababli tarbiyachi qoidali o'yinlarga jiddiy e'tibor qaratishi va ularni izchil olib borishi shart.",
            ],
        ),
        (
            "O'yinlarni tashkil etish va boshqarishda tarbiyachining roli",
            [
                "O'yinlarni tashkil etish va boshqarish — tarbiyachining eng muhim va eng murakkab vazifalaridan biridir. Tarbiyachi o'yin uchun sharoit yaratadi, o'yinni boshqaradi va rivojlantiradi, lekin bolalarning erkinligini va mustaqilligini bo'g'maydi. Bu — nozik pedagogik san'at bo'lib, u tarbiyachidan chuqur bilim, mahorat va bolaga muhabbatni talab qiladi. O'yinni to'g'ri boshqarish — pedagogik mahoratning eng yuqori ko'rinishidir.",
                "O'yin uchun sharoit yaratish — tarbiyachining birinchi vazifasi. Bunga kiradi: o'yin uchun joy va vaqt ajratish; o'yin materiallari va o'yinchoqlarni tayyorlash; o'yin muhitini tashkil etish (o'yin burchaklari — oila burchagi, kasalxona, magazin, qurilish burchagi). Boy va xilma-xil o'yin muhiti bolalarni o'yinga undaydi va ularning o'yinini boyitadi. Material bazasi — o'yin faoliyatining moddiy asosidir.",
                "Ijodiy o'yinlarni boshqarish alohida nozik yondashuvni talab qiladi. Tarbiyachi bu o'yinlarga to'g'ridan-to'g'ri aralashmaydi, balki bilvosita yo'naltiradi: o'yin uchun yangi taassurotlar beradi (ekskursiya, hikoya, surat), o'yin muhitini boyitadi, kerak bo'lganda o'yinga qo'shiladi va namuna ko'rsatadi. Tarbiyachi bolalarning o'yiniga hurmat bilan qaraydi va uning erkinligini saqlaydi.",
                "Qoidali o'yinlarni (didaktik va harakatli) boshqarishda tarbiyachi faolroq rol o'ynaydi. U o'yinni tushuntiradi, qoidalarni o'rgatadi, namuna ko'rsatadi, o'yinning borishini boshqaradi, natijalarni baholaydi. Bunda ham tarbiyachi bolalarni qo'rqitmaslik, balki rag'batlantirishi, o'yin ruhini — quvonch va zavqni saqlashi kerak. Qoidali o'yin ham, ijodiy o'yin kabi, bola uchun zavqli bo'lishi shart.",
                "Tarbiyachi o'yinda har bir bolaga e'tibor qaratadi. U faol bo'lmagan, uyatchang bolalarni o'yinga jalb qiladi; juda faol, hukmron bolalarni boshqalar bilan hisoblashishga o'rgatadi; nizolarni adolatli hal qiladi; zaif bolalarga yordam beradi. Tarbiyachining maqsadi — har bir bola o'yinda o'z o'rnini topishi, faol qatnashishi va rivojlanishi. Hech bir bola o'yindan chetda qolmasligi kerak.",
                "Tarbiyachi o'yin orqali bolalarni kuzatadi va o'rganadi. O'yinda bolaning xarakteri, qiziqishlari, qobiliyatlari, muammolari yaqqol namoyon bo'ladi. Tarbiyachi bu kuzatuvlardan har bir bolani yaxshiroq tushunish va unga to'g'ri yondashish uchun foydalanadi. O'yin — bolani o'rganishning eng yaxshi \"oynasi\"dir. Diqqatli tarbiyachi o'yin orqali bola haqida ko'p narsani bilib oladi.",
                "Tarbiyachi o'yin faoliyatida oila bilan hamkorlik qiladi. U ota-onalarga o'yinning ahamiyatini tushuntiradi, ularni bola bilan o'ynashga undaydi, uy sharoitida o'tkaziladigan o'yinlarni tavsiya etadi. Ko'pgina ota-onalar o'yinni \"bekorchilik\" deb hisoblaydilar va bolani faqat \"o'qishga\" majburlaydilar — bu noto'g'ri. Tarbiyachi ularga o'yin bola taraqqiyotining eng muhim vositasi ekanligini tushuntirishi kerak. Bog'cha va oila birgalikda bolaga to'liq qadrli o'yin imkoniyatini yaratganda, bola sog'lom, baxtli va har tomonlama rivojlangan shaxs bo'lib voyaga yetadi.",
            ],
        ),
    ],
    "refs": COMMON_REFS,
}
