# -*- coding: utf-8 -*-
from ._refs import COMMON_REFS

topic = {
    "num": 7,
    "title": "Bolalarning ijtimoiy va shaxs sifatida shakllanishida dialogik nutqning ahamiyati",
    "reja": [
        "Dialogik nutq tushunchasi va uning psixologik-pedagogik mohiyati.",
        "Dialogik nutqning bola ijtimoiylashuvidagi roli.",
        "Dialogning bola shaxsiyati shakllanishiga ta'siri.",
        "Bog'chada dialogik nutqni rivojlantirish yo'llari va metodlari.",
        "Dialog ko'nikmalarini diagnostika qilish va tarbiyachining yo'naltiruvchi roli.",
    ],
    "sections": [
        (
            "Dialogik nutq tushunchasi va uning psixologik-pedagogik mohiyati",
            [
                "Dialogik nutq — ikki yoki undan ortiq kishilar o'rtasida amalga oshadigan, savol va javob shaklida tashkil qilingan, navbatma-navbat almashinuvchi nutq shakli. \"Dialog\" so'zi yunoncha \"dia\" (orasida) va \"logos\" (so'z) so'zlaridan tashkil topgan va tom ma'noda \"o'rtaslararo so'z almashish\" ma'nosini bildiradi. Dialog — insoniyat muloqotining eng tabiiy va eng asosiy shakli hisoblanadi va u ijtimoiy hayotning markazida turadi.",
                "Dialogik nutqning psixologik mohiyati shundaki, u har doim emotsional bo'yoq, vaziyatga bog'liq va to'liq kontekstga tayanadi. Suhbatdoshlar bir-birini ko'rib turadi, ovoz ohanglari, mimikalar, imo-ishoralar yordamida qo'shimcha axborot oladi. Shu sababli dialogik nutq qisqa, tig'iz va konkret bo'la oladi. Murakkab grammatik konstruksiyalar va to'liq jumlalar shart emas.",
                "Pedagogik nuqtai nazardan dialogik nutq — bolada ijtimoiy ko'nikmalar shakllanishining poydevoridir. Bola dialog orqali muloqot etiketini, navbatga rioya qilishni, boshqalarni tinglashni, o'z fikrini muhokama qilishni, kelishuv va kelishmovchilikni hal qilishni o'rganadi. Bu ko'nikmalar bolaning kelajakdagi muvaffaqiyatli hayoti uchun zaruriy poydevor bo'lib xizmat qiladi.",
                "Dialogik nutqning bir qator funksional turlari mavjud: 1) muloqot dialogi — kundalik suhbatlar, salomlashish va xayrlashish; 2) bilim olish dialogi — savollar va javoblar orqali bilim olish; 3) muhokama dialogi — fikrlar almashish va munozara; 4) hissiy dialog — his-tuyg'ularni ulashish; 5) tashkiliy dialog — birgalikdagi faoliyatni tashkil etish. Har bir tur o'z xususiyatlariga ega.",
                "Dialogik nutqning rivojlanish bosqichlari bola yoshi bilan bog'liq. Erta yoshda (1-3 yosh) dialog asosan kattalar bilan, qisqa va sodda shaklda bo'ladi. Kichik bog'cha yoshda (3-4 yosh) tengdoshlar bilan dialog boshlanadi. O'rta yoshda (4-5 yosh) dialog mazmunan boyiydi, vaziyatlar kengayadi. Katta yoshda (5-7 yosh) dialog murakkab va izchil shaklga ega bo'ladi.",
                "Dialogik nutqda zaruriy ko'nikmalar quyidagilardan iborat: 1) o'z navbatini kutish (suhbatdoshning so'zini bo'lmaslik); 2) eshitish va tushunish; 3) javob berish va savol berish; 4) suhbat mavzusiga sodiq bo'lish; 5) ohang va emotsional rangni saqlash; 6) etiket qoidalariga rioya qilish. Bularning hammasi maxsus tarbiya natijasida shakllanadi va kun sayin amaliyotda mustahkamlanadi.",
                "Dialogik nutq monologik nutqdan birinchi navbatda shu jihatdan farq qiladi-ki, dialogda fikr ikki yoki ko'proq kishilar tomonidan birgalikda quriladi. Har bir suhbatdoshning hissasi keyingi javobning yo'nalishini belgilaydi. Bu — \"o'zaro rivojlanuvchi\" yoki \"hamkorlikdagi\" nutq shakli. Bog'cha tarbiyachisi shu xususiyatdan foydalanib, bolada nafaqat tilni, balki ijtimoiy intellektni, his-tuyg'ularni boshqarish ko'nikmasini ham rivojlantiradi.",
            ],
        ),
        (
            "Dialogik nutqning bola ijtimoiylashuvidagi roli",
            [
                "Bolaning ijtimoiylashuvi — uning jamiyatda yashashga, uning qoidalari, qadriyatlari, an'analarini o'zlashtirib, faol a'zo bo'lib qatnashishga tayyorgarligini shakllantirish jarayonidir. Bu jarayon bolaning butun bog'cha va maktab davrida amalga oshadi va dialogik nutq uning eng muhim vositalaridan biridir. Til orqali bola jamiyatga kiradi va uning a'zosi bo'ladi.",
                "Dialog orqali bola eng birinchi ijtimoiy ko'nikmalarni egallaydi: salomlashish, xayrlashish, rahmat aytish, kechirim so'rash, ruxsat so'rash, taklif qilish, taklifni qabul qilish yoki rad etish. Bu — etiket qoidalari deb ataladi va u har xil madaniyatlarda turlicha bo'ladi. O'zbek bolasi \"Assalomu alaykum\" deb salomlashadi, \"Yaxshi qoling\" yoki \"Xayr\" deb xayrlashadi, \"Rahmat\" deb minnatdorchilik bildiradi. Bularning hammasi — bola madaniyatining belgilari.",
                "Tengdoshlari bilan munosabatda dialogning roli alohida muhim. Bog'chada bola birinchi marta o'zining tengdoshlari bilan to'qnash keladi va ular bilan o'zaro munosabat o'rnatishi kerak. Dialog — bunday munosabatlarning eng asosiy vositasidir. Bola dialog orqali do'stlik tuzadi, o'yin shartlarini muhokama qiladi, kelishmovchiliklarni hal qiladi, his-tuyg'ularini ulashadi.",
                "Dialog jarayonida bola \"o'rinida turish\" malakasini o'zlashtiradi — boshqa kishining nuqtai nazarini tushunish va hisobga olish. Psixologlar buni \"dekontratsiya\" yoki \"ego­tsentrizmdan chiqish\" deb atashadi. Bola asta-sekin tushunadiki, dunyo faqat unga emas, balki boshqalarga ham tegishli, ularning ham fikrlari, his-tuyg'ulari, istaklari bor. Bu tushuncha — empatiyaning poydevoridir.",
                "Konfliktlarni hal qilish ko'nikmasi dialog yordamida shakllanadi. Bog'chada bolalar o'rtasida kelishmovchiliklar muqarrar — o'yinchoq, joy, e'tibor uchun. Tarbiyachi bunday vaziyatlarda bolalarni dialogga undaydi: \"Bir-biringiz bilan gaplashing, kim aytmoqchi?\", \"O'rtoqning fikrini tinglang\", \"Birgalikda yechim toping\". Bola asta-sekin nizolarni urush bilan emas, suhbat bilan hal qilishga o'rganadi.",
                "Hamkorlikda ish olib borish ko'nikmasi ham dialog asosida shakllanadi. Birgalikdagi syujetli o'yinlar, jamoa loyihalari, badiiy faoliyat — bularning hammasi bolalar o'rtasida muloqotni va kelishuvni talab qiladi. Bola \"Sen — sotuvchi, men — xaridor bo'laman\", \"Avval mening uyimni quraylik, keyin seningni\" kabi kelishuvlarni qura oladi. Bu hamkorlik ko'nikmasi kelajakda jamoaviy mehnatga zamin bo'ladi.",
                "Madaniyatlararo muloqot ko'nikmalari ham bog'cha yoshida shakllana boshlaydi. Hozirgi davrda ko'p oilalarda turli millat va madaniyat vakillari uchrashadi. Bola bog'chada turli millat tengdoshlari bilan birga o'sadi va dialog orqali ularning madaniyatini, tilini, an'analarini o'rganadi. Bu — kelajakda dunyo fuqarosi sifatida shakllanish uchun zaruriy tajriba. Tarbiyachi millatlararo do'stlik va tolerantlikning samarali yo'lboshchisi bo'ladi.",
            ],
        ),
        (
            "Dialogning bola shaxsiyati shakllanishiga ta'siri",
            [
                "Bola shaxsiyati — uning ichki dunyosi, qadriyatlari, qiziqishlari, his-tuyg'ulari, fikrlash uslubi, xulq-atvori va o'ziga ishonchining majmuidir. Shaxsiyat butun hayot davomida shakllanadi, lekin uning poydevori bog'cha va maktab yoshlarida quriladi. Dialogik nutq shaxsiyatning shakllanishida hal qiluvchi rol o'ynaydi, chunki aynan suhbat orqali bola o'zini va olamni anglaydi.",
                "Dialog orqali bola o'z fikrini bayon eta olishni va uni asoslab berishni o'rganadi. Bu — mantiqiy fikrlash va aqliy ishonchning poydevori. Bola \"Men shunday deb o'ylayman, chunki ...\" yoki \"Men bu bilan rozi emasman, sababi ...\" deb gapirishni o'rganganda, u o'zini, o'z fikrini va o'z mavqeini hurmat qilishni o'rganadi. Bu — kelajakda mustaqil va ijodiy shaxs sifatida shakllanish uchun muhim qadam.",
                "Dialog orqali bola his-tuyg'ularini ifodalashni va boshqarishni o'rganadi. \"Men xursandman, chunki ...\", \"Men g'amginman, sababi ...\", \"Men g'azabim chiqayapti, agar ...\" kabi iboralar bola his-tuyg'ularini so'zlar bilan ifodalashga, demak ular ustidan nazoratga ega bo'lishga yordam beradi. His-tuyg'ularni so'z bilan ifodalay olmagan bola ularni xulqi bilan namoyon qiladi — yig'i, urush, qichqirish bilan.",
                "Dialog bolada o'ziga ishonchni shakllantiradi. Tarbiyachi va ota-onalar uning fikrini tinglagani, e'tirof etgani, savollarga sabr bilan javob bergani — bularning hammasi bolaga \"meni sevadilar, men muhimman, mening fikrim qiymatga ega\" degan ishonchni beradi. Bunday bola hayotda muvaffaqiyatga erishadi, qiyinchiliklardan qo'rqmaydi, yangi narsalarni o'rganishga ochiq bo'ladi.",
                "Aksincha, dialogdan mahrum yoki tahqirlovchi dialogga duchor bo'lgan bolalarda bir qator psixologik muammolar paydo bo'lishi mumkin: o'ziga ishonchsizlik, qo'rquv, o'zini chetga olish, ijtimoiy fobiya, depressiv kayfiyat, agressiya. Shu sababli kattalar — ota-onalar va tarbiyachilar — bola bilan dialogdagi munosabatni juda ehtiyotkorlik bilan tashkil qilishlari shart. Har qanday so'z izsiz qolmaydi.",
                "Dialog orqali bolada axloqiy fazilatlar shakllanadi: halollik (ochiqchasiga gapirish va aldash haromligini bilish), mehribonlik (boshqalarning his-tuyg'ularini hisobga olish), kamtarlik (o'zini boshqalardan yuqori qo'ymaslik), sabrlik (boshqani tinglash). Bularning hammasi nazariy ko'rsatmalar bilan emas, balki kundalik dialog amaliyoti orqali shakllanadi. Bola kattalardan ko'rganini takrorlaydi.",
                "Dialog bola ijodkorligini ham rivojlantiradi. Suhbat jarayonida fikrlar bir-biri bilan to'qnashadi, yangi g'oyalar tug'iladi, tasavvur ishlaydi. \"Agar ...?\", \"Nima bo'larkin, ...?\" turidagi savollar bola xayolini ishga soladi va ijodiy fikrlashni rivojlantiradi. \"Agar quyon kattaroq bo'lganda, nima bo'lardi?\", \"Nima bo'lar edi-yu, agar barcha hayvonlar gapira olsa?\" kabi savollar bolada ijodiy salohiyatni shakllantiradi va bu uning butun hayotida foydali bo'ladi.",
            ],
        ),
        (
            "Bog'chada dialogik nutqni rivojlantirish yo'llari va metodlari",
            [
                "Bog'chada dialogik nutqni rivojlantirish maxsus tashkil qilinadigan va kundalik faoliyatga singdirilgan ish hisoblanadi. Maxsus mashg'ulotlar — suhbatlar, didaktik o'yinlar, rolli o'yinlar — alohida vaqt va e'tibor talab qiladi. Kundalik faoliyatda dialog rejim daqiqalari, sayrlar, ovqat vaqti, mehnat va o'yin paytlarida tabiiy ravishda amalga oshiriladi. Har ikkala yo'nalish bir-birini to'ldiradi.",
                "Suhbat metodi — dialogik nutqni rivojlantirishning eng asosiy va eng samarali metodlaridan biridir. Tarbiyachi har kuni bolalar bilan turli mavzularda suhbatlashadi: kunlik voqealar, ob-havo, oilaviy hodisalar, qiziqishlar, kelajak rejalari. Suhbat erkin yoki rejalashtirilgan bo'lishi mumkin. Erkin suhbat tabiiy ravishda paydo bo'ladi, rejalashtirilgan suhbat esa muayyan mavzu va savollar bo'yicha o'tkaziladi.",
                "Suhbat o'tkazishning samarali sirlari: 1) mavzu bola uchun qiziq va tushunarli bo'lishi shart; 2) savollar oddiy va bola yoshiga mos bo'lishi kerak; 3) tarbiyachi sabr bilan tinglashi va to'g'ri ohangda javob qaytarishi kerak; 4) bola fikrini bo'lmaslik, balki uni qo'llab-quvvatlash; 5) hech qanday \"bola gaplaridan kulish\" yoki \"masxara qilish\" bo'lmasligi shart. Suhbatda ehtirom va e'tibor — eng muhim sifatlar.",
                "Didaktik dialogli o'yinlar maxsus tashkil qilingan vaziyatlarda dialogik nutqni o'rgatishga yo'naltirilgan. \"Telefon\" o'yini eng mashhur va samaralidir: bolalar telefon orqali sodda dialoglar quradilar — salomlashish, savol-javob, hikoya aytish, xayrlashish. \"Sayohat\" o'yini, \"Mehmon\" o'yini, \"Qabulda\" o'yini, \"Yo'lda\" o'yini bolaga turli xil ijtimoiy vaziyatlarni boshdan kechirish imkonini beradi.",
                "Rolli o'yinlar dialogik nutqning eng tabiiy va samarali laboratoriyasidir. Bolalar shifokor va bemor, sotuvchi va xaridor, ona va bola, mehmon va mehmondor, o'qituvchi va o'quvchi rollarida bo'lib o'ynashadi. Har bir rolda dialog o'ziga xos lug'at va konstruksiyalar talab qiladi. Tarbiyachi o'yinga o'zi qo'shilib, namuna ko'rsatadi, boshqaradi va kerakli yo'nalishga yo'llaydi.",
                "Badiiy adabiyot bilan ishlash dialogik nutq materiallari bilan boy. Ko'pchilik ertaklar va hikoyalarda dialoglar bor: \"Bo'g'irsoq\" ertagida bo'g'irsoqning hayvonlar bilan dialoglari, \"Sholg'om\" ertagida personajlarning birgalikdagi dialogi, \"Qizil chodir\" ertagida qizcha va bo'rining suhbati. Bunday asarlarni rolma-rol o'qish va sahnalashtirish bolaning dialogik nutqini sezilarli darajada rivojlantiradi.",
                "Sahnalashtirilgan o'yinlar va kichik teatr — dialogik nutqni rivojlantirishning yorqin va qiziqarli shakllaridan biri. Bog'cha bolalari sodda ertak yoki hikoyani sahna ko'rinishida ko'rsatadilar. Har bir bola o'z rolini ijro etadi, dialoglarni yodlaydi va ifodali aytadi. Bunday faoliyat nafaqat nutqni rivojlantiradi, balki bolada o'ziga ishonch, jamoa oldida gapira olish, badiiy did va ijodiy his-tuyg'ularni shakllantiradi.",
            ],
        ),
        (
            "Dialog ko'nikmalarini diagnostika qilish va tarbiyachining yo'naltiruvchi roli",
            [
                "Bog'cha tarbiyachisining muhim vazifalaridan biri — bolalarning dialogik nutq ko'nikmalarini muntazam ravishda baholash, qiyinchiliklarni o'z vaqtida aniqlash va kerakli yordam ko'rsatish. Buning uchun pedagogik diagnostika metodlari qo'llaniladi. Diagnostika — bola taraqqiyotini boshqarish va to'g'ri yo'nalishga yo'llashning asosiy vositasidir. Faqat diagnostikadan keyingina samarali ish rejasi tuzilishi mumkin.",
                "Pedagogik diagnostika metodlari quyidagilardir: 1) kuzatish — bolalarning kundalik faoliyatdagi dialoglarini kuzatish va qayd etish; 2) maxsus suhbat — diagnostik maqsadda tarbiyachi bilan bola o'rtasidagi suhbat; 3) o'yin vaziyatlari — maxsus tashkil qilingan rolli yoki didaktik o'yinda bola xulqini kuzatish; 4) jamoaviy muhokama — bolalar bir-biri bilan suhbatda qanday qatnashishini kuzatish.",
                "Dialogik nutqni baholash mezonlari: 1) suhbatga kirisha olish (savol-javob, mavzuga kirish); 2) suhbat mavzusiga sodiq qola olish; 3) o'z navbatini kutish va boshqalarni tinglash; 4) o'z fikrini aniq va tushunarli bayon qilish; 5) etiket qoidalariga rioya qilish; 6) lug'at va grammatikadan to'g'ri foydalanish; 7) hissiy tomondan adekvat reaksiya qaytarish. Har bir mezon individual ko'rsatkich beradi.",
                "Diagnostika natijalari asosida har bir bola uchun individual ish rejasi tuziladi. Yaxshi rivojlangan dialogik nutqi bo'lgan bolalar uchun — yangi va murakkab vazifalar; o'rtacha rivojlangan bolalar uchun — mustahkamlash va kengaytirish ishlari; rivojlanishi orqada qolgan bolalar uchun — qo'shimcha individual mashg'ulotlar va ota-onalar bilan kelishuv. Hech bir bola e'tibordan chetda qolmasligi shart.",
                "Tarbiyachining yo'naltiruvchi roli ko'p qirrali. U dialogni boshqaradi va yo'naltiradi: savollar bilan bolaga o'z fikrini chuqurlashtirishga yordam beradi (\"Nega shunday deb o'ylaysan?\", \"Yana nima deb aytishing mumkin?\"); mavzuni qo'llab-quvvatlaydi; bolalar o'rtasidagi muloqotni faollashtiradi (\"Sening fikring qanday? Karim nima dedi?\"); jamiyatchi rolini bajaradi va bolalarni adolatli muhokamaga yo'llaydi.",
                "Tarbiyachi shaxsiy namuna sifatida ham eng muhim rolni o'ynaydi. Uning bolalar bilan, hamkasblari bilan, ota-onalar bilan dialogi — bola uchun \"o'rganish darsligi\". Tarbiyachi xushmuomalalik, sabr, e'tibor, mehribonlik bilan suhbatlashsa, bola xuddi shunday qiladi. Aksincha, tarbiyachi qattiq, asabiy, befarq bo'lsa, bola ham shunday bo'lib qoladi. Shaxsiy namuna — eng kuchli pedagogik vositadir.",
                "Ota-onalar bilan hamkorlik dialog ishida alohida ahamiyatga ega. Tarbiyachi ota-onalarga uy sharoitida qanday qilib bola bilan dialog qurish kerakligi bo'yicha tavsiyalar beradi: bolaga vaqt ajrating, uning savollariga javob bering, uni eshitishni biling, uning fikrini hurmat qiling. Telekanal va planshetlar oilaviy dialogni almashtira olmaydi — bularni eslating. Bog'cha va oila birgalikda ish olib borgandagina haqiqiy natija beradi va bola dialog ko'nikmalari bilan jihozlangan, ijtimoiy va shaxs sifatida yetuk inson bo'lib voyaga yetadi.",
            ],
        ),
    ],
    "refs": COMMON_REFS,
}
