# -*- coding: utf-8 -*-
from ._refs import COMMON_REFS

topic = {
    "num": 5,
    "title": "Maktabgacha ta'lim tashkilotlarida katta guruh bolalarining nutqini o'stirish metodlari va vositalari",
    "reja": [
        "Katta guruh bolalarining yoshiga xos nutq xususiyatlari.",
        "Lug'atni chuqurlashtirish va so'z ma'nosini boyitish ishlari.",
        "Grammatik tuzilishni mukammallashtirish va tovush tahlili.",
        "Ravon nutqni mukammallashtirish: hikoya turlari va ijodiy nutq.",
        "Maktabga tayyorgarlik va savod o'rgatishga zamin yaratish.",
    ],
    "sections": [
        (
            "Katta guruh bolalarining yoshiga xos nutq xususiyatlari",
            [
                "Katta guruh bolalari (5-6 yosh) bog'cha yoshining yetuk bosqichida bo'ladilar. Bu yoshda bola allaqachon mukammal so'zlovchi, qiziquvchan va izlanuvchi shaxs sifatida shakllanadi. Uning fikrlashi ko'rgazmali-obrazlidan abstrakt-mantiqiyga o'ta boshlaydi. Tarbiyachi katta guruh bolalari bilan ishlashda ularning yangi imkoniyatlarini hisobga olib, mashg'ulotlarning mazmunini chuqurlashtirishi va vazifalarni murakkablashtirishi kerak.",
                "Bu yoshdagi bolaning lug'at boyligi 2500-3500 so'zni tashkil etadi. Bola endi nafaqat narsa va hodisalarning nomini, balki ularning mohiyatini, sabab va natija aloqalarini, umumlashtiruvchi tushunchalarni biladi. \"Mebellar\", \"transport vositalari\", \"yovvoyi hayvonlar\", \"sabzavotlar\", \"mevalar\" kabi umumiy tushunchalar lug'atining muhim qismini tashkil etadi. Bola turli kategoriyalar bo'yicha narsalarni guruhlay oladi.",
                "Tovushlarni talaffuz qilish bo'yicha katta guruh bolasi to'liq nazoratga ega bo'lishi kerak. Agar bu yoshda hali ham ayrim tovushlarda kamchiliklar saqlanib qolgan bo'lsa, bu jiddiy masala — logoped yordami zarur. Aks holda, maktab ta'limi bola uchun qiyinchiliklar manbasiga aylanadi. Tarbiyachi bunday bolalarni o'z vaqtida aniqlashi va kerakli yo'nalishga yo'llashi shart.",
                "Grammatik tomondan katta guruh bolasi murakkab va qo'shma gaplar quris ko'nikmasiga ega bo'ladi. \"Ona shamol qattiq esgani uchun barglar daraxtdan to'kildi\", \"Agar yog'ingarchilik tinmasa, biz sayrga chiqa olmaymiz\" kabi mantiqiy bog'lanishli gaplarni o'zi tuza oladi. Bola fe'lning barcha zamonlarini, nisbat va aspekt shakllarini, sifatning darajalarini to'g'ri qo'llay oladi.",
                "Dialogik nutq jihatidan katta guruh bolasi mukammal suhbatlasha oladi. U bahslashishni, fikrini asoslab berishni, boshqalarning fikriga e'tiroz bildirishni, kelishishni, kechirim so'rashni biladi. Tengdoshlari bilan birgalikda murakkab syujetli o'yinlarni tashkil eta oladi, rolllarni taqsimlay oladi, qoidalarni shartlasha oladi. Bu — ijtimoiylashuv jarayonining muhim ko'rsatkichi va tarbiyachi uni qadrlashi kerak.",
                "Monologik nutq sezilarli darajada rivojlangan. Bola surat asosida 7-10 jumlali bog'liq hikoya tuza oladi, eshitgan ertakni mustaqil qayta aytib bera oladi, o'z tajribasi haqida batafsil hikoya qila oladi, ijodiy hikoyalarni boshlay oladi (\"Agar men sehrgar bo'lsam ...\", \"Bo'lib qolsam ...\"). Bu monologik nutq endi shakllangan va keyingi yillarda mukammallashishi kerak.",
                "Bu yoshda bola til o'rtasidagi taqqoslarni anglay boshlaydi: omonim, sinonim, antonim so'zlarni amalda farqlay oladi, ko'p ma'noli so'zlarning turli ma'nolarini bilib oladi (\"oltin barg\", \"oltin yurak\" — ko'chma ma'no). Tilning go'zalligini, badiiy ifoda vositalarini his eta boshlaydi. Bu — keyingi yillarda adabiy ta'lim uchun zarur tayyorgarlik bosqichidir. Tarbiyachi bola his-tuyg'usini bu yo'nalishda rivojlantirish imkoniyatlariga ega bo'ladi.",
            ],
        ),
        (
            "Lug'atni chuqurlashtirish va so'z ma'nosini boyitish ishlari",
            [
                "Katta guruhda lug'at ishi yangi sifat bosqichiga ko'tariladi. Endi gap nafaqat yangi so'zlarni o'rgatish, balki bolaga so'z ma'nosini chuqur tushunish, uning ko'p qirrali bo'lishini bilish, badiiy ifodalarda qo'llay olish ko'nikmalarini shakllantirish haqida ketadi. Lug'at miqdori bilan birga uning sifati, ya'ni so'zlarni ongli, aniq va o'rinli qo'llay olish bog'cha tarbiyachisining asosiy maqsadiga aylanadi.",
                "Lug'at ishining mavzulari ham kengayadi va chuqurlashadi. Yangi mavzular: O'zbekiston haqida tushuncha, vatanimiz tabiati va madaniyati, mashhur shaharlar (Toshkent, Samarqand, Buxoro, Xiva), milliy bayramlar (Mustaqillik kuni, Navro'z, Hayit), milliy taomlar (osh, manti, somsa, sumalak), milliy kiyimlar (do'ppi, atlas, chopon), professional kasblar (shifokor, muhandis, agronom, dasturchi, fermer) va boshqalar. Bolalar O'zbekistonni, uning tarixini va madaniyatini ana shu so'zlar orqali bilishadi.",
                "Sinonim va antonim so'zlar bilan ishlash maxsus mashqlar shaklida olib boriladi. \"Bir narsani bir necha xil aytish mumkin\" — bu g'oya bolalarga taqdim etiladi: \"katta\", \"ulkan\", \"haybatli\"; \"chiroyli\", \"go'zal\", \"husnli\". Antonimlarning chuqurroq tahlili: \"yorqin — qorong'i\", \"chuqur — sayoz\", \"murakkab — oddiy\". Bunday so'zlar bola nutqini ifodali, jonli va boy qiladi.",
                "Ko'p ma'noli so'zlar va ko'chma ma'no bilan tanishtirish katta guruhdagi yangi bosqichdir. \"Oltin\" — metall, \"oltin barg\" — sariq rangli barg, \"oltin yurak\" — mehribon kishi. \"Sovuq\" — past harorat, \"sovuq munosabat\" — befarq munosabat. Bu mashqlar bolaning til hissini va metaforik fikrlashini rivojlantiradi. Bunday material, albatta, sodda va tushunarli darajada beriladi.",
                "Maqollar, matallar, topishmoqlar bilan ishlash katta guruhda alohida o'rin tutadi. \"Mehnat — baxt kaliti\", \"Ona yer — oltin beshik\", \"Yaxshi gap — tugun yumshatadi, yomon gap — toshni qotiradi\" kabi maqollarning ma'nosi bolalar bilan birga muhokama qilinadi. Maqollar nafaqat lug'atni boyitadi, balki bolaning axloqiy va estetik tarbiyasiga ham xizmat qiladi. Topishmoqlarni topish — fikrlash va lug'atni rivojlantiruvchi mashq.",
                "Bolalar adabiyoti — katta guruhda lug'atni boyitishning asosiy manbalaridan biri. Bu yoshda bolalar hajmi va murakkabligi bo'yicha kattaroq asarlar bilan tanishtiriladi: G'afur G'ulom, Quddus Muhammadiy, Po'lat Mo'min, Mirtemir, Pirimqul Qodirov, Anvar Obidjon va boshqa o'zbek shoir va yozuvchilarining bolalar uchun mo'ljallangan asarlari. Jahon adabiyotidan A.S.Pushkin, A.Lindgren, R.Kipling, Sh.Perro asarlari ham qo'llaniladi.",
                "Lug'atni boyitishda kompyuter o'yinlari va interaktiv dasturlardan ham foydalanish mumkin. Lekin asosiy ish jonli muloqotda, real predmet va hodisalar bilan tanishishda, badiiy adabiyot o'qishda olib boriladi. Texnologiyalar — yordamchi vosita, asosiy o'qituvchi va tarbiyachi esa odamdir. Bola tarbiyachining ko'zlariga, yuziga, ovoziga qarab o'rganadi — bunday hissiy aloqani hech qanday texnika almashtira olmaydi.",
            ],
        ),
        (
            "Grammatik tuzilishni mukammallashtirish va tovush tahlili",
            [
                "Katta guruhda grammatik ish murakkablashadi va chuqurlashadi. Bola endi grammatik shakllarni nazariy bilmasa-da, ularni amalda yaxshi qo'llay oladi. Tarbiyachining vazifasi — bolada grammatik aniqlik, izchillik va xilma-xillikni shakllantirish. Bu yoshdagi bola maxsus mashqlar yordamida grammatik nozikliklarni o'zlashtiradi.",
                "Morfologik tomondan otning kelishik shakllari, fe'lning shaxs-son va zamon shakllari, sifatning oddiy va orttirma darajalari ustida ishlanadi. Maxsus o'yinlar: \"Kim nima qiladi?\" (fe'l zamonlari); \"Kimning nimasi?\" (egalik shakllari); \"Qayerga, qayerdan, qayerda?\" (kelishiklar); \"Eng ...\" (sifat darajalari). Bu o'yinlar bolaga zerikarli emas, balki qiziq va samarali.",
                "Sintaksis bo'yicha katta guruh bolasi turli xil murakkab gaplar quris ko'nikmasini egallashi kerak. Tarbiyachi maxsus mashqlar tashkil etadi: jumlani davom ettirish (\"Bahor keldi va ...\"), jumlani bog'lash (\"Yomg'ir yog'di\" + \"Sayr bekor bo'ldi\" → \"Yomg'ir yog'gani uchun sayr bekor bo'ldi\"), savol asosida gap qurish, deformatsiyalangan jumlani to'g'rilash.",
                "So'z yasalishi bilan tanishtirish bu yoshda boshlanadi. Bolalar so'zlarning ildizlari va qo'shimchalari haqida amaliy tushunchaga ega bo'ladilar. \"Ish — ishchi — ishlamoq — ishxona\"; \"Kitob — kitobxon — kitobxonlik — kitobcha\". Bu mashqlar bola tilini chuqurlashtiradi va leksik boyligini sifat jihatidan oshiradi. Bu mashqlar maktabda morfemik tahlilga zamin yaratadi.",
                "Tovush tahlili bilan ishlash — katta guruhning eng muhim yangiligi. Bu — savod o'rgatishga to'g'ridan-to'g'ri tayyorgarlik. Bola so'zda tovushlarni eshita oladi, ularni navbat bilan ayta oladi, qattiq va yumshoq, jarangli va jarangsiz tovushlarni farqlay oladi. \"Kit\" so'zida nechta tovush bor? Birinchi tovush qaysi? Oxirgi tovush qaysi? Bunday savollar mashg'ulotning ajralmas qismi bo'lishi kerak.",
                "Tovush tahlili bosqichlari: 1) so'zda muayyan tovushni topish; 2) tovushning so'zdagi o'rnini aniqlash (boshida, o'rtasida, oxirida); 3) so'zdagi barcha tovushlarni navbatma-navbat aytish; 4) tovushni belgilash (qattiq tovushlar — ko'k rang, yumshoq tovushlar — yashil rang). Bu mashqlar bolaning fonematik eshitishini va tovush sezgirligini rivojlantiradi va savod ta'limining samarali bosqichiga zamin tayyorlaydi.",
                "Bo'g'in tahlili ham katta guruhda boshlanadi. Bola so'zni bo'g'inlarga ajrata olishi (\"o-na\", \"bo-la\", \"ki-tob\"), bo'g'inlar sonini sanay olishi, urg'uli bo'g'inni ajrata olishi kerak. Bularning hammasi maktabda o'qish o'rganishga muhim asosdir. Tarbiyachi bunday mashqlarni o'yin shaklida olib boradi: chapaklab bo'g'inlar sonini ko'rsatish, bo'g'inlarni navbatma-navbat aytish, bo'g'in zanjirlari tuzish — bularning hammasi qiziq va samarali.",
            ],
        ),
        (
            "Ravon nutqni mukammallashtirish: hikoya turlari va ijodiy nutq",
            [
                "Katta guruhda ravon nutqni rivojlantirish — markaziy va eng muhim vazifadir. Bu yoshda bola turli xil hikoya turlarini o'zlashtirishi, ularni mustaqil qura olishi va boshqalarga taqdim eta olishi kerak. Hikoya — bog'cha pedagogikasida ravon nutqning eng yuqori ko'rinishi sifatida qaraladi va u maxsus, izlanishli ish natijasida shakllanadi. Hikoya tuzish ko'nikmasi bolaning aqliy va nutqiy taraqqiyot ko'rsatkichidir.",
                "Hikoya turlari quyidagicha: 1) tasvirlash hikoyasi — biror predmet, hayvon, manzara, voqelik haqida; 2) syujetli hikoya — voqealar tartibida bayon qilinadigan; 3) tajriba hikoyasi — bola o'z hayotidan voqea aytib berishi; 4) qayta hikoya — eshitilgan ertak yoki hikoyani aytib berish; 5) ijodiy hikoya — bola o'zi to'qib chiqargan voqea. Har bir tur o'z ish usullari va vositalarini talab qiladi.",
                "Tasvirlash hikoyasini o'rganish suratlar va o'yinchoqlar yordamida olib boriladi. Tarbiyachi bola bilan birgalikda tasvirlashning sxemasini ishlab chiqadi: \"Bu nima? Qanday rangda? Qanday shaklda? Qaysi qismlardan iborat? Nima uchun kerak?\". Asta-sekin bola mustaqil ravishda predmetni tasvirlay oladi. Tasvirlashda \"qiyoslash\" usuli ham qo'llaniladi — ikkita predmetni qiyoslab tasvirlash bola fikrini chuqurlashtiradi.",
                "Syujetli hikoya tuzish surat seriyasi yoki bir surat asosida amalga oshiriladi. Surat seriyasi bilan ishlash bosqichlari: 1) suratlar tartibi aniqlanadi; 2) har bir surat ko'rib chiqiladi va u bo'yicha savol-javob; 3) suratlar o'rtasidagi mantiqiy bog'liqlik aniqlanadi; 4) bola navbati bilan har bir surat haqida gapirib, butun voqeani bayon qiladi. Bu mashq bola mantiqiy fikrlashini va ravon nutqini rivojlantiradi.",
                "Qayta hikoya — bog'cha tarbiyachisining doimiy ish turi. Bolalarga maxsus tanlangan ertak, hikoya yoki badiiy asar o'qib beriladi. Tanlash mezonlari: hajmi mos (3-5 daqiqa o'qiladigan), syujeti aniq, til sodda va boy, axloqiy g'oya tushunarli. Eshitishdan keyin suhbat o'tkaziladi, asar yana o'qiladi, va keyin bolalar qayta aytib berishadi — bir bola butunini, yoki bir necha bola qism-qismdan.",
                "Tajriba hikoyalari — bola o'z hayoti haqida gapirishi. Mavzular: \"Dam olish kunlari nima qildim?\", \"Bayramda qaerga bordik?\", \"Yangi yilda nima ko'rgan edim?\", \"Sayohatda eng qiziq nima bo'ldi?\". Tarbiyachi bolaning hikoyasini sabr bilan tinglaydi, savollar berib uni boshqaradi va to'liqlashtiradi. Bunday hikoyalar bolaga o'z fikrini ifoda etish, his-tuyg'ularini ulashish ko'nikmasini beradi.",
                "Ijodiy hikoya — eng yuqori va eng murakkab tur. Bola berilgan boshlanma yoki tasvirdan kelib chiqib o'zi voqea to'qib chiqaradi. Mavzular: \"Sehrli sumka\", \"Qushcha qayerga uchdi\", \"Quyon va tulki o'rmonda\", \"Dengiz osti dunyosida\". Boshida tarbiyachi yordam beradi, namuna ko'rsatadi, savollar bilan yo'naltiradi. Asta-sekin bola mustaqil ijodiy hikoyalar tuza oladigan bo'ladi. Bu — bolaning fantaziyasini, badiiy did va nutqini birga rivojlantiradi.",
            ],
        ),
        (
            "Maktabga tayyorgarlik va savod o'rgatishga zamin yaratish",
            [
                "Katta guruhning asosiy strategik vazifalaridan biri — bolani maktabga muvaffaqiyatli tayyorlash. Bu kompleks vazifa bo'lib, bir necha yo'nalishni o'z ichiga oladi: aqliy tayyorgarlik, jismoniy tayyorgarlik, hissiy-ijtimoiy tayyorgarlik, motivatsion tayyorgarlik va, albatta, nutq tayyorgarligi. Nutq tayyorgarligi maktab o'qishining muvaffaqiyati uchun eng asosiy poydevor hisoblanadi.",
                "Maktabga tayyorgarlikning nutqiy ko'rsatkichlari quyidagilardan iborat: 1) tovushlarni to'g'ri talaffuz qilish; 2) yetarlicha lug'at boyligi (3500-4000 so'z); 3) grammatik to'g'ri va xilma-xil nutq qurish; 4) ravon nutq — dialog va monolog ko'nikmalari; 5) fonematik eshitish va tovush tahlili; 6) so'zga ongli munosabat va til hissiyoti. Tarbiyachi bu ko'rsatkichlarni har bir bolada baholaydi va kerakli ishlarni olib boradi.",
                "Savod o'rgatishga tayyorgarlik to'g'ridan-to'g'ri o'qish va yozishga emas, balki ularning oldindan tayyorlanishiga qaratiladi. Bolalar harflar bilan tanishadilar, lekin maxsus o'qishni o'rganmaydilar. Tarbiyachi bolada o'qishga qiziqish, kitobga muhabbat, yozuv harflarining shaklini his qilish ko'nikmalarini shakllantiradi. Bola maktab boshlanishidan oldin o'qishni mukammal o'rganishi shart emas — bu maktab vazifasi.",
                "Tovush tahlili va sintezi mashqlari bu yoshda kuchaytiriladi. Bola so'zlarni tovushlarga ajrata oladi va tovushlardan so'z tuza oladi. \"K-i-t — kit\", \"O-n-a — ona\". Maxsus o'yinlar: \"Sehrli zanjir\" (har bir keyingi so'z oldingi so'zning oxirgi tovushi bilan boshlanadi: kit-tovuq-quduq-...); \"Tovushni yo'qot\" (so'zdan tovushni olib tashlash). Bunday mashqlar bolaning til ongini rivojlantiradi.",
                "Yozma nutqning oldingi shakllari (qo'l harakatlari, grafik tasvir) ham tarbiyalanadi. Bolalar qog'oz va qalam bilan ishlashga, oddiy chiziqlarni va shakllarni chizishga, harflarning grafik elementlarini takrorlashga o'rganadilar. Mayda motorikani rivojlantiruvchi mashqlar (mozaika, plastilin, rasm chizish, qog'oz kesish, lego) qo'l mushaklarini yozuvga tayyorlaydi. Bu juda muhim ish.",
                "Bolada o'qish va o'rganishga ijobiy munosabat shakllantirish — alohida vazifadir. Maktab haqida ijobiy hikoyalar, maktab hayoti haqida suhbatlar, akabirodarlarning maktab tajribalari haqida muhokamalar, maktab ekskursiyalari — bularning hammasi bola maktabga ishonch va qiziqish bilan kelishini ta'minlaydi. \"Maktabda qiyin\", \"O'qituvchi qattiq\" deyish butunlay noto'g'ri va zararli.",
                "Maktabga tayyorgarlik bog'cha va maktab o'rtasidagi izchillikni talab qiladi. Bog'cha tarbiyachisi maktab boshlang'ich sinf o'qituvchilari bilan hamkorlikda ish olib boradi: maktablarga ekskursiya, maktabda ochiq darslar tashkil etish, o'qituvchilar bilan suhbatlar. Bu bola uchun maktabga o'tishni tabiiy va silliq qiladi, hech qanday stress va qo'rquv keltirib chiqarmaydi. Bog'chadan maktabga o'tish — bola hayotidagi muhim bosqich va u puxta tayyorlangan bo'lishi shart.",
            ],
        ),
    ],
    "refs": COMMON_REFS,
}
