# -*- coding: utf-8 -*-
from ._refs import COMMON_REFS

topic = {
    "num": 1,
    "title": "Nutqini o'stirish metodikasi fanining ilmiy-nazariy asoslari",
    "reja": [
        "Nutq haqida tushuncha va uning insoniyat hayotidagi o'rni.",
        "\"Nutqini o'stirish metodikasi\" fanining predmeti, vazifalari va boshqa fanlar bilan aloqasi.",
        "Fanning falsafiy, fiziologik va psixologik asoslari.",
        "Lingvistik va pedagogik asoslari.",
        "Fanning tadqiqot metodlari va tarixiy taraqqiyoti.",
    ],
    "sections": [
        (
            "Nutq haqida tushuncha va uning insoniyat hayotidagi o'rni",
            [
                "Nutq — bu insonning fikrlari, his-tuyg'ulari va istaklarini til vositalari yordamida ifoda etish jarayonidir. Til esa nutqning shakllanishi uchun zarur bo'lgan ovozlar, so'zlar, grammatik qoidalar va ma'no birliklarining o'ziga xos tizimidir. Til va nutqning o'zaro aloqasi shu darajada chambarchasdir-ki, ularni bir-biridan ajratib bo'lmaydi: til — vosita, nutq — uning amaliy ko'rinishidir. Bu ikki tushuncha o'zaro to'ldirib, insonning ijtimoiy faoliyatini ta'minlaydi.",
                "Nutq insoniyat tarixida tafakkur bilan birga shakllanib, taraqqiy etib kelgan eng muhim ijtimoiy hodisadir. U avlodlardan-avlodlarga bilim, tajriba, an'ana va madaniyatni yetkazib berishning asosiy vositasi sifatida xizmat qiladi. Nutq tufayli odamlar bir-biri bilan muloqot qiladi, hamkorlikda mehnat qiladi, his-tuyg'ularini ulasha oladi va o'zlarini ijtimoiy mavjudot sifatida namoyon etadi. Aynan shu sababli olimlar nutqni \"insoniylikning eng katta belgisi\" deb atashadi.",
                "Nutqning bir necha asosiy funktsiyalari mavjud bo'lib, ular o'zaro chambarchas bog'langan. Birinchidan, kommunikativ funktsiya — kishilar o'rtasida axborot almashinuvini ta'minlaydi. Ikkinchidan, fikrni shakllantirish funktsiyasi — inson nutq orqali fikrlaydi va uni boshqalarga yetkazadi. Uchinchidan, regulyativ funktsiya — odamning xulqi va faoliyatini boshqarishga yordam beradi. To'rtinchidan, ekspressiv funktsiya — his-tuyg'ularni ifoda etadi. Beshinchidan, nominativ funktsiya — narsa va hodisalarni nomlash imkonini beradi.",
                "Nutq inson hayotining barcha sohalarida — oilada, bog'chada, maktabda, mehnat jamoasida, ijtimoiy munosabatlarda muhim o'rin tutadi. Bola hayotining dastlabki yillaridanoq nutq orqali atrofdagi olamni o'zlashtiradi, uning haqidagi tasavvurlarini boyitadi va shakllantiradi. Nutq orqali bola kattalardan, tengdoshlaridan o'rganadi; ona allasi, ertak, qo'shiq, she'r — bularning barchasi bola nutqini boyitishga, uning ma'naviy olamini shakllantirishga xizmat qiladi.",
                "Nutqning psixik taraqqiyotdagi o'rni beqiyosdir. Mashhur psixolog L.S.Vigotskiyning ta'kidlashicha, nutq nafaqat muloqot vositasi, balki tafakkurning shakllanishida, idrok va xotiraning rivojlanishida, irodaning tarbiyalanishida ham hal qiluvchi rol o'ynaydi. Bola so'zni o'zlashtirar ekan, u bilan bir vaqtda fikrlash usullarini, mantiqiy bog'liqliklarni, hukm va xulosa chiqarish ko'nikmalarini ham egallaydi. Demak, nutqni o'stirish — bu butun aqliy taraqqiyotni boshqaruvchi jarayondir.",
                "Maktabgacha yoshdagi davr — bola nutqi rivojlanishidagi eng sermahsul va eng muhim davr hisoblanadi. Aynan shu davrda bola tovushlarni to'g'ri talaffuz qilishni, asosiy lug'at boyligini, grammatik qoidalarni va ravon nutq malakalarini o'zlashtiradi. Olimlar bu davrni \"nutq sezgirligi davri\" (sensitive period) deb atashadi, chunki keyinchalik o'zlashtirilmagan nutq ko'nikmalarini to'ldirish ancha mushkul bo'ladi. Shu sababli ham bog'cha tarbiyachisining vazifasi nihoyatda mas'uliyatlidir.",
                "Insoniyat tarixiga nazar tashlasak, qadimgi yunon faylasuflari Aristotel va Sokratdan tortib, hozirgi zamon olimlarigacha nutqning insoniylikdagi o'rniga katta e'tibor qaratganlar. Sharq mutafakkirlari Forobiy, Beruniy, Ibn Sino, Yusuf Xos Hojib, Alisher Navoiy o'z asarlarida nutq madaniyati, til go'zalligi, so'z qudrati haqida qimmatli fikrlarni qoldirganlar. Bularning barchasi nutqni o'rganish va uni o'stirishga oid fanning shakllanishiga zamin yaratgan.",
            ],
        ),
        (
            "\"Nutqini o'stirish metodikasi\" fanining predmeti, vazifalari va boshqa fanlar bilan aloqasi",
            [
                "\"Nutqini o'stirish metodikasi\" — pedagogika fanining tarmog'i bo'lib, u maktabgacha yoshdagi bolalarning ona tilini muvaffaqiyatli o'zlashtirishi, nutqini har tomonlama rivojlantirishi qonuniyatlari, vositalari va metodlarini o'rganadi. Bu fanning asosiy predmeti — bola nutqini ongli ravishda boshqarish, rejalashtirish va samarali rivojlantirish jarayonidir. Fan amaliy tabiatga ega bo'lib, tarbiyachilar uchun ilmiy asoslangan ishonchli yo'l-yo'riqlar, metodlar va vositalarni taqdim etadi.",
                "Fanning ilmiy-nazariy vazifasi — bola nutqi taraqqiyotining qonuniyatlarini ochib berish, har xil yoshdagi bolalarda nutqning shakllanish bosqichlarini tahlil qilish va bu jarayonga ta'sir etuvchi omillarni aniqlashdan iborat. Bu vazifa bajarilgan taqdirdagina, amaliy ishni samarali tashkil etish mumkin bo'ladi. Nazariya amaliyot uchun yo'lchiroq vazifasini bajaradi, amaliyot esa nazariyaning to'g'riligini sinaydi va boyitadi.",
                "Amaliy vazifalari quyidagilardir: birinchidan, bolalarning lug'at boyligini muntazam oshirib borish; ikkinchidan, ona tilining grammatik tuzilishini o'zlashtirishga yordam berish; uchinchidan, tovushlarni to'g'ri talaffuz qilish va nutq tovush madaniyatini tarbiyalash; to'rtinchidan, ravon nutq — dialogik va monologik nutqni rivojlantirish; beshinchidan, badiiy adabiyot orqali nutqni go'zallashtirish va boyitish; oltinchidan, savod o'rgatishga zamin tayyorlash.",
                "Fan bir qator boshqa fanlar bilan chambarchas aloqada rivojlanadi. Falsafa fani bilan bog'liqligi — nutqning ijtimoiy mohiyati, uning tafakkur bilan munosabati, til va voqelik munosabati kabi nazariy masalalarda namoyon bo'ladi. Falsafiy yondashuv pedagogga bola nutqini umuminsoniy madaniyat va ma'naviyat doirasida ko'rishga imkon beradi. Bu yondashuv usuliga falsafa fanida \"germenevtik\" yoki \"ramziy\" yondashuv deb ataladi.",
                "Tilshunoslik (lingvistika) bilan aloqasi eng yaqin va bevosita aloqadir. Aynan tilshunoslikdan fan til tizimining tuzilishi — fonetika, morfologiya, sintaksis, leksika va semantika to'g'risidagi nazariy bilimlarni oladi. Bu bilimlarsiz tarbiyachi tovush, so'z va gap ustida samarali ish olib bora olmaydi. Shuningdek, sotsiolingvistika fani til va jamiyat o'rtasidagi aloqani, psixolingvistika esa nutq va psixika o'rtasidagi munosabatni yoritib beradi, va bularning hammasi metodikaga foyda keltiradi.",
                "Psixologiya fani bola nutq taraqqiyotining ichki qonuniyatlarini, motivatsiyasini, his-tuyg'u va idrok bilan aloqasini, individual xususiyatlarini ochib beradi. L.S.Vigotskiy, A.N.Leontev, J.Piaget, S.L.Rubinshteyn, D.B.Elkonin kabi olimlarning tadqiqotlari nutqni o'rgatish bo'yicha asosli metodikalar yaratishga zamin bo'lib xizmat qildi. Pedagog psixologik bilimlardan foydalanmasdan turib, bola dunyosiga kirish va uning nutqini boshqara olishi mumkin emas.",
                "Fiziologiya, neyrofiziologiya va anatomiya fanlari nutq apparati tuzilishi va ishlash mexanizmlari, bosh miya va asab tizimi bilan nutqning aloqasi haqidagi bilimlarni beradi. I.P.Pavlovning birinchi va ikkinchi signal tizimlari haqidagi ta'limoti, P.K.Anoxinning funksional tizimlar nazariyasi nutqni o'rgatishda nima fiziologik jarayonlar kechishini tushuntirib beradi. Bundan tashqari, defektologiya, logopediya, gigiena fanlari ham metodikani to'ldiradi va boyitadi.",
            ],
        ),
        (
            "Fanning falsafiy, fiziologik va psixologik asoslari",
            [
                "Falsafiy asoslar — bu nutqni o'rgatishga oid yondashuvlarning eng chuqur, dunyoqarash darajasidagi tamoyillaridir. Falsafa fani til va tafakkur, til va madaniyat, til va shaxsning shakllanishi munosabatlarini umumiy nazariy darajada o'rganadi. Marksistik falsafa nutqni mehnat va ijtimoiy faoliyat zaminida vujudga kelgan ijtimoiy hodisa sifatida talqin qiladi: \"Til mehnat bilan birga vujudga kelgan, mehnat insonni vujudga keltirgan\" degan tezis ana shu yondashuvni ifodalaydi.",
                "Hozirgi davr falsafasida nutqqa nisbatan turli yondashuvlar mavjud: pozitivistik, ekzistensial, fenomenologik va germenevtik yondashuvlar. Pedagogik amaliyot uchun esa, eng asosiysi, har bir bolaning shaxs sifatida betakrorligini, uning nutq orqali o'z borlig'ini ifoda eta olishini, til esa shu shaxsning ichki olamini tashqi olamga ulash ko'prigi ekanligini tushunishdir. Demak, falsafiy asos pedagogga \"insonparvarlik tamoyili\" — har bir bolaning shaxsiy qadr-qimmatini hurmat qilish vazifasini yuklaydi.",
                "Fiziologik asoslar — nutqni o'stirishning biologik mexanizmlari to'g'risidagi bilimlardir. Akademik I.P.Pavlovning yuksak asab faoliyati haqidagi ta'limoti bu sohaning tamal toshidir. Pavlov birinchi signal tizimi (atrof-muhitdan keladigan bevosita qo'zg'aluvchilar — ko'rish, eshitish, hidlash, ta'm bilish) va ikkinchi signal tizimi (so'z) haqidagi nazariyani ishlab chiqdi. So'z — bu \"signal signali\", ya'ni u bilvosita boshqa qo'zg'aluvchilarni almashtira oladi va shu tariqa odam fikrlay oladi.",
                "Bola tug'ilgandan boshlab uning bosh miyasi va asab tizimi nutqni o'zlashtirishga tabiiy ravishda tayyor holda bo'ladi. Lekin bu imkoniyatning ro'yobga chiqishi uchun bolaning kattalar bilan muloqot qilishi, til muhitida bo'lishi shartdir. Bosh miyaning chap yarim sharidagi maxsus nutq markazlari — Brokaning markazi (motor nutq) va Vernikening markazi (sensor nutq) — nutqni qabul qilish va talaffuz qilish funksiyalarini bajaradi. Bu markazlar bola hayotining birinchi 5-6 yilida intensiv shakllanadi, va aynan shu davrda nutqni o'rgatish eng samaralidir.",
                "Nutq apparati uchta qismdan iborat: markaziy qism (bosh miya), nafas qismi (o'pka, diafragma, traxeya) va periferik qism (xalqum, ovoz pardalari, og'iz bo'shlig'i, til, lab, tish). Bu uch qismning bir-biri bilan muvofiq ishlashi natijasida tovush hosil bo'ladi. Bog'cha tarbiyachisi nutq apparatining tuzilishini bilishi va bolalarda tovushlarni to'g'ri talaffuz qilishga, nafas olish va chiqarishni boshqarishga, ovoz balandligi va tezligini me'yorlashga yordam berishi kerak.",
                "Psixologik asoslar — bola psixikasining nutq taraqqiyotidagi rolini ochib beradi. L.S.Vigotskiyning madaniy-tarixiy konsepsiyasi bo'yicha, bolaning psixik taraqqiyoti ijtimoiy va madaniy muhit ta'sirida amalga oshadi. \"Yaqin taraqqiyot zonasi\" tushunchasi muhim ahamiyatga ega: bola hozir kattalar yordamida bajarayotgan ish ertaga uning mustaqil bajarish darajasiga aylanadi. Demak, tarbiyachining vazifasi — bolani u erisha oladigan, lekin hozircha bir oz qiyin keluvchi vazifalar bilan band qilishdir.",
                "Faoliyat psixologiyasi (A.N.Leontev) bo'yicha, nutq ham boshqa psixik jarayonlar kabi faoliyat jarayonida shakllanadi. Bola \"o'rganish uchun o'rganmaydi\", balki o'yin orqali, mehnat orqali, muloqot orqali nutqni o'zlashtiradi. Shu sababli metodikada faoliyat asosida o'rgatish tamoyili eng muhim tamoyillardan biri hisoblanadi. Tarbiyachi o'yinlar, ekskursiyalar, badiiy faoliyat orqali bolaning nutqini bilvosita rivojlantiradi, bu esa to'g'ridan-to'g'ri \"saboq berishdan\" ko'ra ancha samarali bo'ladi.",
            ],
        ),
        (
            "Lingvistik va pedagogik asoslari",
            [
                "Lingvistik (tilshunoslik) asoslar bo'lim — fanning eng muhim ilmiy ustunlaridan biridir. Tilshunoslik fani har qanday tilning tovush, leksik, grammatik va stilistik tuzilishini o'rganadi. Bog'cha tarbiyachisi til tizimini bilmasdan turib, bolaning nutqini ongli ravishda rivojlantira olmaydi. Aynan tilshunoslik bilimlari asosida tarbiyachi tovushlar va so'zlar ustida ishlash, gap tuzish, matn yaratishning to'g'ri yo'nalishini belgilab oladi.",
                "Fonetika fani til tovushlari va ularning funksional tabiatini o'rganadi. Tarbiyachi o'zbek tili fonetik tizimini, unli va undosh tovushlarning tasniflanishini, urg'u va ohang qoidalarini bilishi shart. Aks holda, bola tovushlarni xato talaffuz qilganda, uni to'g'rilash imkoniyatini topa olmaydi. Masalan, [s], [sh], [ch], [j], [r] tovushlari ko'pincha bolalarda qiyinchilik tug'diradi va ular bilan maxsus ish olib borish talab etiladi.",
                "Leksikologiya fani til lug'at tarkibini, so'zlarning ma'nosi va o'zaro munosabatini o'rganadi. Tarbiyachi sinonim, antonim, omonim, ko'p ma'noli so'zlar, sodda va yasama so'zlar haqidagi bilimlarni egallagan bo'lishi kerak. Bu bilimlar bolalar bilan lug'at ishini olib borishda zarur. Frazeologiya — turg'un birikmalar (maqol, matal, idiomalar)ni o'rganuvchi soha — bola nutqini tasvirli, jonli va boy qiladi.",
                "Morfologiya so'z turkumlari va ularning grammatik shakllarini o'rganadi. Tarbiyachi ot, sifat, son, olmosh, fe'l, ravish, ko'makchi va boshqa so'z turkumlarining xususiyatlarini bilishi kerak. O'zbek tilida fe'lning zamonlari, kelishik shakllari, egalik qo'shimchalari kabi grammatik kategoriyalar bola tomonidan asta-sekin o'zlashtiriladi. Sintaksis esa so'z birikmasi va gap tuzilishini, gap turlari va ularning ifoda imkoniyatlarini o'rganadi.",
                "Pedagogik asoslar — bu fanning amaliy yo'nalishini belgilovchi tamoyillar majmuidir. K.D.Ushinskiy, Ya.A.Komenskiy, V.A.Suxomlinskiy, A.S.Makarenko, Sh.A.Amonashvili kabi pedagoglarning ta'limotlari bu sohada chuqur iz qoldirgan. Ushinskiyning \"ona tili — xalqning eng buyuk pedagogi\" tezisi nutqni o'rgatishning milliy zaminini ko'rsatadi. Bola ona tilini chinakam o'zlashtirar ekan, u bilan birga xalqning ruhiyatini, madaniyatini va dunyoqarashini ham o'zlashtiradi.",
                "O'zbek pedagogikasida Abdulla Avloniy, Hamza Hakimzoda, Munavvarqori, M.Behbudiy va boshqa ma'rifatparvarlar nutqni o'rgatish, ona tilini sevish, savod o'rgatish bo'yicha o'lmas asarlarni qoldirganlar. Avloniyning \"Turkiy guliston yoxud axloq\" asari bola tarbiyasi va so'z madaniyatining yorqin namunasidir. Hozirgi davr o'zbek metodikasi shu boy merosga, shuningdek, jahon pedagogikasining ilg'or yutuqlariga tayanadi.",
                "Pedagogik tamoyillar orasida bola yoshiga moslik, izchillik (sistematiklik), ko'rgazmalilik, anglashlilik, mustahkamlik, individuallashtirish, faollik, tarbiyaviylik kabilar muhim o'rin tutadi. Bu tamoyillar yagona tizim sifatida ishlaydi va tarbiyachining barcha mashg'ulot va faoliyatlarida amalga oshiriladi. Pedagogik tamoyillarni qattiq qoidalar emas, balki ijodiy yo'l-yo'riqlar deb tushunish kerak: tarbiyachi vaziyatga qarab ularni ijodiy qo'llay bilishi shart.",
            ],
        ),
        (
            "Fanning tadqiqot metodlari va tarixiy taraqqiyoti",
            [
                "Har bir mustaqil fan o'ziga xos tadqiqot metodlariga ega bo'ladi. Nutqini o'stirish metodikasi fanida ham ilmiy bilimni olish va sinash uchun bir qator metodlardan foydalaniladi. Birinchi va eng muhim metod — pedagogik kuzatishdir. Tarbiyachi yoki tadqiqotchi bolalarning kundalik faoliyatida nutqlarini sistemali tarzda kuzatib boradi va olingan ma'lumotlarni qayd etib, tahlil qiladi. Kuzatish ochiq yoki yashirin tarzda olib borilishi mumkin.",
                "Pedagogik tajriba (eksperiment) metodi — nutq ish jarayonini ataylab tashkil etish va uning natijalarini sinash usulidir. Tajriba uch bosqichdan iborat bo'ladi: aniqlovchi tajriba (boshlang'ich holatni aniqlash), shakllantiruvchi tajriba (yangi metod yoki yondashuvni qo'llash) va nazorat tajribasi (natijalarni tekshirish). Bu metod fan rivojining ilmiy asosini tashkil qiladi va yangi metodikalarni ishonchli tarzda yaratish imkonini beradi.",
                "Suhbat va anketa metodlari — tarbiyachilar, ota-onalar va bolalar bilan o'tkaziladigan og'zaki yoki yozma so'rovlardir. Bu metodlar yordamida muayyan masalalar bo'yicha fikrlar, qarashlar va tajribalar to'planadi. Suhbat erkin yoki standartlashgan, shaxsiy yoki guruhli bo'lishi mumkin. Anketalar yopiq (oldindan tayyorlangan javob variantlari bilan) yoki ochiq (erkin javob beriladigan) ko'rinishda bo'ladi va katta hajmdagi ma'lumotlarni qisqa muddatda yig'ishga imkon beradi.",
                "Bolalar nutqi mahsulotlarini o'rganish — bola tomonidan aytilgan hikoyalar, qayta hikoyalar, savol-javoblar, lug'at namunalari yozma yoki audio shaklda qayd etiladi va keyin tahlil qilinadi. Bu metod bola nutqining real holatini, uning rivojlanish dinamikasini ko'rishga imkon beradi. Hozirgi zamon texnologiyalari (audio va videoyozuvlar) bu metodning imkoniyatlarini sezilarli darajada kengaytirgan.",
                "Pedagogik hujjatlarni o'rganish — Davlat dasturlari, mashg'ulot rejalari, kalendar-mavzu rejalari, tarbiyachilarning kundalik daftarlari, hisobotlar va boshqa hujjatlarni tahlil qilish ham fan uchun zarur metoddir. Bu metod orqali pedagogik amaliyotning umumiy holati, yutuq va kamchiliklari ochib beriladi. Statistik metodlar esa to'plangan ma'lumotlarni miqdoriy ko'rsatkichlar yordamida tahlil qilish va qonuniyatlarni aniqlashga yordam beradi.",
                "Fanning tarixiy taraqqiyotiga nazar tashlasak, qadimiyat davridanoq mutafakkirlar bola nutqini o'stirish masalasiga e'tibor qaratganlarini ko'rishimiz mumkin. Aflotun, Aristotel, Kvintilian asarlarida nutq tarbiyasi haqida fikrlar uchraydi. Sharqda Forobiy o'zining \"Ihso al-ulum\" (\"Ilmlar sanasi\") asarida til va ritorika ilmlarini ta'riflagan, Beruniy va Ibn Sino til o'rganishning tabiatini, Yusuf Xos Hojib esa \"Qutadg'u bilig\"da so'z odobini ulug'lagan.",
                "XIX asrning ikkinchi yarmida Ya.A.Komenskiyning \"Buyuk didaktika\" asari, K.D.Ushinskiyning ona tili haqidagi g'oyalari fan rivojiga katta hissa qo'shgan. Rossiyada Ye.I.Tixiyeva birinchi marotaba bog'cha bolalari uchun nutqni o'stirish bo'yicha izchil metodikani ishlab chiqdi. O'zbekistonda XX asrning 60-yillaridan boshlab F.Yo'ldosheva, V.Karimova, Sh.Sodiqova kabi olimlar milliy zaminda mukammal metodikalar yaratdilar. Hozirgi davrda fan kompyuter texnologiyalari, multimediya vositalari, inklyuziv ta'lim tamoyillari bilan boyib bormoqda.",
            ],
        ),
    ],
    "refs": COMMON_REFS,
}
