# -*- coding: utf-8 -*-
from ._refs import COMMON_REFS

topic = {
    "num": 13,
    "title": "Lug'atni boyitish uchun yordam beradigan o'yin turlari. Ko'rgazmali materiallar bilan o'ynaladigan o'yinlar mazmuni",
    "reja": [
        "Lug'atni boyituvchi o'yinlarning umumiy tavsifi.",
        "Predmetli o'yinlar va ularning mazmuni.",
        "Ko'rgazmali (surat) materiallar bilan o'ynaladigan o'yinlar.",
        "So'zli (og'zaki) o'yinlar va ularning mazmuni.",
        "Ko'rgazmali materiallarni tanlash, tayyorlash va qo'llash.",
    ],
    "sections": [
        (
            "Lug'atni boyituvchi o'yinlarning umumiy tavsifi",
            [
                "Lug'atni boyitish — nutqni o'stirishning markaziy vazifalaridan biri bo'lib, uni hal qilishda o'yinlar muhim o'rin tutadi. Lug'atni boyituvchi o'yinlar — bola so'z boyligini kengaytirish, mustahkamlash, faollashtirish va aniqlashtirishga yo'naltirilgan maxsus didaktik o'yinlardir. Bu o'yinlar bog'cha pedagogikasida boy va xilma-xil bo'lib, ularning har biri o'z ta'limiy vazifasini bajaradi.",
                "Lug'atni boyituvchi o'yinlar materialiga ko'ra uch asosiy guruhga bo'linadi: 1) predmetli o'yinlar (real predmetlar va o'yinchoqlar bilan); 2) ko'rgazmali o'yinlar (suratlar va kartochkalar bilan); 3) so'zli o'yinlar (faqat og'zaki, materialsiz). Bu uch guruh bola yoshiga qarab tanlanadi: kichik yoshda predmetli, o'rta yoshda ko'rgazmali, katta yoshda so'zli o'yinlar ustun bo'ladi.",
                "Bu o'yinlar lug'at ishining barcha vazifalarini hal etadi. Boyitish — o'yin orqali yangi so'zlar kiritiladi. Mustahkamlash — ma'lum so'zlar takrorlanadi. Faollashtirish — passiv so'zlar faol qo'llaniladi. Aniqlashtirish — so'z ma'nosi chuqurlashtiriladi. Tizimlashtirish — so'zlar guruhlarga ajratiladi. Bir o'yinda bir necha vazifa bir vaqtda hal qilinishi mumkin.",
                "Lug'atni boyituvchi o'yinlar lug'atning turli tomonlarini rivojlantiradi. Otlarni boyituvchi o'yinlar (narsalar nomi); fe'llarni boyituvchi o'yinlar (harakatlar); sifatlarni boyituvchi o'yinlar (xususiyatlar); umumlashtiruvchi so'zlarni shakllantiruvchi o'yinlar (mevalar, hayvonlar); sinonim va antonimlarni o'rgatuvchi o'yinlar. Tarbiyachi har bir yo'nalish bo'yicha mos o'yinlarni tanlaydi.",
                "Lug'at o'yinlarining samaradorligi ularning psixologik tabiatiga asoslanadi. O'yinda bola emotsional ko'tarinki holatda bo'ladi, qiziqish bilan ishtirok etadi, zo'riqishsiz o'rganadi. Bunday holatda yangi so'zlar oson va mustahkam o'zlashtiriladi. Bundan tashqari, o'yinda so'z real harakat va vaziyat bilan bog'lanadi, bu esa uni xotirada mustahkam saqlaydi. O'yin — lug'at ishining eng tabiiy va eng samarali metodidir.",
                "Lug'at o'yinlari nafaqat lug'atni, balki bolaning umumiy taraqqiyotini ham ta'minlaydi. O'yinda bola diqqat, xotira, tafakkurni rivojlantiradi; intizom, navbat, hamkorlik fazilatlarini egallaydi; muloqot va ijtimoiy ko'nikmalarni shakllantiradi. Shu sababli lug'at o'yinlari — kompleks ta'sirga ega universal pedagogik vositadir. Ular bog'cha hayotining ajralmas qismi bo'lishi kerak.",
                "Tarbiyachi lug'at o'yinlarining boy arsenaliga ega bo'lishi va ularni mohirlik bilan qo'llashi kerak. U o'yinlarni mavzular va vazifalar bo'yicha tizimlashtiradi, ularni bola yoshiga moslaydi, izchil va rejali olib boradi. Yaxshi tarbiyachi har bir vaziyat uchun mos o'yinni topa oladi va uni qiziqarli o'tkaza oladi. Lug'at o'yinlari metodikasini bilish — tarbiyachi professional kompetentsiyasining muhim qismidir.",
            ],
        ),
        (
            "Predmetli o'yinlar va ularning mazmuni",
            [
                "Predmetli o'yinlar — real predmetlar, o'yinchoqlar, tabiiy materiallar bilan o'tkaziladigan o'yinlardir. Bu o'yinlar lug'atni boyitishda eng samarali, ayniqsa kichik yoshdagi bolalar uchun. Buning sababi — bunday o'yinlarda bola so'zni real, ushlash mumkin bo'lgan narsa bilan bog'laydi. Bola predmetni ko'radi, ushlaydi, paypaslaydi, hidlaydi — barcha sezgilari ishlaydi va so'z mustahkam o'zlashtiriladi.",
                "\"Sehrli qopcha\" (\"Ajoyib quticha\") — eng mashhur predmetli o'yinlardan biridir. Qopchaga turli predmetlar solinadi. Bola qo'lini qopchaga solib, predmetni paypaslab topadi, uni nomlaydi va tasvirlaydi: \"Bu — to'p. U dumaloq, silliq, yumshoq\". Bu o'yin lug'atni boyitadi, sezgilarni o'tkirlashtiradi va tasvirlash ko'nikmasini shakllantiradi. O'yin har xil mavzularda (mevalar, o'yinchoqlar, geometrik shakllar) o'tkazilishi mumkin.",
                "\"Nima o'zgardi?\" va \"Nima yo'qoldi?\" — diqqat va lug'atni rivojlantiruvchi o'yinlar. Stolga bir necha predmet qo'yiladi, bolalar ularni eslab qoladilar. Keyin bir predmet olib qo'yiladi yoki joyi o'zgartiriladi. Bolalar nima o'zgarganini aytadilar. Bu o'yin lug'atni faollashtiradi, diqqat va xotirani rivojlantiradi. O'yin bola yoshiga qarab murakkablashtiriladi (predmetlar soni ko'paytiriladi).",
                "\"Magazin\" — syujetli-didaktik o'yin bo'lib, lug'atni boyitadi va dialogik nutqni rivojlantiradi. Bolalar sotuvchi va xaridor rollarini o'ynaydilar. Xaridor mahsulot nomini aytib, uni \"sotib oladi\", sotuvchi esa mahsulotni topib beradi. O'yinda bola mahsulot nomlarini, ularning xususiyatlarini, savdo dialoglarini o'rganadi. \"Mevalar do'koni\", \"O'yinchoqlar do'koni\", \"Kiyim do'koni\" kabi variantlar bo'lishi mumkin.",
                "\"Juftini top\" — predmetlarni juftlash o'yini. Bolaga turli predmetlar beriladi va u ularning juftini (paypoq, qo'lqop, tufli) topadi va nomlaydi. Bu o'yin lug'atni boyitadi va mantiqiy fikrlashni rivojlantiradi. \"Kimga nima kerak?\" o'yini esa kasb va asboblarni bog'laydi (shifokorga — fonendoskop, oshpazga — qozon, dehqonga — ketmon). Bu o'yin kasblar lug'atini boyitadi.",
                "Tabiiy materiallar bilan o'yinlar — barglar, mevalar, sabzavotlar, urug'lar, toshlar, qobiqlar bilan o'tkaziladigan o'yinlar. \"Qaysi daraxtning bargi?\" (barglarni daraxtlar bilan bog'lash); \"Mevalar va sabzavotlar\" (ularni ajratish va nomlash); \"Ta'mini top\" (ko'zni yumib mevani ta'mi bo'yicha aniqlash). Bu o'yinlar tabiat lug'atini boyitadi va bolaning sezgilarini rivojlantiradi.",
                "Predmetli o'yinlarning afzalligi shundaki, ular bolaning barcha sezgilarini ishga soladi va so'zni real narsa bilan bog'laydi. Bu — \"so'z va narsa birligi\" tamoyilining amaliy ifodasidir. Kichik yoshdagi bola fikrlashi ko'rgazmali-amaliy bo'lganligi uchun, predmetli o'yinlar ular uchun eng mos va eng samaralidir. Tarbiyachi predmetli o'yinlar uchun boy material bazasiga — turli o'yinchoqlar, predmetlar, tabiiy materiallarga ega bo'lishi kerak.",
            ],
        ),
        (
            "Ko'rgazmali (surat) materiallar bilan o'ynaladigan o'yinlar",
            [
                "Ko'rgazmali o'yinlar — suratlar, kartochkalar, rasmlar bilan o'tkaziladigan didaktik o'yinlardir. Bu o'yinlar lug'atni boyitishda keng qo'llaniladi, ayniqsa o'rta va katta yoshdagi bolalar uchun. Surat — bola bevosita ko'ra olmaydigan narsalar (yovvoyi hayvonlar, uzoq mamlakatlar, kasblar) bilan tanishtirishda muhim vosita. Surat orqali bolaning lug'ati real predmetlardan ancha kengroq doirada boyiydi.",
                "\"Lotto\" — eng mashhur ko'rgazmali o'yinlardan biridir. Bolalarda katta kartalar (bir necha rasmli), tarbiyachida kichik kartochkalar bo'ladi. Tarbiyachi kichik kartochkani ko'rsatadi va nomlaydi, mos rasmi bo'lgan bola uni o'z kartasiga qo'yadi. Birinchi bo'lib kartasini to'ldirgan bola yutadi. Bu o'yin lug'atni boyitadi va diqqatni rivojlantiradi. \"Mevalar loto\", \"Hayvonlar loto\", \"Kasblar loto\" kabi mavzularda bo'ladi.",
                "\"Domino\" — suratli kartochkalarni juftlash o'yini. Har bir kartochkada ikkita rasm bo'ladi. Bolalar navbat bilan mos rasmli kartochkalarni qo'shadilar va rasmlarni nomlaydilar. Bu o'yin lug'atni mustahkamlaydi va mantiqiy fikrlashni rivojlantiradi. \"Juft top\" (memori) o'yini esa xotirani rivojlantiradi: bir xil rasmli kartochkalarni topish va nomlash.",
                "\"Nima ortiqcha?\" — mantiqiy-lug'aviy o'yin. Bolaga 4 ta rasm ko'rsatiladi, ulardan 3 tasi bir guruhga mansub, 1 tasi ortiqcha. Bola ortiqchasini topadi va nima uchun ortiqcha ekanligini tushuntiradi: \"Olma, nok, uzum — mevalar, sabzi esa — sabzavot, shuning uchun u ortiqcha\". Bu o'yin lug'atni boyitadi, umumlashtiruvchi tushunchalarni shakllantiradi va mantiqiy fikrlashni rivojlantiradi.",
                "\"Qism va butun\" — predmet qismlarini o'rgatuvchi o'yin. Bolaga butun predmet (mashina, uy, daraxt) va uning qismlari (g'ildirak, eshik, barg) rasmlari beriladi. Bola qismlarni butun bilan bog'laydi va nomlaydi. Bu o'yin lug'atni boyitadi (qismlar nomi) va tahlil qilish ko'nikmasini rivojlantiradi. \"Kim qayerda yashaydi?\" o'yini esa hayvonlar va ularning uylarini bog'laydi (it — kataki, qush — uya, ari — uya).",
                "Syujet suratlari bilan o'yinlar lug'at va ravon nutqni birga rivojlantiradi. \"Surat bo'yicha hikoya tuz\" — bola syujet surati asosida hikoya quradi. \"Surat seriyasini tartibla\" — bola voqea suratlarini tartibga soladi va hikoya qiladi. \"Suratda nima yashiringan?\" — bola suratdagi yashirin detallarni topadi va nomlaydi. Bu o'yinlar lug'atni boyitadi va monologik nutqni rivojlantiradi.",
                "\"Tasvirlab top\" — tasvirlash o'yini. Tarbiyachi rasmni ko'rsatmasdan tasvirlaydi, bolalar topadilar: \"U dumaloq, qizil, shirin, daraxtda o'sadi\" — \"Olma!\". Yoki aksincha, bola rasmni tasvirlaydi, boshqalar topadilar. Bu o'yin lug'atni boyitadi, tasvirlash va tinglash ko'nikmasini rivojlantiradi. Ko'rgazmali o'yinlar bolaning ko'rgazmali-obrazli fikrlashiga mos bo'lib, ular lug'at ishining eng samarali vositalaridan biridir.",
            ],
        ),
        (
            "So'zli (og'zaki) o'yinlar va ularning mazmuni",
            [
                "So'zli (og'zaki) o'yinlar — hech qanday material talab qilmaydigan, faqat so'zga tayanadigan o'yinlardir. Bu o'yinlar lug'atni boyitishning eng yuqori bosqichi bo'lib, ular asosan katta va maktabga tayyorlov guruhlarida qo'llaniladi. So'zli o'yinlar bolaning yetuk lug'at va tafakkurini talab qiladi, chunki bola na predmetga, na suratga tayanmaydi — u faqat so'z va tasavvur bilan ishlaydi.",
                "\"Aksini ayt\" (antonimlar o'yini) — eng mashhur so'zli o'yinlardan biridir. Tarbiyachi so'z aytadi, bola uning aksini (antonimini) aytadi: katta — kichik, baland — past, issiq — sovuq, yorqin — qorong'i, shirin — achchiq. Bu o'yin lug'atni boyitadi, antonimlarni mustahkamlaydi va mantiqiy fikrlashni rivojlantiradi. O'yin to'p tashlash bilan o'ynalsa, yanada qiziqarli bo'ladi.",
                "\"Bir xil ma'noli so'z ayt\" (sinonimlar o'yini) — bola berilgan so'zga ma'nodosh so'z topadi: katta — ulkan, chiroyli — go'zal, tez — chaqqon. Bu o'yin bola lug'atini boyitadi va so'z ma'nosi nozikliklarini his etishni o'rgatadi. \"Kim ko'p so'z aytadi?\" o'yini esa bolani mavzu bo'yicha barcha so'zlarni eslab aytishga undaydi: \"Qishki so'zlar\", \"Mevalar\", \"Hayvonlar\".",
                "\"Sehrli zanjir\" — so'zlar zanjiri o'yini. Har bir keyingi so'z oldingi so'zning oxirgi tovushi bilan boshlanadi: kit — tovuq — quduq — qor — ruchka. Bu o'yin lug'atni faollashtiradi, fonematik eshitishni va tovush tahlilini rivojlantiradi, savod o'rgatishga tayyorlaydi. \"Davom ettir\" o'yini esa bolani mavzu bo'yicha so'z zanjirini davom ettirishga undaydi.",
                "\"Bo'ladimi-bo'lmaydimi?\" — mantiqiy so'zli o'yin. Tarbiyachi jumla aytadi, bola uning to'g'ri yoki noto'g'riligini aniqlaydi: \"Qishda qor yog'adi\" (bo'ladi), \"Baliq daraxtda yashaydi\" (bo'lmaydi). Bu o'yin lug'atni boyitadi va mantiqiy fikrlashni rivojlantiradi. \"Kim nima qiladi?\" o'yini esa kasb va harakatlarni bog'laydi: \"Shifokor nima qiladi? — Davolaydi\".",
                "\"Topishmoqlar\" — xalq og'zaki ijodiga asoslangan so'zli o'yin. Tarbiyachi topishmoq aytadi, bolalar javobini topadilar: \"Osmonda yuradi, lekin qush emas\" (bulut). Topishmoqlar lug'atni boyitadi, tafakkurni rivojlantiradi va bolani milliy madaniyat bilan tanishtiradi. \"Kim men?\" o'yinida bola biror narsa nomidan gapiradi, boshqalar uni topadilar: \"Men oqman, sovuqman, qishda yog'aman\" — \"Qor!\".",
                "So'zli o'yinlarning katta afzalligi — ular hech qanday material talab qilmaydi va istalgan joyda o'tkazilishi mumkin: sayrda, transportda, navbat kutishda, uy yumushlari paytida. Bu o'yinlar ota-onalar uchun ham juda qulay — ularni bola bilan har joyda o'ynash mumkin. Tarbiyachi ota-onalarga shunday o'yinlarni o'rgatadi va ulardan uy sharoitida foydalanishni tavsiya etadi. So'zli o'yinlar — lug'atni boyitishning eng qulay va eng yuqori bosqichidir.",
            ],
        ),
        (
            "Ko'rgazmali materiallarni tanlash, tayyorlash va qo'llash",
            [
                "Ko'rgazmali materiallar — lug'at o'yinlarining muhim tarkibiy qismidir. Ularning sifati va to'g'ri tanlanishi o'yin samaradorligini bevosita belgilaydi. Tarbiyachi ko'rgazmali materiallarni tanlash, tayyorlash va saqlash bo'yicha muayyan talablar va qoidalarni bilishi va ularga rioya qilishi kerak. Yaxshi material — muvaffaqiyatli o'yinning moddiy asosidir.",
                "Ko'rgazmali materiallarga qo'yiladigan talablar: 1) aniqlik — rasmda narsa aniq va tushunarli tasvirlangan bo'lishi; 2) realistiklik — rasm haqiqatga mos bo'lishi (hayvonlar, narsalar real ko'rinishda); 3) yorqinlik — ranglar yorqin va jozibali bo'lishi; 4) estetiklik — rasm chiroyli va did bilan ishlangan bo'lishi; 5) bola yoshiga moslik. Bu talablarga javob bermaydigan material o'yin samaradorligini pasaytiradi.",
                "Ko'rgazmali materiallarni tanlashda mavzu va maqsadga muvofiqlik muhim. Tarbiyachi har bir o'yin uchun aniq maqsadga mos materialni tanlaydi. Lug'atni boyitish uchun — yangi narsalar rasmlari; tasniflash uchun — turli guruhga mansub narsalar; antonimlar uchun — qarama-qarshi tushunchalar rasmlari. Material maqsadga xizmat qilishi kerak, aks holda u o'yinni chalkashtiradi.",
                "Materiallarni tayyorlash — tarbiyachining ijodiy ishidir. Tarbiyachi materiallarni turli manbalardan to'playdi: tayyor didaktik o'yinlar, jurnal va kitoblardan kesib olingan rasmlar, o'zi chizgan yoki bosib chiqargan rasmlar, bolalar va ota-onalar yordamida tayyorlangan materiallar. Hozirgi davrda internetdan ham sifatli rasmlarni topish va chop etish mumkin. Materiallar mustahkam (kartonga yopishtirilgan, laminat qilingan) bo'lishi kerak.",
                "Materiallarni saqlash va tartibga solish — muhim tashkiliy masala. Tarbiyachi materiallarni mavzular bo'yicha guruhlaydi va alohida qutilar yoki papkalarda saqlaydi: \"Mevalar\", \"Hayvonlar\", \"Kasblar\", \"Transport\". Har bir o'yin to'plami alohida saqlanadi. Tartibli saqlash materialni topishni osonlashtiradi va uni uzoq saqlanishini ta'minlaydi. Tartibsizlik esa vaqtni yo'qotadi va materialni buzadi.",
                "Ko'rgazmali materiallarni qo'llashda metodik qoidalarga rioya qilinadi: 1) material o'yin maqsadiga mos bo'lishi; 2) material miqdori yetarli, lekin ortiqcha bo'lmasligi (ortiqcha material diqqatni chalg'itadi); 3) material o'yin paytida ko'rsatilishi, oldindan emas (qiziqishni saqlash uchun); 4) material barcha bolalarga ko'rinadigan tarzda joylashtirilishi; 5) material bilan ehtiyotkorlik bilan munosabatda bo'lish va bolalarni ham shunga o'rgatish.",
                "Hozirgi davrda an'anaviy ko'rgazmali materiallar bilan birga zamonaviy texnik vositalar ham qo'llaniladi: interaktiv doska, proyektor, planshet, ta'limiy dasturlar. Bu vositalar o'yinni yanada jozibali va xilma-xil qiladi. Lekin ularni qo'llashda ehtiyotkorlik kerak: ekran oldida o'tkaziladigan vaqt cheklangan bo'lishi, texnika an'anaviy materiallarni butunlay almashtirib qo'ymasligi shart. Real predmet va surat bilan ishlash bola uchun eng tabiiy va eng foydalidir. Tarbiyachi an'anaviy va zamonaviy vositalarni oqilona uyg'unlashtirib, lug'at o'yinlarini eng samarali tarzda tashkil etadi.",
            ],
        ),
    ],
    "refs": COMMON_REFS,
}
