# -*- coding: utf-8 -*-
from ._refs import COMMON_REFS

topic = {
    "num": 6,
    "title": "Ravon nutqni rivojlantirish",
    "reja": [
        "Ravon nutq tushunchasi, mohiyati va shakllari.",
        "Dialogik nutq va uni rivojlantirishning yo'llari.",
        "Monologik nutq turlari va ularni o'rgatish bosqichlari.",
        "Surat, predmet va tabiat asosida hikoya tuzish metodikasi.",
        "Ravon nutqni rivojlantirishda tarbiyachining roli va xatolarni bartaraf etish.",
    ],
    "sections": [
        (
            "Ravon nutq tushunchasi, mohiyati va shakllari",
            [
                "Ravon nutq — bu ifodaga taluqli, mantiqiy izchillikka ega, mazmuni jihatidan tushunarli, til vositalari jihatidan to'g'ri tarzda tashkil etilgan kengaytirilgan nutqdir. Ravon nutqda fikrlar bir-biri bilan mantiqiy bog'langan bo'ladi, yangi axborot ilgari aytilganlar zamirida bayon qilinadi, til vositalari mavzu va vaziyatga muvofiq tanlanadi. Ravon nutq — bola fikrlash darajasining va umumiy aqliy taraqqiyotining eng muhim ko'rsatkichidir.",
                "Ravon nutqning mohiyati shundaki, u bola ichki dunyosini tashqi olamga ulaydi va aksincha — tashqaridan kelgan axborotni bola ongida tashkil qiladi va saqlaydi. Ravon nutq orqali bola olamni anglash va undagi o'z o'rnini topishni o'rganadi. Tilshunoslar va psixologlar ravon nutqni \"tafakkurning og'zaki shakli\" deb atashadi, chunki u tafakkur bilan eng yaqin va bevosita aloqada bo'ladi.",
                "Ravon nutq ikki asosiy shaklga ega: dialogik va monologik. Dialogik nutq — ikki yoki undan ortiq kishilar o'rtasidagi suhbat shaklida tashkil qilingan nutq. Unda har bir ishtirokchi navbatma-navbat gapiradi, savol beradi va javob qaytaradi. Monologik nutq esa bir kishining batafsil, izchil bayoni shaklida bo'ladi va boshqalardan tinglash, idrok etish talab qiladi.",
                "Bu ikki shakl o'zaro chambarchas bog'liq, lekin har biri o'ziga xos xususiyatlarga ega. Dialogik nutq tabiiyroq, hissiy bog'liq, vaziyatga bog'liq, kontekstga tayanadi. Monologik nutq esa rejalashtirilgan, ko'p hollarda mustaqil va to'liq tarzda tashkil qilingan, mantiqiy va til jihatidan murakkabroq bo'ladi. Bola dastlab dialogik nutqni o'zlashtiradi, keyin esa monologik nutqqa o'tadi.",
                "Ravon nutqning rivojlanishi insonning butun hayot davomida davom etadi, lekin uning poydevori bog'cha yoshida quriladi. Aynan shu davrda bolada ravon nutqning asosiy mexanizmlari va ko'nikmalari shakllanadi. Tarbiyachi bu ish uchun maxsus mashg'ulotlar tashkil etadi, kundalik faoliyatdan foydalanadi va bola individualligini hisobga oladi. Ravon nutq mashqlari — bog'chaning kundalik ishi.",
                "Ravon nutq taraqqiyotini bir necha bosqichda kuzatish mumkin: 1) sotuvchi-vaziyatli nutq (1-2 yosh) — bola alohida so'zlar va sodda gaplar bilan o'z ehtiyojlarini bayon qiladi; 2) kontekstli nutq boshlanishi (3-4 yosh) — bola sodda hikoyalar boshlay oladi, lekin uni to'liq olib bora olmaydi; 3) rivojlangan kontekstli nutq (5-7 yosh) — bola batafsil, mantiqiy va to'liq hikoyalar tuza oladi. Har bosqich o'z xususiyatlariga ega.",
                "Ravon nutqning shakllanishi bir qator omillarga bog'liq: bola atrofidagi til muhiti boyligi va sifati; kattalar bilan muloqotning intensivligi; o'qib eshittiriladigan badiiy adabiyotning hajmi va sifati; bolaning shaxsiy aktiv faoliyati; tarbiyachi va ota-onalarning ravon nutqi rivojlanishini boshqarish ko'nikmasi. Hammasi bir-biri bilan o'zaro bog'liq va bir-birini to'ldiradi.",
            ],
        ),
        (
            "Dialogik nutq va uni rivojlantirishning yo'llari",
            [
                "Dialogik nutq — bola hayotidagi eng birinchi va eng tabiiy nutq shakli. U onaning bola bilan birinchi muloqotidan boshlanadi va butun hayot davomida muhim o'rin tutadi. Dialog orqali bola atrofdagi olamni tan oladi, ijtimoiy munosabatlarni o'rganadi, o'z fikrini boshqalarga yetkazishni va ularni tinglashni biladi. Dialogik nutq — ijtimoiylashuvning asosiy vositasidir.",
                "Dialogik nutqning tarkibiy elementlari: savol, javob, talab, taklif, rad etish, kelishish, undash, ifodalash. Bunday elementlarning har biri bog'cha bolasi tomonidan o'zlashtirilishi va to'g'ri qo'llanilishi shart. Tarbiyachi har bir element bo'yicha maxsus ish olib boradi, namunalar ko'rsatadi va bolalarni mashq qildiradi. Bularning hammasi maxsus tashkil etilgan o'yinlar va vaziyatlar yordamida amalga oshiriladi.",
                "Dialogning eng oddiy shakli — savol va javob. Tarbiyachi har kuni bolalarga savollar berdi: \"Bugun nima qildingiz?\", \"Eng yaxshi do'stingiz kim?\", \"Sevimli o'yiningiz qaysi?\". Bola javoblari asta-sekin to'liqlashadi va kengayadi. Boshida bir so'zli javoblar bo'lsa, keyinchalik to'liq jumlalar, keyin esa kichik hikoyalar bilan javob qaytarish ko'nikmasi shakllanadi.",
                "Etiket dialoglarini o'rgatish nutqning ijtimoiy tomonini boyitadi. Salomlashish, xayrlashish, rahmat aytish, kechirim so'rash, ruxsat so'rash, tabriklash, hamdardlik bildirish — bularning hammasi bola hayotida zarur. Tarbiyachi har kuni bolalar bilan etiket vaziyatlarini o'ynaydi: \"Bugun salomlashishni \"Assalomu alaykum\" bilan boshlaymiz\", \"Rahmat aytaylik tarbiyachiga\".",
                "Rolli o'yinlar — dialogik nutqni rivojlantirishning eng samarali shakllaridan biri. Bolalar turli xil rollarda — sotuvchi va xaridor, shifokor va bemor, ona va bola, mehmondor va mehmon — bo'lib gapirib o'rganadilar. Bu o'yinlar nafaqat dialogik nutqni rivojlantiradi, balki bola ijtimoiy bilim va ko'nikmalarini boyitadi, hayotga tayyorlaydi. Rolli o'yin — bog'cha hayotining markazi.",
                "Didaktik dialogli o'yinlar maxsus rejalashtirilgan vaziyatlarda olib boriladi. \"Telefon\" o'yini eng mashhuri: bolalar telefon orqali sodda dialoglar quradilar, salomlashishdan hikoyaga, xayrlashishgacha bo'lgan ketma-ketlikni saqlaydilar. \"Sayohat\" o'yini, \"Mehmonda\" o'yini, \"Maktabda birinchi kun\" o'yini ham bolalarga turli vaziyatlarda muloqot qilishni o'rgatadi.",
                "Dialogik nutqni rivojlantirishda tinglash madaniyati ham muhim. Bola nafaqat o'zi gapirishni, balki boshqalarni tinglashni, ularning so'zini bo'lmaslikni, savol berishdan oldin o'ylab olishni o'rganishi kerak. Tarbiyachi maxsus mashqlar va vaziyatlar yordamida bunday madaniyatni shakllantiradi: \"Avval o'rtog'imning so'zini tinglaymiz, keyin javob beramiz\", \"Hammamiz bittadan navbat bilan gapiramiz\". Bu — dialogning chinakam san'ati.",
            ],
        ),
        (
            "Monologik nutq turlari va ularni o'rgatish bosqichlari",
            [
                "Monologik nutq dialogik nutqdan keyin shakllanadi va u ancha murakkabroqdir. Monolog — bir kishining boshqalar oldida batafsil, mustaqil va izchil tarzda fikrlarini bayon qilishidir. Monologik nutq oldindan rejalashtirishni, mavzu rivojlantirishni, til vositalarini ongli tanlashni va tinglovchi e'tiborini ushlab turishni talab qiladi. Bu — bolaning yuqori darajadagi nutqiy va aqliy taraqqiyot ko'rsatkichidir.",
                "Monologik nutqning asosiy turlari quyidagilar: 1) tasvirlash (predmet, hayvon, manzara haqida — ularning xususiyatlarini ko'rsatish); 2) hikoya (voqea, jarayon, harakat haqida — vaqt ketma-ketligida bayon); 3) mulohaza (sabab-natija, ahamiyati haqida — fikrning rivoji va xulosasi). Bog'cha yoshida birinchi ikkitasi asosiy o'rin tutadi, mulohaza maktab davrida yetuklashadi.",
                "Tasvirlash hikoyasi — predmet, hayvon, manzara, surat haqida ularning xususiyatlari, qismlari, vazifasi, ahamiyatini bayon etishdir. Tasvirlashda statik holat tasvirlanadi: \"Bu olma. U dumaloq, qizil rangda. Olma shirin va mazali. Olmada ko'p vitaminlar bor. Biz olmani sevamiz\". Tasvirlashning sxemasi (model) bolaga taqdim etiladi va u shu asosda mustaqil tasvirlay oladi.",
                "Hikoya — voqealar tartibida bayon qilingan bog'liq matn. \"Boshlanma — rivoj — yakun\" sxemasiga ega. Hikoyada vaqt ketma-ketligi, sabab-natija aloqalari, personajlar harakatlari va ularning natijalari namoyon bo'ladi. \"Bir kuni Karim bog'chaga keldi. U yangi o'yinchoq olib kelgan edi. Bolalar uni juda yaxshi qabul qilishdi va birga o'ynashdi. Karim juda xursand bo'ldi va uyga kayfiyat bilan qaytdi\".",
                "Monologik nutqni o'rgatish bosqichlari quyidagicha tashkil qilinadi: 1) tarbiyachining namuna hikoyasi (bola tinglaydi va tushunadi); 2) namuna asosida birgalikda hikoya (tarbiyachi boshlaydi, bola davom ettiradi); 3) reja yoki sxema bo'yicha hikoya (bola yordamchi vositalardan foydalanadi); 4) mustaqil hikoya (bola hech qanday yordamsiz tuzadi). Har bir bosqich o'zlashtirilgan keyin keyingisiga o'tiladi.",
                "Qayta hikoya qilish — monologik nutqni rivojlantirishning asosiy turlaridan biri. Asar tanlanishi muhim: u qiziq, hajmi mos, til sodda va boy, axloqiy mazmunli bo'lishi shart. Birinchi marta o'qib bergandan keyin asar bola xotirasida saqlanmaydi, shu sababli takror o'qish va savollar bilan ishlash zarur. Asar mazmunini bola yaxshi tushunganidan keyingina qayta hikoya qilishga o'tiladi.",
                "Ijodiy hikoya — eng yuqori va eng murakkab tur. Bola hech qanday tayyor matn asosida emas, balki o'zining xayoli, tasavvuri yordamida hikoya tuzadi. Ijodiy hikoyalarning xilma-xil shakllari mavjud: berilgan boshlanmadan davom ettirish; berilgan oxirdan boshlash; berilgan personajlar bilan voqea; berilgan mavzu bo'yicha hikoya. Ijodiy hikoyalar bola fantaziyasini, ijodiy fikrlashni va tilini birga rivojlantiradi.",
            ],
        ),
        (
            "Surat, predmet va tabiat asosida hikoya tuzish metodikasi",
            [
                "Surat asosida hikoya tuzish — bog'cha pedagogikasining eng an'anaviy va samarali ish turlaridan biridir. Suratlar har xil bo'lishi mumkin: predmet suratlari (alohida narsalar tasvirlangan); syujet suratlari (kichik voqea); seriyali suratlar (voqealar tartibida tasvirlangan); manzara suratlari (tabiat ko'rinishi); muammoli suratlar (qiziqarli vaziyatda). Har bir tur o'z metodikasini talab qiladi.",
                "Predmet suratlari bilan ishlash sodda tasvirlash mashqlariga aylantiriladi. Bola surat asosida narsa nomini, rangini, shaklini, qismlarini, vazifasini bayon qiladi. \"Bu — qo'g'irchoq. U katta, sariq sochli, ko'k ko'zli. U pushti ko'ylak kiygan. Qo'g'irchoq juda chiroyli. Bolalar uni yaxshi ko'radi\". Bunday hikoyalar kichik va o'rta guruhlarda keng qo'llaniladi.",
                "Syujet suratlari bilan ishlash — bog'cha katta guruhda asosiy. Surat batafsil ko'rib chiqiladi, savol-javob orqali uning mazmuni anglanadi. Asosiy savollar: \"Suratda kim tasvirlangan?\", \"Ular nima qilyapti?\", \"Qaerda?\", \"Qanday?\", \"Nima uchun?\". Keyin bolalar yondashib hikoya tuzadilar. Surat o'rtasidagi mantiqiy bog'liqliklar va sabab-natija aloqalari aniqlanadi.",
                "Seriyali suratlar (3-4 ta) yordamida voqealar ketma-ketligi bo'yicha hikoya tuziladi. Bu — bolaning vaqt va sababiy fikrlashini rivojlantiradigan zo'r mashq. Suratlar tartibi avval aniqlanadi (\"Avval nima sodir bo'ldi? Keyin nima? Oxirida nima bo'ldi?\"), keyin har bir surat uchun gap tuziladi va nihoyat barchasi bog'lanib bir hikoyaga aylanadi. Tipik mavzular: \"Bola qor odam yasaydi\", \"Itcha jo'nadi\", \"Olma yetishtirish\".",
                "Predmet asosida hikoya tuzish — real, ushlash mumkin bo'lgan predmet bilan ishlash. Bola predmetni ko'radi, ushlaydi, paypaslaydi, ta'mini totadi (agar mumkin bo'lsa) va u haqida hikoya quradi. Bunday ish bolaning sezgi va idroki bilan nutqini birlashtirib rivojlantiradi. Mavzular cheksiz: o'yinchoq, oziq-ovqat mahsulotlari, kiyim-kechak, gul, mevalar, sabzavotlar va boshqalar.",
                "Tabiat asosida hikoya — sayrlar va ekskursiyalar paytida olib boriladi. Bolalar tabiatdagi narsa va hodisalarni kuzatadilar — fasllar, ob-havo, o'simliklar, hayvonlar, qushlar — va keyin ular haqida hikoya quradilar. Bu mashqlar bolada nafaqat nutq, balki ekologik ong, tabiatga muhabbat ham shakllantiradi. \"Kuzning belgilari\", \"Bahorda nima sodir bo'ladi\", \"Qishki o'rmonda\" kabi mavzular boy va xilma-xil materiallar beradi.",
                "Tajriba va xotira asosida hikoya tuzish — bola o'z hayotidan voqealar haqida gapirishi. Mavzular: \"Sayohat haqida\", \"Bayramda\", \"Tug'ilgan kunda\", \"Mehmonda\", \"Birinchi marta velosiped minganimda\". Tarbiyachi savollar bilan bolaga yordam beradi va uning hikoyasini boshqaradi: \"Qachon bo'lgan edi?\", \"Qayerda?\", \"Kim bilan?\", \"Nima qildingiz?\", \"Eng yaxshi nima edi?\". Bunday hikoyalar bolaga o'ziga ishonchni va o'z hayotini qadrlashni o'rgatadi.",
            ],
        ),
        (
            "Ravon nutqni rivojlantirishda tarbiyachining roli va xatolarni bartaraf etish",
            [
                "Ravon nutqni rivojlantirishda tarbiyachining roli markaziy va belgilovchi xarakterga ega. Tarbiyachining o'zi — bola uchun nutq namunasi. Uning gapirish uslubi, ohangi, til boyligi, fikrlarni izchil bayon qilish ko'nikmasi bola tomonidan o'zlashtiriladi. Shu sababli tarbiyachi o'zining nutqi ustida doimiy ish olib borishi, uni mukammallashtirishi shart. \"Tarbiyachi qanday gapirsa, bola ham shunday gapiradi\" — bu eski va to'g'ri haqiqat.",
                "Tarbiyachining nutqiga qo'yiladigan talablar quyidagilar: 1) talaffuz aniqligi — barcha tovushlar to'g'ri talaffuz qilinishi; 2) lug'at boyligi — turli xil so'zlar va ifodalar; 3) grammatik to'g'rilik — qoidalarga muvofiqlik; 4) ifodalilik — ohang, urg'u, pauzalarning to'g'ri qo'llanilishi; 5) sokin va yumshoq ovoz; 6) bola yoshiga moslik — tushunarli, sodda, lekin tasvirli til. Bu sifatlar tarbiyachining professional kompetentsiyasining asosiy qismidir.",
                "Tarbiyachi bolalar nutqini doimiy kuzatib boradi va xatolarni qayd etadi. Eng ko'p uchraydigan nutq xatolari: 1) tovushlarni xato talaffuz qilish; 2) lug'at chegaralangan; 3) bir xil so'zlarning takror qo'llanilishi; 4) grammatik xatolar (kelishik, son, zamon shakllari); 5) gap qurilishida xatolar; 6) ravon nutqning izchil emasligi; 7) hikoyaning to'liq emasligi. Har bir xato individual yondashuv bilan to'g'rilanadi.",
                "Xatolarni to'g'rilash usullari ehtiyotkorlik va san'at talab qiladi. Asosiy tamoyil — bolani uyaltirmaslik, jamoa oldida tanqid qilmaslik, qo'pol va qattiq tarzda tuzatmaslik. Tarbiyachi to'g'ri shaklni qaytarib, bolaga eshitish va o'zlashtirish imkonini beradi. Yana bir samarali usul — bolaning xatosini takrorlamasdan, to'g'ri shaklni o'zining nutqiga qo'shish. Bola asta-sekin to'g'ri shaklni qabul qiladi va xatoyiga qaytmaydi.",
                "Bolalar nutqida xatolarni o'rganish va tahlil qilish — pedagogik tahlilning muhim qismi. Tarbiyachi har bir bolaning nutq xususiyatlarini bilishi va kerakli yo'nalishda ish olib borishi shart. Ba'zi bolalar lug'at jihatidan zaif, boshqalari grammatik xatolar qiladi, uchinchilarining ravon nutqi shakllanmagan. Har bir bola individual rivojlanish dasturiga muhtoj.",
                "Maxsus pedagogik yordam talab qiladigan bolalar bilan ishlash alohida e'tibor talab qiladi. Tovushlar bilan kuchli muammosi bo'lgan bolalar logoped bilan ishlaydi. Lug'ati zaif bolalar uchun individual mashqlar tashkil qilinadi. Ravon nutqi shakllanmagan bolalar uchun maxsus surat va o'yin to'plamlari tayyorlanadi. Tarbiyachi bunday bolalarga qo'shimcha vaqt va e'tibor ajratadi.",
                "Ravon nutqning rivojlanishida ota-onalar bilan hamkorlik muhim ahamiyatga ega. Tarbiyachi ota-onalarga uy sharoitida olib boriladigan ishlar bo'yicha aniq tavsiyalar beradi: bola bilan ko'p suhbatlashish; uning savollariga sabr bilan javob berish; bayramlar, sayohatlar, oilaviy voqealar haqida bola hikoyasini eshitish; har kuni kitob o'qish. Bunday hamkorlik bog'cha ishini sezilarli darajada to'ldiradi va kuchaytiradi. Faqat bog'cha va oila birgalikda ishlaganda bola haqiqiy yutuqlarga erisha oladi.",
            ],
        ),
    ],
    "refs": COMMON_REFS,
}
