# -*- coding: utf-8 -*-
from ._refs import COMMON_REFS

topic = {
    "num": 4,
    "title": "Maktabgacha ta'lim tashkilotlarida o'rta guruh bolalarining nutqini o'stirish metodlari va vositalari",
    "reja": [
        "O'rta guruh bolalarining yosh va nutqiy xususiyatlari.",
        "O'rta guruhda lug'atni boyitish ishlarining mazmuni va metodlari.",
        "Grammatik tuzilishni o'zlashtirish va tovush madaniyatini tarbiyalash.",
        "Ravon nutqni rivojlantirish: dialog va sodda monolog mashqlari.",
        "Mashg'ulot va kundalik faoliyatdagi vositalar, oila bilan hamkorlik.",
    ],
    "sections": [
        (
            "O'rta guruh bolalarining yosh va nutqiy xususiyatlari",
            [
                "O'rta guruh bolalari (4-5 yosh) — bog'cha yoshining \"oltin davri\" deb ataladigan, jismoniy va aqliy taraqqiyot eng intensiv kechadigan davrida bo'ladi. Bu yoshda bola allaqachon faol so'zlovchi, atrofdagi olamga keng qiziqish bilan qaraydigan, savollar berib bilim oluvchi shaxsdir. Tarbiyachi bu yoshning psixologik va pedagogik xususiyatlarini chuqur bilishi va o'z faoliyatini ularga moslashtirishi shart.",
                "O'rta yoshdagi bolaning lug'at boyligi 1500-2500 so'zga yetadi. U narsa va hodisalarning nomlari bilan birga, ularning xususiyatlari, harakat-funksiyalari haqida ham ma'lumotga ega bo'ladi. Bola sinonim va antonim tushunchasini hali nazariy bilmasa-da, amaliy ravishda \"katta-kichik\", \"baland-past\", \"oq-qora\", \"shirin-achchiq\" kabi qarama-qarshi tushunchalarni qo'llay oladi. Lug'at sifati nafaqat miqdor, balki to'g'rilik va aniqlik bo'yicha ham yaxshilanadi.",
                "Tovushlarni talaffuz qilishda 4-5 yoshdagi bola sezilarli yutuqlarga erishadi. \"R\" tovushini ko'pchilik bolalar bu yoshda muvaffaqiyatli o'zlashtiradilar. \"Sh\", \"j\", \"ch\" tovushlari ham asta-sekin to'g'ri talaffuz qilinadi. Lekin bolaning 30%-40% gacha qismida hali ham ayrim tovushlarda kamchiliklar saqlanib qoladi. Tarbiyachi bunday bolalar bilan maxsus ish olib boradi va kerak bo'lganda logoped maslahatini oladi.",
                "Grammatik tuzilish ham sezilarli darajada rivojlanadi. Bola endi 5-6 so'zli, hatto qo'shma gaplar tuza oladi. \"Men bog'chaga keldim, lekin akam uyda qoldi\", \"Bobom kelganda men juda xursand bo'ldim\" kabi murakkab konstruktsiyalar paydo bo'ladi. Lekin grammatik xatolar ham hali uchraydi: ot va sifatlarning kelishik shakllari, fe'l zamonlari, bog'lovchilarning qo'llanilishida bola ba'zan adashadi. Bu yoshga xos hodisa.",
                "Dialogik nutq jihatidan o'rta guruh bolasi sezilarli darajada rivojlanadi. U faqat savollarga javob berish bilan chegaralanmaydi, balki o'zi savollar so'raydi, bahslashishni boshlaydi, fikrini muhokama qiladi. Bog'cha bolalari bir-biri bilan suhbatlasha boshlaydi, oddiy birgalikdagi syujetli o'yinlarni tashkil eta oladilar. Bu — sotsialashuv jarayonining muhim bosqichi va tarbiyachi uni qo'llab-quvvatlashi kerak.",
                "Monologik nutqning kurtaklari ko'rinadi: bola surat asosida 3-5 jumlali sodda hikoya tuza oladi, kichik ertaklarni qayta aytib bera oladi (tarbiyachining yordami bilan), o'zining boshidan kechirgan voqealari haqida hikoya qiladi (\"Bugun bog'chada nimalar qildim\", \"Dam olishda qayerga bordik\"). Bu monologik nutq hali yetuk emas, lekin uning shakllanishi boshlangan va tarbiyachi uni rivojlantirishga e'tibor qaratishi kerak.",
                "Bu yoshdagi bolaning fikrlashi ko'rgazmali-obrazli xarakterga ega. Bola hali abstrakt tushunchalarni qabul qila olmaydi, lekin u hodisalarni umumlashtira biladi, oddiy mantiqiy bog'liqliklarni anglaydi (sabab-natija, qism-butun, vaqt ketma-ketligi). Bu psixologik xususiyat nutq vazifalarini qo'yishda hisobga olinadi: tarbiyachi bolaga aniq, hayotiy, ko'rinarli mavzular taqdim etadi. Mavhumlik o'rta guruhda hali bola uchun begona.",
            ],
        ),
        (
            "O'rta guruhda lug'atni boyitish ishlarining mazmuni va metodlari",
            [
                "O'rta guruhda lug'atni boyitish ishi yangi bosqichga ko'tariladi. Endi tarbiyachining vazifasi nafaqat narsalar nomini o'rgatish, balki ularning xususiyatlari, sifatlari, vazifalari, tasniflarini ham bolaga taqdim etishdan iborat. Lug'at \"lug'at-tushuncha\" darajasiga o'tadi: bola so'z orqasida muayyan tushunchani anglay boshlaydi va uni boshqa tushunchalar bilan bog'lay oladi.",
                "Lug'at ishida quyidagi mavzular asosiy o'rin tutadi: oila va qarindoshlar (otam, onam, bobom, buvim, akam, opam, amakim, ammam, holam, tog'am); kiyim-kechak (ko'ylak, shim, etik, kepka, paypoq); oziq-ovqat (non, sut, gusht, baliq, sabzavotlar, mevalar nomlari); transport vositalari; kasb-hunarlar; uy hayvonlari va yovvoyi hayvonlar; qushlar; o'simliklar; tabiat hodisalari va fasllar; bayramlar va milliy odatlar.",
                "Predmetlarning xususiyatlarini o'rgatish — lug'atni sifat jihatdan boyitishning muhim tomoni. Bolalar olmaning shaklini (dumaloq), rangini (qizil, sariq, yashil), ta'mini (shirin, nordon), o'lchamini (katta, kichik), qattiqligini (qattiq), pishganlik darajasini (xom, pishgan) o'rganadilar. Buning uchun real predmet bilan ishlash, uni paypaslash, ta'mini totish, hidini sezish — barchasi muhim.",
                "Sinonim va antonim so'zlar ustida ishlash o'rta guruhda boshlanadi. \"Yumshoq — qattiq\", \"katta — kichik\", \"baland — past\", \"shirin — nordon\", \"yorqin — qorong'i\" kabi qarama-qarshi tushunchalar maxsus o'yinlar va mashqlar yordamida o'rgatiladi. \"Aksini ayt!\" o'yini, suratlar bilan taqqoslash bunday vazifani hal etishda samarali. Sinonimik qatorlardan eng oddiylari — \"katta-baquvvat\", \"chiroyli-go'zal\" — ham asta-sekin kiritiladi.",
                "Lug'atni boyitish metodlari xilma-xil bo'lishi kerak. Asosiy metodlar: 1) bevosita kuzatish (real predmet bilan tanishish); 2) bilvosita kuzatish (surat va illyustratsiya bilan ishlash); 3) badiiy adabiyot bilan tanishtirish; 4) didaktik o'yinlar; 5) musobaqalar va musohabalar; 6) faoliyat bilan birga olib boriladigan tushuntirish. Har bir metod o'z o'rni va vazifasiga ega.",
                "Didaktik o'yinlar lug'at ishida muhim rol o'ynaydi. \"Magazin\" o'yini (mahsulotlarni nomlash va tasvirlash); \"Sehrli qopcha\" (paypaslab predmet topish va u haqda gapirish); \"Kim ko'p so'z aytadi?\" (mavzu bo'yicha so'zlar to'plash); \"Tasvirlash bo'yicha topish\" (tarbiyachi predmetni tasvirlaydi, bola topadi); \"Lotto\" (suratli kartochkalar bilan o'yin) — bularning hammasi bola lug'atini boyitishga yordam beradi.",
                "Lug'at ishini olib borishda alohida e'tibor talab qiladigan masala — yangi so'zlarni mustahkamlash. Bola yangi so'zni faqat bir marta eshitsa, uni o'zlashtirmaydi. Yangi so'z 4-5 marta turli xil sharoitlarda takrorlanishi kerak: avval mashg'ulotda, keyin sayrda, ovqat vaqtida, o'yin paytida. Faqat shunda bola yangi so'zni o'z faol lug'atiga kiritadi va uni mustaqil qo'llay boshlaydi. Lug'at — uzluksiz va izchil ish natijasidir.",
            ],
        ),
        (
            "Grammatik tuzilishni o'zlashtirish va tovush madaniyatini tarbiyalash",
            [
                "Grammatik tuzilishni o'zlashtirish o'rta guruhda jadal kechadi. Bu yoshda bola tilning grammatik qoidalarini nazariy emas, balki amaliy o'zlashtiradi: kattalar nutqini eshitish, taqlid qilish, faol qo'llash orqali. Tarbiyachining vazifasi — bolaga to'g'ri grammatik shakllarning namunalarini berish, uning xatolarini muloyimlik bilan to'g'rilab borish, grammatik mashqlar va o'yinlar tashkil etish.",
                "Morfologiya jihatidan o'rta guruh bolasi otning ko'plik shaklini, kelishik qo'shimchalarini (qaratqich, tushum, jo'nalish, o'rin-payt, chiqish), egalik qo'shimchalarini, sifatning oddiy va orttirma darajalarini, fe'lning hozirgi, o'tgan va kelasi zamon shakllarini, shaxs-son qo'shimchalarini o'zlashtiradi. Lekin bularning hammasi bir vaqtda emas, balki asta-sekin va izchil ravishda kiritiladi.",
                "Ko'pincha uchraydigan grammatik xatolar va ularni to'g'rilash usullari: 1) \"otam keldilar\" o'rniga \"otam keldi\" — tarbiyachi to'g'ri shaklni qaytarib aytadi; 2) \"non-non\" o'rniga \"nonlar\" — ko'plikning to'g'ri qo'shimchasini ko'rsatadi; 3) \"borgan edim\" o'rniga \"borgan edim\" yoki \"bordim\" — vaqtga muvofiq fe'l shaklini eslatadi. Hech qachon bolani uyaltirmaslik, balki to'g'ri shaklga olib kelish kerak.",
                "Sintaksis bo'yicha o'rta guruh bolasi sodda gaplardan murakkab gaplarga o'tish bosqichida bo'ladi. Tarbiyachi maxsus mashqlar va o'yinlar orqali bolada qo'shma gaplar quris ko'nikmasini shakllantiradi: \"Quyon nima qiladi va quyondan kim qo'rqadi?\", \"Bahor keldi, chunki ...\", \"Agar yomg'ir yog'sa, biz ...\". Bunday gaplar bola fikrini chuqurlashtiradi va uni kengroq ifoda etishni o'rgatadi.",
                "Tovush madaniyatini tarbiyalash o'rta guruhda eng intensiv olib boriladi. Bu yoshda bolaning artikulyatsion apparati shakllangan, lekin u hali to'liq nazoratga ega emas. Tarbiyachi bilan birgalikda bola maxsus mashqlar bajaradi: lab va til mashqlari (\"sutni shirin qildik\", \"otdek choptik\", \"go'zal jilmaymiz\"); nafas mashqlari (\"shamol esadi\", \"to'pni puflaymiz\"); ovoz mashqlari (qattiq-sekin, baland-past gapirish).",
                "Maxsus tovushlar bilan ishlash o'rta guruhning asosiy vazifasidir. Har hafta 1-2 tovush ustida ish olib boriladi. Avval bola tovushni yakka holda eshitishi va aytishi mashq qilinadi, keyin bo'g'inda, so'zda, jumlada. \"R\" tovushi uchun: \"r-r-r\", \"ra-ro-ru\", \"ravon\", \"darvoza\", \"ravon ravonda yura olar\". Bunday izchil va izlanishli ish bola tovush madaniyatini sezilarli darajada yaxshilaydi.",
                "Fonematik eshitishni rivojlantirish — tovush madaniyatining muhim qismidir. Bola turli tovushlarni bir-biridan farqlay olishi, ularni so'zda topa olishi, oddiy tovush tahlilini bajara olishi kerak. \"Qaysi tovush bilan boshlanadi?\", \"So'zda \"a\" tovushi bormi?\", \"Bir xil tovushli so'zlarni topib ber\" kabi o'yinlar bu vazifani hal etadi. Bu mashqlar bolani savod o'rgatishga ham asta-sekin tayyorlaydi.",
            ],
        ),
        (
            "Ravon nutqni rivojlantirish: dialog va sodda monolog mashqlari",
            [
                "O'rta guruhda ravon nutqni rivojlantirish — markaziy vazifalardan biri. Bu yoshda bola endi nafaqat alohida so'zlar va sodda gaplar darajasida emas, balki bog'liq, izchil matn darajasida nutq qila boshlashi kerak. Ravon nutq dialogik va monologik shakllarda namoyon bo'ladi va har ikkalasi ham maxsus ish olib borishni talab qiladi.",
                "Dialogik nutq — bola muloqot ko'nikmalarining asosini tashkil qiladi. O'rta guruhda dialogni rivojlantirish quyidagi yo'nalishlarda olib boriladi: 1) savol va javob berish madaniyati; 2) suhbatda navbat tushunchasi; 3) tinglash madaniyati — boshqalarni so'zini bo'lmay tinglash; 4) o'z fikrini bayon eta olish; 5) bahslashish va kelishish — tengdoshlar bilan kelishish ko'nikmasi. Bularning hammasi katta ahamiyatga ega.",
                "Suhbatlar — dialogik nutqni rivojlantirishning eng samarali shakllaridan biri. Tarbiyachi har kuni bolalar bilan turli mavzular bo'yicha suhbatlar tashkil etadi: \"Bugun ob-havo qanday?\", \"Onangiz qanday taom pishirgan?\", \"Eng sevgan o'yinchog'ingiz qanday?\". Suhbatlar individual, kichik guruh bilan yoki butun guruh bilan o'tkaziladi. Suhbat oddiy savollardan boshlanadi va asta-sekin chuqurlashadi.",
                "Didaktik dialogli o'yinlar dialogik nutqni rivojlantirishda muhim. \"Telefon\" o'yini (bolalar telefon orqali suhbatlashadi: birinchi salomlashish, keyin so'rash, javob berish, xayrlashish); \"Kafe\"/\"Magazin\" rolli o'yinlari (sotuvchi va xaridor o'rtasidagi suhbat); \"Shifokor\" o'yini (bemor va shifokor o'rtasidagi suhbat). Bu o'yinlarda bola turli xil ijtimoiy rollarda muloqot qilishni o'rganadi.",
                "Monologik nutqning kurtaklarini rivojlantirish o'rta guruhda boshlanadi. Asosiy turlar: 1) tasvirlash (predmet, hayvon yoki rasm haqida 3-5 jumla); 2) qayta hikoya qilish (eshitilgan ertakni qisqacha takrorlash); 3) o'z tajriba haqida hikoya (\"Bugun nima qildim\", \"Dam olishda qayerga borgan edim\"). Har bir turi maxsus mashqlar va vositalar yordamida o'rgatiladi.",
                "Tasvirlash mashqlari uchun real predmet, o'yinchoq yoki surat olinadi. Tarbiyachi avval o'zi namuna ko'rsatadi: \"Bu — qo'g'irchoq. Uning ismi Munisa. Munisa go'zal, yuzi oppoq, ko'zlari qora. U qizil ko'ylak kiygan. Munisa o'ynashni juda yaxshi ko'radi\". Keyin bola shu namuna asosida o'z tasvirlashini quradi. Asta-sekin yordam kamayadi va bola mustaqil tasvirlay oladi.",
                "Qayta hikoya qilish — bola eshitgan badiiy asarni o'z so'zlari bilan qayta aytib berishi mashqi. Bunda asosiy ish quyidagi tartibda boradi: tarbiyachi ertakni o'qiydi yoki aytib beradi; bolalar bilan suhbat o'tkaziladi (kim qatnashdi, nima bo'ldi, qanday tugadi); ertak ikkinchi marta o'qiladi; bolalar navbatma-navbat (ba'zi qismlarini) qayta aytib beradilar. Bu mashq bola xotirasini, mantiqiy fikrlashni va nutqni rivojlantiradi.",
            ],
        ),
        (
            "Mashg'ulot va kundalik faoliyatdagi vositalar, oila bilan hamkorlik",
            [
                "O'rta guruhda nutq o'stirish mashg'ulotlari haftada 2 marta o'tkaziladi, ularning davomiyligi 20 daqiqani tashkil etadi. Davomiylik kichik guruhga nisbatan 5 daqiqaga oshadi, chunki bu yoshda bolaning diqqati ko'proq vaqt bir mavzuga jamlanishi mumkin. Mashg'ulot tarkibida turli xil faoliyatlar (kuzatish, suhbat, o'yin, mashq) almashtirib turilishi shart, aks holda bola charchaydi.",
                "Mashg'ulot tuzilishi quyidagicha bo'lishi mumkin: 1) tashkiliy va kirish qismi (2-3 daqiqa) — bolalar tartibga keladi, mavzuga sozlanadilar; 2) asosiy qism (15 daqiqa) — yangi material yoki o'zlashtirilgan materialni mustahkamlash; 3) yakuniy qism (2-3 daqiqa) — natijalar, baholash, keyingi rejani bayon qilish. Har bir mashg'ulot aniq pedagogik vazifaga yo'naltirilgan bo'lishi shart.",
                "O'rta guruh bolalarining nutqini o'stirishda ko'rgazmali vositalar muhim rol o'ynaydi. Tarbiyachi turli xil ko'rgazmali materiallarni tayyorlaydi va saqlaydi: predmet va syujet suratlari katalogi (mavzular bo'yicha); didaktik o'yinlar to'plami; ko'rgazmali stol o'yinlari (lotto, domino, mozaika); flanelegraf va figuralar; qo'g'irchoq teatri; bolalar adabiyoti kitobxonasi. Hammasi joyiga tartibli qo'yilgan va kundalik foydalanish uchun qulay bo'lishi kerak.",
                "Kompyuter va multimedia vositalari ham o'rta guruhda asta-sekin kiritiladi. Lekin ularni qo'llashda ehtiyotkorlik kerak: ekran oldida o'tkaziladigan vaqt 20 daqiqadan oshmasligi, multimediadan keyin albatta jonli muloqot va muhokama o'tkazilishi shart. Multfilmlar, ta'limiy slaydlar, interaktiv o'yinlar — bularning hammasi to'g'ri va me'yorli qo'llanganda foyda keltiradi, lekin an'anaviy vositalarni almashtira olmaydi.",
                "Kundalik faoliyatning barcha rejim daqiqalari nutqni rivojlantirish uchun foydalaniladi. Ertalabki qabul vaqtida har bir bola bilan qisqa, lekin samimiy suhbat; ovqat vaqtida — taom haqida; sayrda — kuzatish; o'yin paytida — birgalikdagi muloqot; tushlikdan keyin — ertak yoki sokin suhbat; uxlashdan oldin — qisqa sokin she'r yoki qo'shiq. Bunday yondashuv nutq mashg'ulotini sun'iy ravishda ajratmaydi, balki uni hayot bilan birlashtiradi.",
                "Oila bilan hamkorlikning xilma-xil shakllari mavjud. Ota-onalar yig'ilishlari — eng an'anaviy va eng samarali shakl. Ularda nutq o'stirish bo'yicha ma'lumot beriladi, savollar muhokama qilinadi, taklif va istaklarga e'tibor beriladi. Ochiq darslar — ota-onalar bog'cha mashg'ulotini bevosita ko'rishlari, bu ularda ko'p savollarni hal etadi va ishonch uyg'otadi.",
                "Oila bilan ishlashda zamonaviy texnologiyalardan foydalanish bugungi kun talabidir. Ko'pchilik ota-onalar Telegram va WhatsApp messenjeri orqali tez aloqada bo'ladilar. Tarbiyachi guruh chati orqali kundalik xabarlarni yuboradi, fotosuratlar yuboradi, foydali maslahatlar va bola bilan uyda olib boriladigan oddiy mashqlarni ulashadi. Bunday hamkorlik bog'cha va oila o'rtasidagi to'siqlarni yo'q qiladi va bola tarbiyasini umumiy ishga aylantiradi. Faqat shu yo'l bilan haqiqiy natijaga erishish mumkin.",
            ],
        ),
    ],
    "refs": COMMON_REFS,
}
