# -*- coding: utf-8 -*-
from ._refs import COMMON_REFS

topic = {
    "num": 2,
    "title": "Bolalarni nutqini o'stirish fanining maqsadi va vazifasi",
    "reja": [
        "Bolalar nutqini o'stirish fanining umumiy maqsadi.",
        "Lug'at boyitish va grammatik tuzilishni o'rgatish vazifalari.",
        "Tovush madaniyatini tarbiyalash va ravon nutqni rivojlantirish vazifalari.",
        "Bolalar nutqini o'stirishning tarbiyaviy va ma'rifiy vazifalari.",
        "Yosh xususiyatlariga muvofiq vazifalar va Davlat dasturi talablari.",
    ],
    "sections": [
        (
            "Bolalar nutqini o'stirish fanining umumiy maqsadi",
            [
                "Bolalar nutqini o'stirish fanining bosh maqsadi — har bir bolada ona tilini erkin, to'g'ri, ifodali va ongli ravishda qo'llay olish ko'nikmasini shakllantirish, uni mukammal so'zlashish madaniyatiga ega, har tomonlama rivojlangan shaxs sifatida tarbiyalashdir. Bu maqsad mamlakatimiz pedagogikasining umumiy maqsadi — yetuk, ma'rifatli va ma'naviyatli barkamol avlodni voyaga yetkazish vazifasiga uzviy ravishda bog'liqdir. Demak, nutqni o'stirish — bu shunchaki tilning texnik tomonini o'rgatish emas, balki shaxsni shakllantirish jarayonidir.",
                "Maqsadning ijtimoiy ahamiyati nihoyatda kattadir. Zamonaviy axborot jamiyatida nutq qobiliyatining ahamiyati avvalgi davrlardagidan ham oshib bormoqda. Bola kelajakda muvaffaqiyatli o'qishi, ijtimoiy hayotda o'rin egallashi, kasb-hunar tanlashi, oilada va jamoada to'g'ri munosabat o'rnatishi uchun rivojlangan nutqqa ega bo'lishi shart. Aynan bog'cha yoshida qo'yilgan poydevor uning butun keyingi hayoti uchun mustahkam asos bo'lib xizmat qiladi.",
                "Bola nutqini o'stirishning tarbiyaviy maqsadi shaxsning ma'naviy-axloqiy shakllanishi bilan bog'liq. Til orqali bola umuminsoniy va milliy qadriyatlarni o'zlashtiradi, vatanparvarlik, mehnatsevarlik, halollik, mehribon va kamtarlik kabi axloqiy fazilatlarni o'ziga singdiradi. \"Til kishining ko'zgusi\", \"so'z — fikrning libosi\" degan xalq donolik so'zlari ana shu haqiqatni ifodalaydi. Bog'cha tarbiyachisi bolaga so'zni nafaqat texnik tomondan, balki uning ma'naviy yukini ham tushuntirib o'rgatadi.",
                "Maqsadning ta'limiy yo'nalishi bolada bilim olish, tahlil qilish, mantiqiy fikrlash, taqqoslash, umumlashtirish ko'nikmalarini shakllantirishni o'z ichiga oladi. Nutq orqali bola atrof-olamni biladi, narsa va hodisalar haqida tasavvurga ega bo'ladi, ularning xususiyatlari, sabab-natija aloqalarini aniqlashga o'rganadi. Demak, nutqni o'stirish — bu butun aqliy taraqqiyotni ta'minlovchi vositadir.",
                "Maqsad amalga oshishi uchun nafaqat bog'cha, balki oila va keng jamoatchilik ham mas'uliyatli bo'lishi shart. Tarbiyachi va ota-onalar o'rtasida hamkorlik, bog'cha va maktabning izchilligi, ommaviy axborot vositalari va madaniyat muassasalarining hissasi muhim ahamiyatga ega. Hech bir muassasa yakka holda bola nutqini to'liq rivojlantira olmaydi — bu kompleks va keng qamrovli ish.",
                "O'zbekiston Respublikasida \"Maktabgacha ta'lim va tarbiya to'g'risida\"gi qonun, \"Ilk qadam\" Davlat o'quv dasturi va boshqa me'yoriy hujjatlar bola nutqini o'stirishning umumiy maqsad va vazifalarini me'yorlashtiradi. Bu hujjatlarda har bir yosh guruhi uchun aniq talablar, kutiladigan natijalar va baholash mezonlari belgilangan. Tarbiyachi shu hujjatlarda belgilangan talablardan kelib chiqib, o'z faoliyatini ijodiy va izchil tashkil etadi.",
                "Maqsad ko'p qirrali bo'lib, uni amalga oshirish uchun tarbiyachi bir qator aniq vazifalarni hal qilib boradi. Pedagogika fanida bu vazifalarni shartli ravishda nutqning to'rt asosiy yo'nalishi bo'yicha guruhlarga ajratiladi: lug'at, grammatika, tovush madaniyati va ravon nutq. Bu vazifalarning har biri muhim ahamiyatga ega va o'zaro chambarchas bog'liq holda hal etiladi. Bir tomonni rivojlantirish boshqa tomonlarning rivojiga ham ta'sir ko'rsatadi.",
            ],
        ),
        (
            "Lug'at boyitish va grammatik tuzilishni o'rgatish vazifalari",
            [
                "Lug'at boyitish vazifasi — bolaning faol va passiv lug'at boyligini muntazam ravishda kengaytirib borish, uni hayotining barcha sohalariga oid kerakli so'zlar bilan ta'minlash. Bog'cha yoshidagi bola odatda yiliga 1500-2000 ga yaqin yangi so'zni o'zlashtiradi. Bog'cha tugagunga qadar bolaning faol lug'ati 3000-4000 so'zga yetadi. Bu raqamlar tasodifiy emas, balki maxsus va izchil ish natijasidir.",
                "Lug'at boyitishda quyidagi yo'nalishlarda ish olib boriladi: birinchidan, narsa va hodisalarni nomlovchi otlar (idishlar, kiyim-kechak, mebellar, hayvonlar, o'simliklar, oziq-ovqatlar, kasb va hunarlar nomlari); ikkinchidan, harakatni bildiruvchi fe'llar; uchinchidan, sifat va xususiyatlarni ifodalovchi sifatlar; to'rtinchidan, son, ravish, olmosh va boshqa so'z turkumlari. Har bir so'z bola uchun tushunarli, hayotiy va mazmundor bo'lishi shart.",
                "Lug'at sifati ham juda muhim. Tarbiyachi nafaqat so'zlar miqdorini ko'paytirish, balki bolaga so'zning aniq ma'nosini, uning grammatik xususiyatlarini, qayerda va qanday qo'llanilishini, sinonim va antonim variantlarini o'rgatishi kerak. Masalan, \"katta\" so'zining \"kichik\" antonimi va \"baquvvat\", \"keng\" sinonimlari bilan birga taqdim etiladi. Shu yo'l bilan bola so'zni mustaqil va to'g'ri qo'llay oladi.",
                "Grammatik tuzilishni o'rgatish vazifasi — bolaga ona tilining qonuniyatlariga muvofiq so'zlarni o'zgartirish, ularni o'zaro to'g'ri bog'lash va ulardan gap tuzish ko'nikmasini shakllantirish. Bog'cha yoshidagi bola grammatik qoidalarni nazariy o'rganmaydi, lekin amaliy ravishda — kattalar nutqini eshitish, taqlid qilish, faol foydalanish orqali ularni o'zlashtiradi. Pedagog bolaning xato ishlatgan grammatik shakllarini muloyim, samimiy ravishda to'g'rilab borishi shart.",
                "Morfologik tomonidan bola otning ko'plik shaklini, kelishik qo'shimchalarini, fe'lning zamonlari va shaxs-son shakllarini, sifat darajalarini o'rganadi. Sintaktik tomondan esa sodda gaplardan murakkab gaplarga, qo'shma gaplarga o'tib boradi. Bog'chaning kichik guruhlarida 2-3 so'zli sodda gaplar yetarli bo'lsa, katta guruhda bola murakkab birikmali, payt va sabab ergash gapli gaplarni qura oladigan bo'lishi kerak.",
                "Bolalarda uchraydigan grammatik xatolarni tarbiyachi diqqat bilan tahlil qilishi va to'g'rilash usullarini tanlashi lozim. Masalan, \"otam keldi-lar\" o'rniga \"otam keldilar\" yoki \"otam keldi\", \"men bordim qildim\" kabi xatolarni jamoatchilik oldida emas, balki yakkama-yakka, samimiy munosabat doirasida tuzatish maqsadga muvofiqdir. Tarbiyachi to'g'ri shaklni qaytarib aytib, bolaga uni eshitishi va o'zlashtirishi imkonini yaratadi.",
                "Lug'at va grammatik vazifalarni hal etishning samarali metodlari quyidagilar: predmetlarni kuzatish, suratlar bilan ishlash, didaktik o'yinlar, tabiat bilan tanishtirish ekskursiyalari, badiiy adabiyot o'qish, qo'shiqlar va she'rlar yodlash, sahna ko'rinishlari va dramalashtirish. Eng muhimi — bola so'zni o'zining real faoliyatida, jonli muloqotda qo'llay olishidir. Faqat \"lug'atda\" qolgan so'z hech qanday ahamiyatga ega emas.",
            ],
        ),
        (
            "Tovush madaniyatini tarbiyalash va ravon nutqni rivojlantirish vazifalari",
            [
                "Nutq tovush madaniyatini tarbiyalash — bu nutqning aniq, ifodali, ravon, ohangli va orfoepik me'yorlarga muvofiq bo'lishini ta'minlashdir. Bu vazifa o'z ichiga bir qator komponentlarni oladi: barcha tovushlarni to'g'ri talaffuz qilish; nutqning tezligi, balandligi, ohangini boshqarish; nafas olishni to'g'ri tashkil etish; pauza va urg'uni to'g'ri qo'yish; nutq ifodaliligini rivojlantirish. Bularning hammasi bolada uzoq va sabrli ish natijasida shakllanadi.",
                "Tovushlarni to'g'ri talaffuz qilish ustida ishlash erta yoshdan boshlanadi. Birinchidan, fonematik eshitish — bola turli tovushlarni bir-biridan farqlay olishi taminlanadi. Ikkinchidan, artikulyatsion mashqlar (til, lab, jag' uchun) bajariladi. Uchinchidan, har bir tovushni alohida-alohida (avval o'rganishi qiyin bo'lganlarini) o'rgatadi. Maxsus muammoli tovushlar — [r], [l], [s], [sh], [ch], [j], [z] — uchun maxsus mashqlar tashkil etiladi.",
                "Nutqning ohangdorligi va ifodaliligini rivojlantirish ham muhim vazifadir. Bola gapni bir xil pastlik-balandlikda emas, balki mazmunga muvofiq turlicha ohanglarda aytishni o'rganishi kerak. Soroq, undov, hikoya gaplarining ohanglari turli xildir. She'rlarni yodlash, ertaklarni rolma-rol o'qish, sahnalashtirish bu vazifani hal etishning samarali yo'llaridir. Ifodali nutq bola his-tuyg'ularini boshqalarga yetkazishga yordam beradi.",
                "Ravon nutqni rivojlantirish vazifasi — bola fikrlarini izchil, mantiqiy va to'liq bayon eta olishi ko'nikmasini shakllantirishdir. Ravon nutq ikki shaklda namoyon bo'ladi: dialogik (ikki yoki undan ortiq kishilar o'rtasidagi suhbat) va monologik (bir kishining batafsil bayoni). Ikki shakl ham bola hayotida zarur va har biri o'z ish usullarini talab qiladi. Tarbiyachi har ikki shaklni rivojlantirish uchun maxsus mashg'ulotlar tashkil etadi.",
                "Dialogik nutqni rivojlantirishda kundalik muloqot, savol-javob, suhbat, didaktik o'yinlar muhim rol o'ynaydi. Tarbiyachi bolalarga turli vaziyatlarda muloqot qilishni — salomlashish, xayrlashish, ruxsat so'rash, rahmat aytish, kechirim so'rash kabi etiket shakllarini o'rgatadi. Shuningdek, jamoaviy suhbatlar (\"Bugun nima qilib yurdik?\", \"Bahor haqida nima bilamiz?\") orqali bolalarda fikr almashish ko'nikmasi shakllantiriladi.",
                "Monologik nutqni rivojlantirish — bog'chaning katta guruhlarida intensiv olib boriladigan ish. Bunda bola tasvirlash, hikoya qilish, qayta hikoya qilish, ijodiy hikoya tuzish kabi monologik shakllarni o'zlashtiradi. Surat asosida hikoya, predmet asosida tasvirlash, tabiat hodisasi haqida hikoya, badiiy asarni qayta aytib berish — bularning hammasi monologik nutqni boyituvchi mashqlar hisoblanadi. Bu ko'nikma keyinchalik maktabda muhim ahamiyatga ega bo'ladi.",
                "Tovush madaniyati va ravon nutq vazifalarini muvaffaqiyatli hal etish uchun tarbiyachining o'zi mukammal nutqqa ega bo'lishi shart. Bola tarbiyachining nutqiga taqlid qilib, undan o'rganadi. Pedagogning ovozi yumshoq, sokin, ohangdor; talaffuzi aniq; lug'ati boy va madaniyatli bo'lishi kerak. \"Tarbiyachining nutqi — bolaning birinchi darsligidir\" degan ifoda bekorga aytilmagan. Pedagogning shaxsi va nutqi bola uchun namuna va o'rgatuvchidir.",
            ],
        ),
        (
            "Bolalar nutqini o'stirishning tarbiyaviy va ma'rifiy vazifalari",
            [
                "Nutqni o'stirish vazifalari faqat \"texnik\" tomondan emas, balki tarbiyaviy va ma'rifiy yo'nalishda ham qarab chiqilishi kerak. Tilni o'rgatish — bu bir vaqtning o'zida bolada axloqiy fazilatlar, milliy g'urur, vatanparvarlik, mehribonlik, halollik, mehnatsevarlik, ota-onaga hurmat kabi qadriyatlarni shakllantirish vositasidir. Aynan til orqali bola o'z xalqining madaniyati, an'analari va ma'naviyati bilan tanishadi.",
                "Vatanparvarlik tarbiyasi — bola nutqini o'stirish jarayonining ajralmas qismidir. Bola O'zbekistonimiz haqida hikoyalar tinglash, vatan haqida she'rlar yodlash, milliy bayramlar haqida bilim olish orqali Vatanga muhabbat his-tuyg'usini shakllantiradi. Tarbiyachi bolalarga bayroq, gerb, madhiya, milliy timsollar haqida tushunarli tarzda hikoya qiladi va ularning ma'nosini ochib beradi. Vatanga muhabbat — abstrakt tushuncha emas, balki uni \"sevishni o'rganish\" jarayonidir.",
                "Milliy qadriyatlar va madaniyatga hurmat tarbiyasi nutq o'stirish ishida ustuvor o'rin tutadi. Xalq og'zaki ijodi — ertaklar, maqollar, matallar, topishmoqlar, xalq qo'shiqlari — bolaning nutqini boyitish bilan birga, uning milliy ongini ham shakllantiradi. \"Yaxshi so'z — joningga payvand\", \"Bilimli kishi — quyoshday yorug'\" kabi maqollar bolaning lug'atiga kirib, hayotiy mavqega aylanadi.",
                "Axloqiy tarbiya — bola so'zning kuchini, ta'sirini, mas'uliyatini anglashida ifodalanadi. \"Yaxshi so'z bilan ilonni inidan chiqarish mumkin\", \"Tilning haqi — qulning haqi\" degan xalq donishmandligi bolaga so'z madaniyatining ahamiyatini chuqur tushuntirib beradi. Tarbiyachi bolalarni samimiy salomlashishga, rahmat aytishga, kechirim so'rashga, xushmuomalalikka o'rgatadi. Bularning barchasi nutq orqali amalga oshadi.",
                "Mehnatsevarlik va kasb-hunarga hurmat tarbiyasi ham nutq mashg'ulotlari orqali olib boriladi. Bolalarga turli kasblar — dehqon, novvoy, shifokor, o'qituvchi, muhandis, fermer, ishchi, savdogar haqida hikoyalar aytiladi, bu kasblarning ahamiyati tushuntiriladi. Bolalar ota-onalarining kasblari haqida hikoya qilishadi, ular bilan g'ururlanishni o'rganadilar. Buning natijasida bola halol mehnatga, mehnat odamlarini hurmat qilishga o'rganadi.",
                "Estetik tarbiya — bolaning go'zallikni his etish va sevish qobiliyatini shakllantirish — nutqni o'stirishning yana bir muhim yo'nalishidir. Badiiy adabiyot bilan tanishish, she'rlar yodlash, qo'shiqlar kuylash, sahna ko'rinishlarini tomosha qilish bola ruhini boyitadi va estetik did shakllanishiga zamin yaratadi. Tabiatga ekskursiya, rasmlar bilan ishlash, badiiy faoliyat — bularning hammasi nutq bilan birgalikda go'zallik tushunchasini shakllantiradi.",
                "Ekologik tarbiya bilan nutqni o'stirishning aloqasi ham juda muhimdir. Bog'cha bolalari tabiat haqida — fasllar, o'simliklar, hayvonlar, qushlar, daryolar va tog'lar haqida ma'lumot olishadi va shu bilan birga ona zaminga muhabbatni, atrof-muhitni asrash hissini his qilishadi. Tabiat bog'cha mashg'ulotlarining mavzusiga aylanganda, bolaning lug'ati boyiydi va u ekologik onggi bilan rivojlanadi. Hozirgi davrda bu masala alohida dolzarblik kasb etmoqda.",
            ],
        ),
        (
            "Yosh xususiyatlariga muvofiq vazifalar va Davlat dasturi talablari",
            [
                "Bog'cha yoshidagi bolalar nutqini o'stirishda yosh xususiyatlarini hisobga olish — eng muhim pedagogik tamoyillardan biridir. Har bir yosh guruhi (kichik, o'rta, katta, maktabga tayyorlov) o'ziga xos rivojlanish dinamikasiga, qabul qilish imkoniyatlariga va vazifalarining tabiatiga ega. Bola yoshiga mos kelmagan vazifa qo'yish ham, juda osonlashtirilgan vazifa berib qo'yish ham kutilgan natijani bermaydi.",
                "Erta yosh (1-3 yosh) bolalari uchun asosiy vazifalar: ona tilini eshitish va tushunish ko'nikmalarini shakllantirish; faol va passiv lug'atni rivojlantirish; sodda 2-3 so'zli gaplarni qura olishni o'rgatish; oddiy savollarga javob bera olish; ertak va qo'shiqlarni tinglashga ehtiyoj uyg'otish. Bu yoshda muloqot kattalar — ona, ota, tarbiyachi — bilan, ularning samimiy va ko'p marta takrorlanuvchi murojaatlari yordamida shakllanadi.",
                "Kichik yosh guruhlari (3-4 yosh) bolalari uchun: faol lug'atni 1500 so'zga yetkazish; 4-5 so'zli sodda gaplarni qurish; predmet va surat asosida sodda hikoya tuza bilish; she'r va qo'shiqlarni yodlash; tarbiyachi bilan oddiy dialog qila olish; tovushlarni asta-sekin to'g'ri talaffuz qila boshlash. Bu yoshda o'yin va qo'g'irchoq muhim ahamiyatga ega — ular orqali bola nutq ko'nikmalarini rivojlantiradi.",
                "O'rta guruh (4-5 yosh) bolalari uchun vazifalar yanada kengayib, chuqurlashadi: lug'atni 2000 so'zga yetkazish; murakkab gaplar qurish; 4-5 jumladan iborat hikoya aytish; surat asosida bog'liq matn tuzish; deyarli barcha tovushlarni to'g'ri talaffuz qilish; turli ohanglarda gapira olish. O'rta yoshdagi bolalar tushuntirib aytishni, sabab-natija aloqalarini ifodalashni boshlaydilar.",
                "Katta guruh (5-6 yosh) bolalari uchun: lug'atni 3000-3500 so'zga yetkazish; turli xil murakkab gaplar qurish; 5-7 jumlali bog'lanishli hikoya aytish; tasvirlash, hikoya qilish, qayta hikoya qilish ko'nikmalariga ega bo'lish; o'zining xulosalarini, mulohazalarini bayon eta olish. Bu yoshda bola savod o'rgatishga tayyorlana boshlaydi: tovushlar va so'zlar tahlil qilish, gap tuzilishini tushunish.",
                "Maktabga tayyorlov guruhi (6-7 yosh) bolalari uchun vazifalar maktab talablari bilan bog'liq holda belgilanadi: lug'atni 4000 so'zdan oshirish; ravon, mantiqiy, izchil nutq qurish; ijodiy hikoyalar tuzish; o'zi mustaqil mavzu tanlay olish; she'r, ertak, hikoyalar haqida xulosa chiqara olish; savod o'rgatishga to'liq tayyor bo'lish — tovushlarni bilish, bo'g'inga ajratish, oddiy so'zlarni o'qish va yozish.",
                "\"Ilk qadam\" Davlat o'quv dasturida har bir yosh guruhi uchun nutqni o'stirish bo'yicha aniq talablar va kutiladigan natijalar ko'rsatilgan. Tarbiyachi shu hujjatdan kelib chiqib, kalendar-mavzu rejasini tuzadi, har kunlik mashg'ulotlarni tashkil etadi va natijalarni baholaydi. Davlat dasturi minimum talablarni belgilab beradi, tarbiyachi esa o'z ijodi va bolalar imkoniyatiga qarab uni boyitishi va kengaytirishi mumkin. Asosiy maqsad — bolaning haqiqiy taraqqiyoti, formal raqamlar emas.",
            ],
        ),
    ],
    "refs": COMMON_REFS,
}
