# -*- coding: utf-8 -*-
from ._refs import COMMON_REFS

topic = {
    "num": 11,
    "title": "Bolalar lug'atini boyitishda ta'limiy o'yinlarning ahamiyati",
    "reja": [
        "Ta'limiy o'yinning ta'limiy va tarbiyaviy ahamiyati.",
        "O'yinning bola aqliy taraqqiyotiga ta'siri.",
        "O'yinning lug'atni boyitish va faollashtirishdagi samaradorligi.",
        "O'yinning ijtimoiy-shaxsiy rivojlanishdagi ahamiyati.",
        "Ta'limiy o'yin samaradorligini oshirish shartlari.",
    ],
    "sections": [
        (
            "Ta'limiy o'yinning ta'limiy va tarbiyaviy ahamiyati",
            [
                "Ta'limiy o'yin — bog'cha pedagogikasining eng qadrli va eng samarali vositalaridan biridir. Uning ahamiyati shu darajada kattaki, ko'pgina pedagoglar o'yinni bola taraqqiyotining \"asosiy dvigateli\" deb atashadi. O'yin bola uchun tabiiy va sevimli faoliyat, shu sababli u orqali olib boriladigan ta'lim eng samarali bo'ladi. Ta'limiy o'yin ta'lim va o'yinni mohirlik bilan birlashtiradi.",
                "Ta'limiy o'yinning ta'limiy ahamiyati birinchi navbatda shundaki, bola unda bilim va ko'nikmalarni zo'riqishsiz, tabiiy ravishda o'zlashtiradi. An'anaviy mashg'ulotda bola charchashi, zerikishi mumkin, o'yinda esa u qiziqish va zavq bilan ishtirok etadi. Shu sababli o'yinda olingan bilim chuqurroq va mustahkamroq bo'ladi. \"O'ynab o'rgangan bola — o'rganganini unutmaydi\" degan haqiqat bekorga aytilmagan.",
                "Ta'limiy o'yin bilim olish jarayonini faollashtiradi. O'yinda bola passiv tinglovchi emas, balki faol ishtirokchidir. U fikrlaydi, qaror qabul qiladi, harakat qiladi, gapiradi. Faol ishtirok esa eng samarali o'rganish yo'lidir. Pedagogik psixologiya shuni isbotlaganki, inson o'zi faol qatnashgan faoliyatda olingan bilimni eng yaxshi eslab qoladi. O'yin aynan shunday faol faoliyatni ta'minlaydi.",
                "Ta'limiy o'yinning tarbiyaviy ahamiyati ham juda katta. O'yin bolada bir qator axloqiy fazilatlarni shakllantiradi: intizom (qoidalarga rioya qilish), halollik (adolatli o'ynash), sabr (navbatni kutish), hamkorlik (birgalikda o'ynash), kamtarlik (yutqazishni qabul qilish). Bularning hammasi nazariy ko'rsatmalar bilan emas, balki o'yin amaliyoti orqali tabiiy ravishda shakllanadi.",
                "O'yin bola irodasini tarbiyalaydi. O'yin qoidalariga rioya qilish uchun bola o'z istaklarini jilovlashga, navbatini kutishga, qoidaga bo'ysunishga o'rganadi. Bu — irodaviy tarbiyaning eng tabiiy yo'lidir. Boshida bola qoidalarga rioya qilishda qiynaladi, lekin asta-sekin u o'z xulqini boshqarishni o'rganadi. Iroda — kelajakda maktab va hayot uchun zaruriy fazilatdir.",
                "Ta'limiy o'yin bolada o'qishga ijobiy munosabatni shakllantiradi. O'yin orqali bilim olishni o'rgangan bola, o'rganishni quvonchli va qiziqarli jarayon deb biladi. Bunday bola maktabga ham qiziqish bilan keladi, o'qishni sevadi. Aksincha, o'qishni faqat zerikarli majburiyat deb bilgan bola maktabda qiyinchiliklarga uchraydi. Demak, o'yin bola o'quv motivatsiyasining poydevorini quradi.",
                "Ta'limiy o'yinning yana bir muhim tarbiyaviy ahamiyati — u bolada estetik did va ijodiy qobiliyatni rivojlantiradi. Yorqin, chiroyli o'yin materiallari bola go'zallikni his etishga o'rgatadi. Rolli va ijodiy elementli o'yinlar bolaning tasavvurini va ijodkorligini rivojlantiradi. Shunday qilib, ta'limiy o'yin bola shaxsini har tomonlama — aqliy, axloqiy, estetik, jismoniy va ijtimoiy jihatdan rivojlantiruvchi universal vositadir.",
            ],
        ),
        (
            "O'yinning bola aqliy taraqqiyotiga ta'siri",
            [
                "Ta'limiy o'yin bola aqliy taraqqiyotiga kuchli ijobiy ta'sir ko'rsatadi. O'yin jarayonida bolaning barcha asosiy psixik jarayonlari — diqqat, idrok, xotira, tafakkur, tasavvur — faol ishlaydi va rivojlanadi. O'yin — bu aqliy mashqlar majmuasi bo'lib, u bola miyasini \"isitadi\" va rivojlantiradi. Shu sababli o'yin aqliy taraqqiyotning eng tabiiy va samarali stimulyatoridir.",
                "Diqqatni rivojlantirish — o'yinning muhim ta'siri. O'yin bola diqqatini jamlaydi va ushlab turadi. Bola o'yin qoidalariga, hamkorlarining harakatlariga, o'z navbatiga diqqat qaratishga majbur bo'ladi. \"Nima o'zgardi?\", \"Nima yo'qoldi?\" kabi o'yinlar diqqatni maxsus rivojlantiradi. Diqqat — barcha aqliy faoliyatning asosi bo'lib, uni rivojlantirish g'oyat muhimdir.",
                "Xotirani rivojlantirish — o'yinning yana bir muhim ta'siri. Ko'pgina o'yinlar bolaning eslab qolish va esga olish qobiliyatini mashq qiladi. \"Juft top\" (memori) o'yini, \"Nima o'zgardi?\" o'yini, so'z zanjirlari o'yinlari xotirani maxsus rivojlantiradi. O'yinda bola o'zi xohlab, zo'riqishsiz eslab qoladi — bu \"ixtiyoriy xotira\"ning rivojlanishiga zamin yaratadi, bu esa maktab uchun zarur.",
                "Tafakkurni rivojlantirish — o'yinning eng muhim ta'sirlaridan biridir. O'yinda bola tahlil qiladi, taqqoslaydi, umumlashtiradi, tasniflaydi, xulosa chiqaradi — bularning hammasi tafakkur amallari. \"Nima ortiqcha?\", \"Guruhga ajrat\", \"Bo'ladimi-bo'lmaydimi?\" kabi o'yinlar mantiqiy fikrlashni rivojlantiradi. O'yin orqali bola fikrlashning asosiy usullarini egallaydi va aqliy jihatdan rivojlanadi.",
                "Tasavvur va ijodiy fikrlashni rivojlantirish — o'yinning alohida ta'siri. Rolli va ijodiy o'yinlarda bola xayolot olamini yaratadi, o'zini turli rollarda tasavvur qiladi, yangi vaziyatlarni o'ylab topadi. Tasavvur — ijodkorlikning asosi va u o'yinda eng yaxshi rivojlanadi. \"Agar ...?\" turidagi savollar, ijodiy hikoya o'yinlari bola tasavvurini va ijodiy salohiyatini boyitadi.",
                "Nutq va tafakkur o'rtasidagi aloqa o'yinda eng yaqqol namoyon bo'ladi. O'yinda bola gapiradi va shu bilan birga fikrlaydi; fikrlaydi va shu bilan birga gapiradi. Nutq va tafakkur bir-birini rivojlantiradi. Lug'at o'yinlarida bola yangi so'zlarni o'rganar ekan, u bilan birga yangi tushunchalarni va fikrlash usullarini ham egallaydi. Bu — o'yinning eng chuqur va eng muhim ta'siridir.",
                "O'yin bola aqliy taraqqiyotini umumiy va kompleks tarzda ta'minlaydi. U faqat bir psixik jarayonni emas, balki barchasini bir vaqtda rivojlantiradi. Bundan tashqari, o'yin bolaning bilishga qiziqishini — \"kognitiv motivatsiya\"ni shakllantiradi. Qiziquvchan, bilishga intiluvchi bola — kelajakda muvaffaqiyatli o'quvchi va izlanuvchi shaxsdir. Shu sababli ta'limiy o'yin bola aqliy taraqqiyotining eng samarali vositasi sifatida e'tirof etiladi.",
            ],
        ),
        (
            "O'yinning lug'atni boyitish va faollashtirishdagi samaradorligi",
            [
                "Ta'limiy o'yin lug'atni boyitishda boshqa metodlarga nisbatan yuqori samaradorlikka ega. Buning sababi — o'yinning psixologik tabiatida. O'yinda bola emotsional ko'tarinki holatda bo'ladi, qiziqish va zavq bilan ishtirok etadi. Bunday holatda miya eng faol ishlaydi va material eng yaxshi o'zlashtiriladi. Hissiy bo'yoqli o'rganish — eng mustahkam o'rganishdir, buni zamonaviy neyrofiziologiya ham tasdiqlaydi.",
                "O'yinda yangi so'z real harakat va vaziyat bilan bog'lanadi. \"Magazin\" o'yinida bola \"tarozi\", \"pul\", \"chek\" so'zlarini real harakatlar bilan birga o'rganadi. Bunday bog'liqlik so'zni mustahkam o'zlashtirishni ta'minlaydi. Quruq, kontekstdan tashqari o'rganilgan so'z tez unutiladi, harakat va vaziyat bilan bog'liq so'z esa uzoq saqlanadi. Bu — o'yinning muhim afzalligidir.",
                "O'yin so'zni ko'p marta takrorlash imkonini beradi. Lug'atni mustahkamlash uchun so'z 5-6 marta takrorlanishi kerak. An'anaviy mashqda takrorlash zerikarli, o'yinda esa u tabiiy va qiziqarli. \"Sehrli zanjir\" o'yinida bola o'nlab so'zlarni qayta-qayta aytadi va zerikmaydi. O'yin takrorlashni quvonchli jarayonga aylantiradi va shu orqali samaradorlikni ta'minlaydi.",
                "O'yin passiv lug'atni faollashtirishda ayniqsa samaralidir. Ko'pincha bola so'zni tushunadi, lekin uni nutqida qo'llamaydi. O'yin bolani so'zni faol qo'llashga undaydi: o'yin yutish uchun bola eslab qolgan so'zlarni aytishi, narsalarni nomlashi, tasvirlashi kerak. \"Kim ko'p so'z aytadi?\" o'yini bolani butun passiv lug'atini faollashtirishga majbur qiladi. Faollashtirilgan so'z — bolaning haqiqiy boyligi.",
                "O'yin individual yondashuvga imkon beradi. Tarbiyachi har bir bola imkoniyatiga qarab o'yinda turli vazifalar berishi mumkin: kuchli bolaga murakkabroq, zaif bolaga osonroq. Bu har bir bolaning o'z darajasida rivojlanishini ta'minlaydi. O'yinda zaif bola ham yuta oladi va o'ziga ishonadi, kuchli bola esa yangi cho'qqilarni zabt etadi. Bu — o'yinning yana bir muhim afzalligidir.",
                "O'yin lug'atni tizimlashtirishda samaralidir. Tasniflash o'yinlari (\"Guruhga ajrat\", \"Nima ortiqcha?\") bola lug'atini tartibli tizimga keltiradi. Bola so'zlarni alohida emas, balki o'zaro bog'liq guruhlar (mevalar, sabzavotlar, hayvonlar) sifatida o'zlashtiradi. Tizimlashtirilgan lug'at — mustahkam va oson esga olinadi. Bu o'yinning kognitiv afzalligidir, chunki u xotirani tartibga soladi.",
                "O'yinning samaradorligi ko'plab tadqiqotlarda isbotlangan. Pedagogik eksperimentlar shuni ko'rsatdiki, o'yin metodi bilan o'rganilgan lug'at an'anaviy metodga nisbatan ancha mustahkam va faol o'zlashtiriladi. Bolalar o'yinda olingan so'zlarni uzoq vaqt eslab qoladilar va ularni mustaqil nutqlarida qo'llaydilar. Shu sababli zamonaviy bog'cha pedagogikasi ta'limiy o'yinni lug'at ishining markaziy metodi sifatida tan oladi va keng tavsiya etadi.",
            ],
        ),
        (
            "O'yinning ijtimoiy-shaxsiy rivojlanishdagi ahamiyati",
            [
                "Ta'limiy o'yin nafaqat aqliy va nutqiy, balki ijtimoiy va shaxsiy rivojlanishda ham muhim o'rin tutadi. O'yinda bola boshqa bolalar bilan o'zaro munosabatga kiradi, hamkorlik qiladi, muloqot qiladi. Bu — ijtimoiylashuvning eng tabiiy maktabidir. O'yin orqali bola jamoada yashashni, boshqalar bilan til topishishni va birgalikda ish qilishni o'rganadi.",
                "Birgalikdagi o'yin bolada hamkorlik ko'nikmasini shakllantiradi. Bolalar birga o'ynar ekan, ular vazifalarni taqsimlaydilar, rollarni belgilaydilar, qoidalarni kelishadilar, bir-biriga yordam beradilar. Bu — kelajakda jamoaviy mehnat uchun zaruriy poydevor. Hamkorlikni o'rgangan bola kelajakda jamoada muvaffaqiyatli ishlay oladi va boshqalar bilan til topisha oladi.",
                "O'yin bolada muloqot ko'nikmasini rivojlantiradi. O'yin jarayonida bolalar doimo bir-biri bilan gaplashadilar: savol berishadi, javob berishadi, kelishadilar, bahslashadilar. Bu — dialogik nutqning eng tabiiy maktabi. Bola o'yinda muloqotning barcha shakllarini — salomlashish, so'rash, taklif qilish, kelishish, rad etish — mashq qiladi va o'zlashtiradi.",
                "O'yin bolaning hissiy sohasini rivojlantiradi. O'yinda bola turli his-tuyg'ularni boshdan kechiradi: quvonch, hayajon, yutuq zavqi, yutqazish achchig'i. Bola bu his-tuyg'ularni boshqarishni, ularni adekvat ifodalashni o'rganadi. \"Yutqazsam ham, yig'lamayman\", \"O'rtog'imning yutug'idan quvonaman\" — bunday hissiy yetuklik o'yinda shakllanadi va bu hayot uchun juda muhimdir.",
                "O'yin bolada o'ziga ishonchni shakllantiradi. O'yinda bola muvaffaqiyatga erishadi, narsalarni topadi, savollarga javob beradi, yutadi. Har bir kichik yutuq bola ishonchini mustahkamlaydi. \"Men qila olaman!\" degan ishonch — bola shaxsiyatining eng muhim fazilatidir. O'ziga ishongan bola yangi narsalarni o'rganishdan qo'rqmaydi, qiyinchiliklarga dadil qaraydi.",
                "O'yin bolada axloqiy normalarni shakllantiradi. O'yin qoidalari — bu bola uchun birinchi \"ijtimoiy qonunlar\". Bola qoidalarga rioya qilishni, adolatli bo'lishni, halol o'ynashni o'rganadi. \"Aldash yomon\", \"Navbatni buzish noto'g'ri\", \"Mag'lubni masxara qilmaslik kerak\" — bunday axloqiy tushunchalar o'yin amaliyoti orqali bolada mustahkamlanadi va uning xulqiga aylanadi.",
                "O'yin bolaning umumiy ijtimoiy yetukligini ta'minlaydi. O'yinda bola jamiyat hayotining kichik modelini boshdan kechiradi: u rollar o'ynaydi, munosabatlar o'rnatadi, nizolarni hal qiladi, hamkorlik qiladi. Bularning hammasi bolani real ijtimoiy hayotga tayyorlaydi. Shu sababli mashhur psixolog D.B.Elkonin o'yinni \"bolaning ijtimoiy hayotga tayyorgarlik maktabi\" deb atagan. O'yin — bola shaxsiyatining har tomonlama va uyg'un rivojlanishini ta'minlovchi bebaho pedagogik vositadir.",
            ],
        ),
        (
            "Ta'limiy o'yin samaradorligini oshirish shartlari",
            [
                "Ta'limiy o'yinning samaradorligi bir qator shartlarga bog'liq. Birinchi va eng muhim shart — o'yinning aniq ta'limiy maqsadga ega bo'lishi. O'yin shunchaki o'yin uchun emas, balki muayyan didaktik vazifani hal qilish uchun o'tkazilishi kerak. Maqsadsiz o'yin — quruq vaqt o'tkazishga aylanadi. Tarbiyachi har bir o'yinning maqsadini aniq belgilab olishi va shu maqsadga erishishga intilishi shart.",
                "Ikkinchi shart — o'yinning bola yoshiga va imkoniyatiga mosligi. Juda oson o'yin bolani zeriktiradi, juda qiyin o'yin esa uni qiynaydi va ishonchini so'ndiradi. O'yin bolaning \"yaqin taraqqiyot zonasi\"da bo'lishi kerak — ya'ni bir oz qiyin, lekin bola erisha oladigan darajada. Bunday o'yin bolani rivojlantiradi va unga muvaffaqiyat zavqini beradi.",
                "Uchinchi shart — o'yinning qiziqarli va emotsional bo'lishi. Bola qiziqsa, u o'yinga butun diqqati bilan kirishadi va material yaxshi o'zlashtiriladi. Tarbiyachi o'yinni qiziqarli boshlashi, uni jonli va quvnoq olib borishi, bolalarni rag'batlantirishi kerak. Zerikarli, monoton o'yin o'zining ta'limiy qiymatini yo'qotadi. O'yin ruhi — quvonch va zavqdir.",
                "To'rtinchi shart — o'yin materiallarining sifatli va xilma-xil bo'lishi. Yorqin, chiroyli, mustahkam, bola yoshiga mos materiallar o'yinni jozibali qiladi. Tarbiyachi boy material bazasiga ega bo'lishi va uni doimiy yangilab borishi kerak. Sifatsiz, eski, zerikarli materiallar bola qiziqishini so'ndiradi. Material — o'yinning moddiy asosidir.",
                "Beshinchi shart — o'yinlarning izchil va tizimli olib borilishi. O'yinlar tasodifiy emas, balki rejali, izchil va murakkablashib boruvchi tartibda o'tkazilishi kerak. Tarbiyachi o'yinlarni kalendar rejaga kiritadi, ularni murakkabligi bo'yicha tartibga soladi, takrorlaydi va asta-sekin murakkablashtiradi. Tizimli yondashuv samaradorlikning kafolatidir.",
                "Oltinchi shart — tarbiyachining mahorati va o'yinga munosabati. Tarbiyachi o'yin metodikasini yaxshi bilishi, o'yinni mohirlik bilan tashkil eta olishi va o'zi o'yinga ijobiy munosabatda bo'lishi kerak. Agar tarbiyachi o'yinni \"vaqt yo'qotish\" deb hisoblasa, undan natija bo'lmaydi. O'yinni qadrlaydigan, uni sevib o'tkazadigan tarbiyachigina yuqori samaraga erishadi.",
                "Yettinchi shart — oila bilan hamkorlik. Bog'chada o'tkazilgan o'yinlar uyda davom ettirilsa, samaradorlik bir necha barobar ortadi. Tarbiyachi ota-onalarga bola bilan o'ynaladigan oddiy lug'at o'yinlarini o'rgatadi va ularni faol qatnashishga undaydi. Ota-onalar bola bilan o'ynar ekan, ular nafaqat lug'atni boyitadilar, balki bola bilan hissiy aloqani ham mustahkamlaydilar. Barcha shartlar bajarilganda ta'limiy o'yin o'zining to'liq quvvati bilan ishlaydi va bola lug'atini hamda umumiy taraqqiyotini eng samarali tarzda ta'minlaydi.",
            ],
        ),
    ],
    "refs": COMMON_REFS,
}
