# -*- coding: utf-8 -*-
from ._refs import COMMON_REFS

topic = {
    "num": 10,
    "title": "Bolalar lug'atini boyitishda ta'limiy o'yinlarning roli",
    "reja": [
        "Ta'limiy (didaktik) o'yin tushunchasi va uning tuzilishi.",
        "Ta'limiy o'yinning lug'at boyitishdagi o'rni va funksiyalari.",
        "Lug'atni boyituvchi ta'limiy o'yin turlari.",
        "Ta'limiy o'yinlarni tashkil etish va o'tkazish metodikasi.",
        "Yosh guruhlari bo'yicha o'yinlardan foydalanish va tarbiyachi roli.",
    ],
    "sections": [
        (
            "Ta'limiy (didaktik) o'yin tushunchasi va uning tuzilishi",
            [
                "Ta'limiy (didaktik) o'yin — muayyan ta'limiy maqsadga yo'naltirilgan, qoidalar asosida tashkil qilingan, o'yin shaklidagi pedagogik faoliyatdir. Didaktik o'yinda ta'lim va o'yin uyg'unlashadi: bola o'ynaydi, lekin shu bilan birga o'rganadi. Bu — bog'cha pedagogikasining eng samarali va eng tabiiy ish usullaridan biridir, chunki o'yin — bog'cha yoshidagi bolaning yetakchi faoliyatidir.",
                "Mashhur pedagog va psixologlar didaktik o'yinning ahamiyatini yuqori baholaganlar. K.D.Ushinskiy, Ye.I.Tixiyeva, A.P.Usova, F.Frobel, M.Montessori o'z asarlarida o'yinning ta'limiy va tarbiyaviy qudratini ko'rsatib berdilar. Ular o'yinda bola eng yaxshi o'rganishini, o'yin orqali bilim chuqur va mustahkam o'zlashtirilishini ta'kidladilar. Bu g'oya hozirgi zamon pedagogikasida ham o'z kuchini saqlab qolgan.",
                "Didaktik o'yinning tuzilishi bir necha komponentdan iborat: 1) didaktik vazifa (o'yinning ta'limiy maqsadi — masalan, lug'atni boyitish); 2) o'yin vazifasi (bola uchun o'yin maqsadi — masalan, narsani topish); 3) o'yin harakatlari (o'yinda bajariladigan amallar); 4) o'yin qoidalari (o'yin tartibi); 5) o'yin natijasi (yutuq, baholash). Bu komponentlar yagona tizimda ishlaydi.",
                "Didaktik vazifa — o'yinning yashirin ta'limiy maqsadi. Bola buni bilmaydi, u faqat o'ynayotganini his qiladi. Lekin tarbiyachi uchun bu — asosiy maqsad. Masalan, \"Sehrli qopcha\" o'yinida bola narsalarni paypaslab topadi (o'yin vazifasi), lekin shu bilan birga narsalar nomini, ularning xususiyatlarini o'rganadi (didaktik vazifa). Ana shu ikki vazifaning uyg'unligi — didaktik o'yinning sirli kuchidir.",
                "O'yin harakatlari — bolani o'yinga jalb qiluvchi, uni qiziqarli qiluvchi amallar. Bu harakatlar qancha xilma-xil va qiziq bo'lsa, o'yin shuncha samarali bo'ladi. O'yin harakatlari: narsani yashirish va topish, paypaslab aniqlash, tasvirlab topish, taqqoslash, guruhlash, navbat bilan gapirish, kartochkalarni tanlash. Tarbiyachi har bir o'yin uchun mos va qiziqarli harakatlarni o'ylab topadi.",
                "O'yin qoidalari — o'yinning tartibini belgilovchi shartlar. Qoidalar bolani intizomga, navbatga, adolatga o'rgatadi. Qoidalar sodda, tushunarli va bola yoshiga mos bo'lishi kerak. Masalan: \"Navbat bilan gapiramiz\", \"Topgan bola keyingisini boshlaydi\", \"Qoidaga rioya qilgan bola yutadi\". Qoidalarsiz o'yin betartib bo'lib qoladi va o'zining ta'limiy qiymatini yo'qotadi.",
                "Didaktik o'yin o'zining tabiiy xususiyatlari bilan lug'at ishi uchun ideal vositadir. O'yinda bola erkin, zerikmaydi, charchaydigan emas, balki qiziqish va zavq bilan ishtirok etadi. Bunday holatda yangi so'zlar oson va mustahkam o'zlashtiriladi. \"O'ynab o'rgangan bola — o'rganganini unutmaydi\" degan pedagogik haqiqat aynan didaktik o'yinga taalluqlidir. Shuning uchun u lug'at ishida markaziy o'rin tutadi.",
            ],
        ),
        (
            "Ta'limiy o'yinning lug'at boyitishdagi o'rni va funksiyalari",
            [
                "Ta'limiy o'yin lug'at ishining barcha vazifalarini hal etishda muhim o'rin tutadi. O'yin orqali lug'at boyitiladi (yangi so'zlar kiritiladi), mustahkamlanadi (ma'lum so'zlar takrorlanadi), faollashtiriladi (passiv so'zlar faol qo'llaniladi) va aniqlashtiriladi (so'z ma'nosi chuqurlashtiriladi). Bir o'yinda bir necha vazifa bir vaqtda hal qilinishi mumkin. Bu — o'yinning samaradorlik kalitidir.",
                "Ta'limiy o'yinning birinchi funksiyasi — lug'atni boyitish. Yangi so'zlar o'yin jarayonida tabiiy ravishda kiritiladi. Masalan, \"Magazin\" o'yinida bola yangi mahsulot nomlarini, \"Hayvonot bog'i\" o'yinida yangi hayvon nomlarini o'rganadi. O'yindagi so'z — quruq emas, balki real harakat va vaziyat bilan bog'liq, shuning uchun u oson o'zlashtiriladi va xotirada mustahkam saqlanadi.",
                "Ikkinchi funksiya — lug'atni faollashtirish. O'yinda bola passiv lug'atidagi so'zlarni faol qo'llashga majbur bo'ladi. \"Kim ko'p so'z aytadi?\" o'yinida bola eslab qolgan barcha so'zlarni faol esga oladi va aytadi. \"Tasvirlab top\" o'yinida bola narsani tasvirlash uchun ko'p sifat va belgilarni qo'llaydi. Shunday qilib, passiv so'zlar faol nutqqa o'tadi va bolaning haqiqiy boyligiga aylanadi.",
                "Uchinchi funksiya — so'z ma'nosini aniqlashtirish va chuqurlashtirish. O'yinda bola so'zning aniq ma'nosini, uning chegaralarini, sinonim va antonimlarini o'rganadi. \"Aksini ayt\" o'yini antonimlarni, \"Bir xil ma'noli so'z\" o'yini sinonimlarni mustahkamlaydi. \"Nima ortiqcha?\" o'yini umumlashtiruvchi tushunchalarni shakllantiradi. O'yin — so'z ma'nosini chuqurlashtirishning eng tabiiy yo'lidir.",
                "To'rtinchi funksiya — lug'atni tizimlashtirish. O'yin orqali bola so'zlarni guruhlarga, kategoriyalarga ajratishni o'rganadi: mevalar, sabzavotlar, hayvonlar, mebellar, kiyimlar. \"Nima qayerga?\" o'yini, \"Guruhga ajrat\" o'yini bola lug'atini tartibga soladi va tizimga keltiradi. Bu — bola tafakkurini ham rivojlantiradi, chunki tasniflash — yuqori aqliy funksiyadir.",
                "Didaktik o'yin lug'at bilan birga boshqa nutq tomonlarini ham rivojlantiradi. O'yinda bola grammatik shakllarni qo'llaydi, tovushlarni to'g'ri talaffuz qiladi, dialogik va monologik nutq ko'nikmalarini mashq qiladi. Demak, didaktik o'yin — kompleks vosita bo'lib, u nutqning barcha tomonlarini bir vaqtda rivojlantiradi. Bu — uning yana bir muhim afzalligidir.",
                "Ta'limiy o'yin nafaqat nutqni, balki bolaning umumiy taraqqiyotini ham ta'minlaydi. O'yinda bola diqqat, xotira, tafakkur, tasavvur, irodani rivojlantiradi; intizom, navbat, adolat, hamkorlik kabi axloqiy fazilatlarni egallaydi; o'ziga ishonch va ijtimoiy ko'nikmalarni shakllantiradi. Shu sababli didaktik o'yin — bola shaxsini har tomonlama rivojlantiruvchi universal pedagogik vositadir.",
            ],
        ),
        (
            "Lug'atni boyituvchi ta'limiy o'yin turlari",
            [
                "Lug'atni boyituvchi ta'limiy o'yinlar uch asosiy guruhga bo'linadi: 1) predmetlar bilan o'ynaladigan o'yinlar; 2) ko'rgazmali (surat) o'yinlar; 3) so'zli (og'zaki) o'yinlar. Har bir guruh o'z xususiyatlari va imkoniyatlariga ega va ular bola yoshiga qarab tanlanadi. Kichik yoshda predmetli o'yinlar, kattaroq yoshda so'zli o'yinlar ustun bo'ladi.",
                "Predmetlar bilan o'ynaladigan o'yinlar — real predmetlar, o'yinchoqlar, tabiiy materiallar bilan o'tkaziladigan o'yinlar. \"Sehrli qopcha\" (paypaslab predmet topish va nomlash); \"Nima o'zgardi?\" (predmetlar joyini eslab qolish); \"Bir xil narsani top\" (juftlash); \"Ajoyib quticha\" o'yinlari shu guruhga kiradi. Bu o'yinlar kichik yosh bolalari uchun eng mos, chunki ularda real predmet ishtirok etadi.",
                "Ko'rgazmali (surat) o'yinlar — suratlar va kartochkalar bilan o'tkaziladigan o'yinlar. \"Lotto\" (suratli kartochkalarni mos rasmga qo'yish); \"Domino\" (suratlarni juftlash); \"Juft top\" (memori); \"Nima ortiqcha?\" (mantiqiy ortiqchani topish); \"Qism va butun\" (qismlardan butunni yig'ish) o'yinlari bu guruhga kiradi. Bu o'yinlar bolaning ko'rgazmali-obrazli fikrlashiga mos va keng qo'llaniladi.",
                "So'zli (og'zaki) o'yinlar — hech qanday material talab qilmaydigan, faqat so'zga tayanadigan o'yinlar. \"Aksini ayt\" (antonimlar); \"Kim ko'p so'z aytadi?\" (mavzu bo'yicha so'zlar); \"Davom ettir\" (zanjir o'yinlari); \"Bo'ladimi-bo'lmaydimi?\" (mantiqiy o'yinlar); \"Sehrli zanjir\" (oxirgi tovush bilan boshlanuvchi so'zlar). Bu o'yinlar kattaroq yosh bolalari uchun mos, chunki ular yetuk lug'at va tafakkurni talab qiladi.",
                "Eng mashhur lug'at o'yinlaridan ba'zilari: \"Magazin\" — bola mahsulot nomini aytib, uni \"sotib oladi\", bu lug'atni boyitadi va dialogik nutqni rivojlantiradi. \"Pochta\" — bola xat \"yo'llaydi\" va manzilni aytadi. \"Sayohat\" — bola turli joylar va ularga oid so'zlarni o'rganadi. \"Kasblar\" — bola turli kasblarni va ularga oid asboblarni nomlaydi.",
                "Tasniflash va umumlashtirish o'yinlari lug'atni tizimlashtiradi: \"Nima ortiqcha?\" (bir guruhga mansub bo'lmagan narsani topish); \"Guruhga ajrat\" (mevalar, sabzavotlar, hayvonlar); \"Umumiy so'zni ayt\" (olma, nok, uzum — mevalar). Bu o'yinlar bola tafakkurini ham rivojlantiradi va lug'atni mantiqiy tizimga keltiradi.",
                "Tasvirlash va taxmin qilish o'yinlari ravon nutq bilan lug'atni birga rivojlantiradi: \"Tasvirlab top\" (tarbiyachi narsani tasvirlaydi, bola topadi yoki aksincha); \"Topishmoq\" (xalq topishmoqlari orqali narsalarni topish); \"Kim men?\" (bola biror narsa yoki hayvon haqida gapiradi, boshqalar topadi). Bu o'yinlar bola lug'atini boyitadi, tasvirlash ko'nikmasini shakllantiradi va tafakkurni rivojlantiradi. Bunday o'yinlar bog'cha hayotining ajralmas qismi bo'lishi shart.",
            ],
        ),
        (
            "Ta'limiy o'yinlarni tashkil etish va o'tkazish metodikasi",
            [
                "Ta'limiy o'yinni samarali o'tkazish uchun tarbiyachi unga puxta tayyorgarlik ko'rishi kerak. Tayyorgarlik bosqichi: 1) o'yin maqsadini (didaktik vazifani) aniqlash; 2) o'yin turini va mazmunini tanlash; 3) kerakli materiallarni (predmetlar, suratlar, kartochkalar) tayyorlash; 4) o'yin qoidalarini va harakatlarini o'ylab chiqish; 5) o'yinning borishini rejalashtirish. Yaxshi tayyorgarlik — muvaffaqiyatning yarmi.",
                "O'yinni o'tkazish bosqichlari: 1) o'yinga qiziqish uyg'otish (kirish, motivatsiya); 2) o'yin mazmuni va qoidalarini tushuntirish; 3) o'yin harakatlarini ko'rsatish (namuna); 4) o'yinning o'zi (bolalar o'ynaydi); 5) o'yin natijalarini umumlashtirish va baholash. Har bir bosqich aniq va izchil amalga oshiriladi. Tarbiyachi o'yinning borishini kuzatadi va kerak bo'lganda yo'naltiradi.",
                "O'yinga qiziqish uyg'otish — muvaffaqiyatning muhim sharti. Tarbiyachi o'yinni qiziqarli boshlaydi: sirli quticha, kutilmagan mehmon (qo'g'irchoq), qiziq savol, jumboq. Bola qiziqsa, u o'yinga butun diqqati bilan kirishadi va material yaxshi o'zlashtiriladi. Qiziqishsiz o'yin — quruq mashqqa aylanadi va o'zining sehrli kuchini yo'qotadi.",
                "O'yin qoidalarini tushuntirish aniq, sodda va qisqa bo'lishi kerak. Tarbiyachi qoidalarni bola tushunadigan tilda aytadi va kerak bo'lsa, namuna ko'rsatadi. Murakkab va uzun tushuntirish bolani charchatadi va o'yindan bezdiradi. Eng yaxshisi — qoidalarni o'yin jarayonida, harakat bilan ko'rsatib tushuntirish. \"Mana, men shunday qilaman, endi sen ham shunday qil\".",
                "O'yin davomida tarbiyachining roli — kuzatish, yo'naltirish va qo'llab-quvvatlash. Tarbiyachi o'yinga aralashib, uni boshqaradi, lekin bolalarning erkinligini bo'g'maydi. U qiyinchilikka uchragan bolaga yordam beradi, faol bo'lmagan bolani rag'batlantiradi, nizolarni hal qiladi. Tarbiyachi o'yinning ruhini saqlaydi — u quvnoq, erkin va do'stona bo'lishi kerak.",
                "O'yin natijalarini baholash — muhim yakuniy bosqich. Tarbiyachi o'yinni umumlashtiradi: kim qanday qatnashdi, nimani o'rgandik, kim yutdi. Baholash ijobiy va rag'batlantiruvchi bo'lishi kerak. Har bir bola o'zining hissasi uchun maqtaladi. Mag'lub bo'lgan bolalar ham qo'llab-quvvatlanadi: \"Bugun yutqazding, lekin keyingi safar albatta yutasan\". Baholash bolani keyingi o'yinga ilhomlantirishi shart.",
                "O'yinlarni rejalashtirish va tizimlashtirish — tarbiyachining muhim vazifasidir. O'yinlar tasodifiy emas, balki rejali va izchil olib borilishi kerak. Tarbiyachi o'yinlarni kalendar-mavzu rejasiga kiritadi, ularni murakkabligi bo'yicha tartibga soladi, har bir o'yinning maqsadini aniqlaydi. O'yinlar takrorlanadi, lekin har safar biroz o'zgartirilib, murakkablashtirilib boriladi. Bunday tizimli yondashuv lug'at ishining samaradorligini ta'minlaydi.",
            ],
        ),
        (
            "Yosh guruhlari bo'yicha o'yinlardan foydalanish va tarbiyachi roli",
            [
                "Ta'limiy o'yinlardan foydalanishda har bir yosh guruhining xususiyatlarini hisobga olish shart. Kichik guruhda (3-4 yosh) o'yinlar sodda, qisqa va asosan predmetli bo'ladi. Bola hali murakkab qoidalarni tushunmaydi va uzoq diqqat qila olmaydi. \"Sehrli qopcha\", \"Bir xil narsani top\", \"Nima yo'qoldi?\" kabi sodda o'yinlar mos. Tarbiyachi o'yinda faol qatnashadi va bolalarni yetaklaydi.",
                "O'rta guruhda (4-5 yosh) o'yinlar murakkablashadi, qoidalar ko'payadi, so'zli o'yinlar kiritiladi. \"Magazin\", \"Aksini ayt\", \"Nima ortiqcha?\", \"Tasvirlab top\" kabi o'yinlar mos. Bola endi murakkabroq qoidalarni tushunadi va uzoqroq diqqat qila oladi. Tarbiyachi o'yinni boshqaradi, lekin bolalarga ko'proq erkinlik beradi va ularning mustaqilligini rag'batlantiradi.",
                "Katta guruhda (5-6 yosh) o'yinlar yanada murakkab va xilma-xil bo'ladi. So'zli o'yinlar, mantiqiy o'yinlar, raqobat elementi bo'lgan o'yinlar keng qo'llaniladi. \"Sehrli zanjir\", \"Davom ettir\", \"Kim ko'p so'z aytadi?\", \"Topishmoqlar\", \"Bo'ladimi-bo'lmaydimi?\" kabi o'yinlar mos. Bolalar o'yinni o'zlari tashkil eta oladilar, qoidalarga rioya qiladilar va g'oliblikni adolatli baholaydilar.",
                "Maktabga tayyorlov guruhida (6-7 yosh) o'yinlar maktab talablari bilan bog'lanadi. So'z va tovush tahliliga oid o'yinlar, so'z yasalishiga oid o'yinlar, mantiqiy va ijodiy o'yinlar ustun bo'ladi. \"So'zni bo'g'inlarga ajrat\", \"Birinchi tovushni top\", \"Yangi so'z yasa\" kabi o'yinlar bolani savod o'rgatishga tayyorlaydi. Bolalar mustaqil va ijodiy o'ynay oladilar.",
                "Tarbiyachining roli yosh bilan o'zgaradi. Kichik guruhda tarbiyachi o'yinning markazida — u yetaklaydi, ko'rsatadi, har bir qadamni boshqaradi. O'rta guruhda tarbiyachi yo'naltiruvchi — u o'yinni boshlaydi va kuzatadi, lekin bolalarga erkinlik beradi. Katta guruhda tarbiyachi maslahatchi — u o'yin sharoitini yaratadi va kerak bo'lganda yordam beradi, lekin bolalar mustaqil o'ynaydilar. Bu — bola mustaqilligini bosqichma-bosqich rivojlantirish tamoyilidir.",
                "Tarbiyachi o'yinlar uchun boy material bazasiga ega bo'lishi kerak. U turli xil didaktik o'yinlarni to'playdi, yasaydi va saqlaydi: predmetli o'yinlar to'plami, surat va kartochkalar katalogi, lotto va domino o'yinlari, mozaika va konstruktorlar. Materiallar tartibli, sifatli va bola yoshiga mos bo'lishi shart. Boy material bazasi — samarali o'yin faoliyatining moddiy asosidir.",
                "Ta'limiy o'yinlardan foydalanishda oila bilan hamkorlik muhim ahamiyatga ega. Tarbiyachi ota-onalarga uy sharoitida bola bilan o'ynaladigan oddiy lug'at o'yinlarini o'rgatadi: \"Aksini ayt\", \"Bir xil ma'noli so'z\", \"Nima ortiqcha?\", \"Davom ettir\". Bu o'yinlar maxsus material talab qilmaydi va ularni yo'lda, transportda, uy yumushlari paytida ham o'ynash mumkin. Ota-onalar bunday o'yinlar orqali bola lug'atini boyitishda faol qatnasha oladilar. Bog'cha va oila birgalikda o'ynaganda bola lug'ati eng to'liq va mukammal rivojlanadi.",
            ],
        ),
    ],
    "refs": COMMON_REFS,
}
