# -*- coding: utf-8 -*-
from ._refs import COMMON_REFS

topic = {
    "num": 8,
    "title": "Maktabgacha yoshdagi bolalarni monologik nutqga o'rgatish metodikasi",
    "reja": [
        "Monologik nutq tushunchasi, xususiyatlari va turlari.",
        "Monologik nutqni o'rgatishning psixologik-pedagogik asoslari.",
        "Tasvirlash va hikoya qilishga o'rgatish metodikasi.",
        "Qayta hikoya qilish va ijodiy hikoya tuzishga o'rgatish.",
        "Monologik nutqni rivojlantirishda vositalar va baholash.",
    ],
    "sections": [
        (
            "Monologik nutq tushunchasi, xususiyatlari va turlari",
            [
                "Monologik nutq — bir kishining boshqalar oldida batafsil, izchil, mustaqil va to'liq tarzda o'z fikrlarini bayon qilishidir. \"Monolog\" so'zi yunoncha \"monos\" (yagona) va \"logos\" (so'z) so'zlaridan tashkil topgan. Dialogdan farqli o'laroq, monolog bir kishi tomonidan amalga oshiriladi va tinglovchilardan faqat idrok etish, tinglashni talab qiladi. Bu — nutqning eng murakkab va eng yuqori shaklidir.",
                "Monologik nutqning asosiy xususiyatlari quyidagilar: 1) bir tomonlamalik — bir kishi gapiradi; 2) kengaygan tuzilish — to'liq jumlalar va batafsil bayon; 3) izchillik — fikrlar mantiqiy ketma-ketlikda; 4) rejalashtirilganlik — oldindan o'ylangan tuzilish; 5) kontekstdan mustaqillik — vaziyatga tayanmasdan tushunarli bo'lish; 6) til vositalarining ongli tanlanishi. Bu xususiyatlar monologni ancha murakkab nutq shakliga aylantiradi.",
                "Monologik nutqning dialogik nutqdan farqi shundaki, dialog tabiiy, hissiy, vaziyatga bog'liq va qisqa bo'lsa, monolog rejalashtirilgan, mantiqiy, mustaqil va kengaygan bo'ladi. Dialogda suhbatdosh yordam beradi, savol bilan yo'naltiradi; monologda esa so'zlovchi o'zi butun mas'uliyatni o'z zimmasiga oladi. Shu sababli monolog bola uchun ancha qiyin va u keyinroq shakllanadi.",
                "Monologik nutqning asosiy turlari: 1) tasvirlash (opisaniye) — predmet, hayvon, manzara, voqelikning belgilari, xususiyatlarini ko'rsatish; 2) hikoya qilish (povestvovaniye) — voqealarni vaqt ketma-ketligida bayon qilish; 3) mulohaza (rassujdeniye) — sabab-natija aloqalari, fikrning rivoji va xulosa. Bog'cha yoshida birinchi ikki tur asosiy, mulohaza esa kurtak holida bo'ladi.",
                "Tasvirlash — predmet yoki hodisaning belgilarini, xususiyatlarini, qismlarini bir vaqtda mavjud holda bayon qilishdir. Tasvirlashda statik holat aks etadi va u \"qanday?\" degan savolga javob beradi. Tasvirlashning tuzilishi: 1) umumiy tushuncha (bu nima?); 2) belgilar va xususiyatlar; 3) qismlar; 4) vazifa va ahamiyat; 5) shaxsiy munosabat (men buni yaxshi ko'raman).",
                "Hikoya qilish — voqealar, hodisalar, harakatlarni vaqt ketma-ketligida bayon qilishdir. Hikoya \"nima sodir bo'ldi?\" degan savolga javob beradi va dinamik xarakterga ega. Hikoyaning tuzilishi klassik: 1) boshlanma (kirish, vaziyat tasviri); 2) rivoj (asosiy voqealar); 3) yakun (xulosa, natija). Bu tuzilish bola tomonidan asta-sekin o'zlashtiriladi va mustahkamlanadi.",
                "Mulohaza — eng murakkab monolog turi bo'lib, sabab-natija aloqalari, dalil va xulosalar bilan bog'liq. \"Nima uchun?\" degan savolga javob beradi. Mulohazaning tuzilishi: 1) tezis (asosiy fikr); 2) dalillar (isbotlar); 3) xulosa. Bu tur bog'cha yoshida hali to'liq shakllanmaydi, lekin uning kurtaklari katta va maktabga tayyorlov guruhlarida paydo bo'ladi: \"Men buni yaxshi ko'raman, chunki ...\".",
            ],
        ),
        (
            "Monologik nutqni o'rgatishning psixologik-pedagogik asoslari",
            [
                "Monologik nutqni o'rgatish chuqur psixologik va pedagogik asoslarga tayanadi. Psixolog L.S.Vigotskiy, A.A.Leontev, S.L.Rubinshteyn, D.B.Elkonin va boshqalarning tadqiqotlari monologik nutqning shakllanish qonuniyatlarini ochib bergan. Ular monolog dialogdan keyin va uning zaminida rivojlanishini, monolog uchun maxsus aqliy va nutqiy mexanizmlar zarurligini ko'rsatib berdilar.",
                "Monologik nutq aqliy taraqqiyot bilan chambarchas bog'liq. Monolog tuzish uchun bola mavzuni rejalashtirishi, fikrlarni mantiqiy tartibga solishi, sabab-natija aloqalarini anglashi, vaqt ketma-ketligini saqlashi kerak. Bularning hammasi — yuqori aqliy funksiyalar. Shu sababli monologik nutqni rivojlantirish bir vaqtning o'zida bola tafakkurini ham rivojlantiradi. Bu ikki jarayon ajralmas.",
                "Monologik nutqning rivojlanishida \"ichki nutq\" muhim rol o'ynaydi. Vigotskiy ta'kidlaganidek, bola avval ovoz chiqarib fikrlaydi (tashqi nutq), keyin esa ichki nutqqa o'tadi — ya'ni fikrlarni ovoz chiqarmasdan tartibga soladi. Monolog tuzishdan oldin bola ichki nutqda uni rejalashtiradi. Bu mexanizm bog'cha yoshida endi shakllana boshlaydi va tarbiyachi uni qo'llab-quvvatlashi kerak.",
                "Monologik nutqni o'rgatish uchun bola ma'lum darajada psixologik tayyorgarlikka ega bo'lishi kerak: 1) yetarli lug'at boyligi; 2) grammatik tuzilishni o'zlashtirish; 3) tovushlarni to'g'ri talaffuz qilish; 4) dialogik nutq ko'nikmalari; 5) diqqat va xotira rivojlanishi; 6) mantiqiy fikrlashning kurtaklari. Shu sababli monologik nutq asosan o'rta va katta guruhlarda intensiv rivojlantiriladi.",
                "Pedagogik nuqtai nazardan monologik nutqni o'rgatishning bir qator tamoyillari mavjud: 1) namunaviylik — tarbiyachining namuna hikoyasi; 2) izchillik — oddiydan murakkabga; 3) ko'rgazmalilik — surat, predmet, sxemalardan foydalanish; 4) faollik — bolaning aktiv qatnashishi; 5) individuallik — har bir bola imkoniyatini hisobga olish. Bu tamoyillar yagona tizimda ishlaydi.",
                "Monologik nutqni o'rgatishda \"yordamchi vositalar\" muhim. Boshida bola mustaqil hikoya tuza olmaydi, shu sababli unga turli yordamchi vositalar taqdim etiladi: tarbiyachining namuna hikoyasi, savollar rejasi, surat seriyasi, model va sxemalar, hikoyaning boshlanmasi. Asta-sekin bu yordamlar kamayadi va bola mustaqil hikoyaga o'tadi. Bu — \"yaqin taraqqiyot zonasi\" tamoyilining amaliy ifodasidir.",
                "Monologik nutqni o'rgatishda motivatsiya hal qiluvchi ahamiyatga ega. Bola hikoyani \"shunchaki topshiriq uchun\" emas, balki real ehtiyoj va qiziqish bilan tuzishi kerak. Tarbiyachi shunday vaziyatlar yaratadi-ki, bolada hikoya qilish istagi paydo bo'ladi: \"O'rtog'ingga sevimli o'yinchog'ing haqida gapir\", \"Kichkina bolalar uchun ertak to'qib ber\", \"Onangga bugun bog'chada nima qilganingni hikoya qilib berasan\". Motivatsiya — monologning jonidir.",
            ],
        ),
        (
            "Tasvirlash va hikoya qilishga o'rgatish metodikasi",
            [
                "Tasvirlashga o'rgatish — monologik nutqni rivojlantirishning birinchi va eng oddiy bosqichidir. Tasvirlash uchun real predmet, o'yinchoq, surat yoki tabiat hodisasi tanlanadi. Tarbiyachi avval bolalar bilan birgalikda predmetni ko'rib chiqadi, uning belgilari va xususiyatlarini aniqlaydi, keyin esa tasvirlash namunasini ko'rsatadi va bolalarni mustaqil tasvirlashga undaydi.",
                "Tasvirlashga o'rgatish bosqichlari: 1) predmetni idrok etish (ko'rish, ushlash, paypaslash); 2) belgilarini aniqlash (savol-javob orqali); 3) tarbiyachining namuna tasviri; 4) reja yoki model asosida birgalikda tasvirlash; 5) bolaning mustaqil tasvirlashi. Har bir bosqich o'zlashtirilgandan keyin keyingisiga o'tiladi. Bu izchillik muvaffaqiyatning kalitidir.",
                "Tasvirlash modeli (sxemasi) bolaga katta yordam beradi. Model — tasvirlash tuzilishini ko'rgazmali ko'rsatuvchi belgilar yoki rasmlar to'plamidir. Masalan: rang uchun — rangli dog'lar; shakl uchun — geometrik figuralar; o'lcham uchun — katta va kichik doiralar; vazifa uchun — qo'l rasmi. Bola modelga qarab tasvirlashning barcha tomonlarini eslab qoladi va to'liq tasvirlay oladi.",
                "Qiyoslab tasvirlash — murakkabroq, lekin samarali usul. Ikkita predmet (masalan, olma va nok, mushuk va it, qish va yoz) qiyoslanadi: ularning o'xshash va farqli tomonlari aniqlanadi va bayon qilinadi. \"Olma ham, nok ham mevalar. Ikkalasi ham shirin. Lekin olma dumaloq, nok cho'zinchoq. Olma qizil, nok sariq\". Bunday tasvirlash bola fikrini chuqurlashtiradi va taqqoslash ko'nikmasini rivojlantiradi.",
                "Hikoya qilishga o'rgatish tasvirlashdan keyin boshlanadi. Hikoya — voqealarni vaqt ketma-ketligida bayon qilish. Hikoya qilishning asosiy turlari: surat seriyasi bo'yicha hikoya, bitta surat bo'yicha hikoya, o'yinchoq bo'yicha hikoya, tajriba (real voqea) haqida hikoya. Har bir tur o'z usullari va vositalarini talab qiladi va izchil ravishda o'rgatiladi.",
                "Surat seriyasi bo'yicha hikoya qilish — eng samarali ish turlaridan biri. 3-4 ta surat voqealar tartibida tasvirlangan bo'ladi. Bosqichlar: 1) suratlar tartibini aniqlash (avval-keyin-oxir); 2) har bir suratni ko'rib chiqish va u bo'yicha gap tuzish; 3) suratlar o'rtasidagi bog'liqlikni aniqlash; 4) butun voqeani bog'liq hikoya sifatida bayon qilish. Bu mashq bola mantiqiy va vaqt ketma-ketligi bo'yicha fikrlashni rivojlantiradi.",
                "Tajriba haqida hikoya — bola o'z hayotidan voqea aytib berishi. Mavzular bolaga yaqin va his-tuyg'uli bo'lishi shart: \"Tug'ilgan kunim\", \"Sayohatimiz\", \"Yangi o'yinchog'im\", \"Bobomникида\". Tarbiyachi savollar bilan bolaga yordam beradi va hikoyani boshqaradi. Bunday hikoyalar bolaga eng oson keladi, chunki u real, his qilgan voqea haqida gapiradi. Bu — mustaqil monologik nutqqa o'tishning eng tabiiy yo'lidir.",
            ],
        ),
        (
            "Qayta hikoya qilish va ijodiy hikoya tuzishga o'rgatish",
            [
                "Qayta hikoya qilish — bola eshitgan badiiy asarni o'z so'zlari bilan, lekin mazmunini saqlagan holda aytib berishidir. Bu — monologik nutqni rivojlantirishning eng keng tarqalgan va eng samarali usullaridan biri. Qayta hikoya qilish bola xotirasini, mantiqiy fikrlashni, lug'at va grammatikani, ravon nutqni bir vaqtda rivojlantiradi. Shu sababli u bog'cha pedagogikasining markazida turadi.",
                "Qayta hikoya uchun asar tanlash mezonlari: 1) hajmi mos (3-5 daqiqa o'qiladigan); 2) syujeti aniq va izchil; 3) til sodda, lekin badiiy va boy; 4) personajlar oz va aniq; 5) axloqiy g'oya tushunarli; 6) bola yoshiga mos. Mos asarlar: \"Sholg'om\", \"Bo'g'irsoq\", \"Uch ayiq\", L.Tolstoyning kichik hikoyalari, K.Ushinskiyning hikoyalari.",
                "Qayta hikoya qilishning bosqichlari: 1) asarni ifodali o'qib berish; 2) mazmun bo'yicha suhbat (kim qatnashdi, nima bo'ldi, qanday tugadi); 3) asarning ikkinchi marta o'qilishi (qayta hikoyaga sozlanish bilan); 4) bolalarning qayta hikoya qilishi (butun yoki qism-qismdan); 5) baholash va to'g'rilash. Har bir bosqich muhim va ularning birortasini ham o'tkazib yuborib bo'lmaydi.",
                "Qayta hikoya qilishning turli shakllari mavjud: 1) to'liq qayta hikoya — butun asarni bir bola aytib beradi; 2) qism-qismdan qayta hikoya — bir necha bola navbat bilan qismlarni aytadi; 3) rolma-rol qayta hikoya — dialogli asarlarda personajlar bo'lib aytish; 4) sxema yoki rasm asosida qayta hikoya. Tarbiyachi bolalar imkoniyatiga qarab shaklni tanlaydi.",
                "Ijodiy hikoya tuzish — monologik nutqning eng yuqori va eng murakkab ko'rinishidir. Bunda bola tayyor matn asosida emas, balki o'zining xayoli va tasavvuri yordamida yangi voqea to'qib chiqaradi. Ijodiy hikoya bola fantaziyasini, ijodiy fikrlashni, mustaqillikni va albatta nutqni rivojlantiradi. Bu tur asosan katta va maktabga tayyorlov guruhlarida olib boriladi.",
                "Ijodiy hikoyaning turlari: 1) berilgan boshlanmani davom ettirish (\"Bir kuni o'rmonda quyoncha sayr qilib yurganda ...\"); 2) berilgan mavzu bo'yicha hikoya (\"Mening sehrli sayohatim\"); 3) berilgan personajlar bilan hikoya (quyon, tulki va ayiq haqida); 4) tasvir yoki rasmga qarab to'qima hikoya; 5) o'zgartirilgan ertak (tanish ertakni boshqacha tugatish). Har bir tur bolaning ijodiy salohiyatini rivojlantiradi.",
                "Ijodiy hikoya tuzishga o'rgatishda tarbiyachi avval namuna ko'rsatadi va bolaga yordam beradi. Savollar bilan yo'naltiradi: \"Quyoncha qayerga bordi?\", \"U kim bilan uchrashdi?\", \"Keyin nima bo'ldi?\", \"Voqea qanday tugadi?\". Asta-sekin yordam kamayadi va bola mustaqil ijodiy hikoyalar tuza oladigan bo'ladi. Tarbiyachi bola ijodini qo'llab-quvvatlashi, hech qachon \"noto'g'ri\" deb baholamasligi kerak — ijodda har qanday tasavvur o'rinli.",
            ],
        ),
        (
            "Monologik nutqni rivojlantirishda vositalar va baholash",
            [
                "Monologik nutqni rivojlantirishda turli xil vositalardan foydalaniladi. Eng asosiy vositalar: suratlar va surat seriyalari; o'yinchoqlar va real predmetlar; modellar va sxemalar; bolalar adabiyoti kitoblari; qo'g'irchoq teatri va flanelegraf; tabiat va atrof-muhit; bolaning shaxsiy tajribasi. Har bir vosita o'z imkoniyatlariga ega va ularni mohirlik bilan qo'llash tarbiyachining mahoratiga bog'liq.",
                "Suratlar va surat seriyalari — monologik nutq uchun eng ko'p ishlatiladigan vosita. Bog'cha tarbiyachisi mavzular bo'yicha boy surat katalogiga ega bo'lishi kerak: predmet suratlari, syujet suratlari, surat seriyalari, manzara suratlari, muammoli suratlar. Suratlar yorqin, aniq, bola yoshiga mos va sifatli bo'lishi shart. Suratlar bilan ish — hikoya tuzishning poydevoridir.",
                "Modellar va sxemalar — monologik nutq tuzilishini ko'rgazmali ko'rsatuvchi yordamchi vositalar. Tasvirlash modeli, hikoya modeli, mulohaza modeli alohida ishlab chiqiladi. Model — bolaga hikoya tuzilishini eslab qolish va unga rioya qilish imkonini beradi. Bu usul (mnemotexnika) hozirgi zamon pedagogikasida keng qo'llaniladi va yuqori samara beradi.",
                "Qo'g'irchoq teatri va dramalashtirish — monologik nutqni rivojlantirishning yorqin va qiziqarli shakllaridan biri. Bola qo'g'irchoq orqali yoki o'zi rol o'ynab, hikoya yoki ertak mazmunini namoyish etadi. Bu faoliyat bolada nutq bilan birga ijodiy qobiliyat, o'ziga ishonch, jamoa oldida chiqish ko'nikmalarini shakllantiradi. Teatr — bog'cha hayotining eng sevimli faoliyatlaridan biridir.",
                "Monologik nutqni baholash — tarbiyachining muhim vazifasidir. Baholash mezonlari: 1) hikoyaning to'liqligi (barcha qismlar bormi); 2) izchillik (mantiqiy ketma-ketlik); 3) bog'liqlik (jumlalar o'zaro bog'langanmi); 4) til to'g'riligi (grammatika va lug'at); 5) ifodalilik (ohang, his-tuyg'u); 6) mustaqillik (yordamsiz tuza oldimi). Har bir mezon bo'yicha individual ko'rsatkich olinadi.",
                "Baholash natijasida har bir bola uchun individual ish rejasi tuziladi. Monologik nutqi yaxshi rivojlangan bolalar uchun murakkabroq vazifalar (ijodiy hikoya, mulohaza); o'rtacha bolalar uchun mustahkamlash; orqada qolgan bolalar uchun qo'shimcha individual mashg'ulotlar va ota-onalar bilan kelishuv. Diagnostika — boshqarish vositasi, individuallashtirish esa samaradorlik kalitidir.",
                "Monologik nutqni rivojlantirishda oila bilan hamkorlik muhim ahamiyatga ega. Tarbiyachi ota-onalarga uy sharoitida olib boriladigan ishlar bo'yicha tavsiyalar beradi: bola bilan har kuni kitob o'qish va uni qayta aytib berishni so'rash; bolaning kunlik voqealar haqidagi hikoyasini eshitish; oilaviy voqealar (sayohat, bayram, mehmon) haqida bola hikoya qilishini rag'batlantirish; bola tuzgan ijodiy hikoyalarni e'tibor bilan tinglash. Bog'cha va oila birgalikda ishlaganda bola monologik nutqi to'liq va mukammal rivojlanadi.",
            ],
        ),
    ],
    "refs": COMMON_REFS,
}
